### ISSUE TITLE
Can I return a err in success response interceptor 

### ISSUE THREAD

**Issue by luxueyan** [axios/axios#1064]
Can I return a reject promise or err in success callback. And can I set a global err handler for this err?
```javascript
axios.interceptors.response.use(function(res) {
	if(res.data.code === 401) {
		localStorage.removeItem('token');
		store.dispatch(sessionOutSuccess(err.message));
	}
	return Promise.reject(new Error('err in res'));
});

```

**Comment by robaxelsen** [comment]
Hi @luxueyan, and thanks for your submitting your issue. You might have found a solution to this by now, but it's also covered in the ["Interceptors" section in the documentation](https://github.com/axios/axios#interceptors). Please have a look and see if that helps.

-----

@mzabriskie @nickuraltsev @rubennorte in accordance with the [Collaborator Guide](https://github.com/axios/axios/blob/master/COLLABORATOR_GUIDE.md) I propose to close this issue on 16.01.2018 if no response from OP.

**Comment by rubennorte** [comment]
thanks @robaxelsen

**Comment by athrunsun** [comment]
@robaxelsen @rubennorte I don't think this is covered in ["Interceptors" section in the documentation](https://github.com/axios/axios#interceptors).

The OP is asking if we can return a rejected promise inside a response interceptor, and most important, he is using `res.data.code`, NOT `res.status`. I think that interceptor is used to handle a response with 200 http status code and { code: 401 } as response body, so there's no chance to catch that "error" in the documented way. And that's why the OP is asking if we can specifically return a rejected promise to handle a custom error code in response data.

I would add up to the OP's question that, can we throw an `Error` inside response interceptor? Can that error be caught in a catch call afterward? e.g.:

```javascript
axios.request(...).catch(error => {...})
```

**Comment by realtebo** [comment]
Did some one find a solution?
