### ISSUE TITLE
Allow build without es6 promise polyfill

### ISSUE THREAD

**Issue by bitinn** [axios/axios#11]
Great stuff! This seem to be the only lib I found that actually use native es6 promise with proper responseType for xhr2.

One suggestion: we actually manage polyfills separately, would be great to have a build without polyfill bundled to save some bytes.

**Comment by wmadden** [comment]
@mzabriskie this still causes problems in our project which imports axios indirectly, i.e. we import another library which imports axios. In our case we're building our project using webpack which is eventually importing axios, and naturally we haven't set up the `es6-promise` external you have in your config.

A better approach might be to check if a native Promise implementation exists at runtime, because `es6-promise`'s polyfill method will just override anything that already exists in the global namespace.

**Comment by wmadden** [comment]
E.g.
```javascript
var es6Promise = require('es6-promise');
if (!global.Promise) {
  es6Promise.polyfill();
}
```

Although I'd question whether it's valuable for axios to be supplying the polyfill at all. It seems like it's useful _exclusively_ for when the library's loaded in isolation - which won't happen in any more complex project with its own build system.

In that case it might be better to include a bootstrapping file only for your `dist` webpack entry, and do the polyfilling there.

Anyone that imports axios from source can be reasonably expected to have polyfilled their environment to include a Promise implementation.

**Comment by mzabriskie** [comment]
@wmadden the next release will remove the `es6-promise` dependency all together. This will require you to either have an environment that natively offers `Promise`, or polyfill it yourself. Will that work for your use case?

**Comment by wmadden** [comment]
Great, thanks very much @mzabriskie!

**Comment by gbrassey** [comment]
For webpack users looking for a way to polyfill Promises. Expose loader does the job nicely without requiring a boostrapped entry: `'expose?Promise!bluebird'`

```
var CommonsChunkPlugin = require('webpack/lib/optimize/CommonsChunkPlugin');

module.exports = {
  entry: {
    'appBundle': './appEntry.js',
    vendors: [
      'expose?Promise!bluebird',
      'axios',
    ],
  },
  plugins: [
    new CommonsChunkPlugin('vendors', './commonVendors.js'),
  ],
  module: {
    loaders: [
      {
        test: /\.jsx?$/,
        exclude: /(node_modules)/,
        loader: 'babel',
      },
    ],
  },
};
```
