### ISSUE TITLE
VueJS/Axios Fires Click Event Twice...?

### ISSUE THREAD

**Issue by BrianMoreno1994** [axios/axios#1128]
Hi everyone, so I'm having a bit of trouble using Axios with VueJS (I'm using the [Quasar Framework](https://github.com/quasarframework/quasar)). I'm making a very simple e-commerce website. I have a button when the user opens the product page that allows the user to insert that product to the cart.

```
<q-btn
     @click="addToCart()"
>
    Agregar Al Carrito
</q-btn>
```
When the user clicks the button I want to execute the `addToCart()` method:

```
methods: {
  addToCart () {
      axios.post(this.getRootURL + 'app/actions/add_to_cart.php', {
        product_id: this.$route.params.product_id,
        quantity: this.quantity,
        user_id: LocalStorage.get.item('user_id')
      }).then(response => {
        console.log("Product added...")
      }).catch(e => {
        console.log("Error... ")
    }
  }
}
```
However, I'm facing a problem. It's as if the data gets inserted twice. The first row gets a null `user_id` and the second row get the correct `user_id` ([See image](https://ibb.co/kRzCiw)).

I'm sure I'm doing something wrong with VueJS or Axios because when using Postman and sending a request directly to the file, the data only gets inserted once correctly. 

Can anyone help? Why Is this happening? :/

**Comment by Nudelsieb** [comment]
Hi @BrianMoreno1994 , this is not axios' fault. I believe, when the component updates (because you executed a method) it reads in the event-handlers/methods again. In your case it does fire again because of `addToCart()`. You have to use `addToCart`. Please resort to the VueJS [docs](https://vuejs.org/v2/guide/events.html). You must never use `()` when you link a method to a directive, unless you explicitely wish the function to execute during evaluation/linking.

**Comment by mandeepsinghgill** [comment]
@pixelbucket-dev what if we send arguments to method ? because in my case i have arguments and it sends double request.
