### ISSUE TITLE
Axios not returning response for POST on 500 error

### ISSUE THREAD

**Issue by themre** [axios/axios#1143]
I setup a basic demo, where I create a POST request and server returns 500 error. With postman I get response, but axios doesn't return response.
https://jsfiddle.net/8r3dh6hw/61/

Response from Postman: `500 Internal Server Error`

**Comment by clusteratlas** [comment]
```
}).catch(error => {
  console.log(error.message);
})
```
results into:

```
Network Error
```

---

From https://github.com/axios/axios/blob/26b06391f831ef98606ec0ed406d2be1742e9850/lib/adapters/xhr.js#L86-L88

```
    // Handle low level network errors
    request.onerror = function handleError() {
      // Real errors are hidden from us by the browser
      // onerror should only fire if it's a network error
      reject(createError('Network Error', config, null, request));

      // Clean up request
      request = null;
    };
```

**Comment by guarani** [comment]
For me, what worked was to implement `validateStatus` and return `true` for the status codes I wanted to handle in the `then` callback.

```
    axios({
      method: 'post',
      url: '/sessions',
      data: {
        username: this.state.username,
        password: this.state.password,
      },
      validateStatus: (status) => {
        return true; // I'm always returning true, you may want to do it depending on the status received
      },
    }).catch(error => {

    }).then(response => {
        // this is now called!
    });
```

**Comment by prog-24** [comment]
Check that you response is giving the correct headers. I had the same problem and it seemed that my API was not sending all the correct error headers so the response was been read as a network error instead of an actual http error which is different.

**Comment by raygesualdo** [comment]
@themre In your jsfiddle, if you look in the browser dev tools, you'll notice that the call to `httpstat.us/500` errors during the `OPTIONS` pre-flight request (an automated network call in modern browsers when using CORS). When making a cross-domain request, if the server isn't correctly configured for CORS, axios returns an error without `error.response` populated. This is because the XHR request fails at the browser level (during the `OPTIONS` call), which is technically a network error. For network errors, axios does not provide a response because one is not provided by the browser. If one debugs the network error returned to axios from an invalid `OPTIONS` call, one will notice that there is no way to know the status.

**Comment by themre** [comment]
@raygesualdo thank you for this detailed explanation! closing the issue.

**Comment by boxfish-ty** [comment]
This is because the XHR request fails at the browser level (during the OPTIONS call), which is technically a network error. For network errors, axios does not provide a response because one is not provided by the browser.
----------------------------------------
Sometimes, we will intercept the request and return a response with a custom field，it will trigger the function request.onerror, but, it can not return the response.
How can i do to get the custom response.

**Comment by amirsefati** [comment]
I spend 12 hours for know Error 500 about my Controller , no Axios 
care about the back-end , Axios is OK

**Comment by orjiss** [comment]
i have the same error how did u fik it please  ?

**Comment by amirsefati** [comment]
send me your code .
my problem was about bad response from controller

**Comment by vidorifaldy** [comment]
(set for global)

                                            in the main.js

import axios from 'axios'

var instance = axios.create({

validateStatus: function (status) {
    return status < 600; #you can change this with another value
}
});

                                               or

Axios.defaults.validateStatus = () => {

    return true;
};

                                                or
(set fot particular)

axios.post(
   'https://httpstat.us/500',
    {dummy: "text"}, 
    {
    validateStatus: function (status) {
    return status < 600; // Reject only if the status code is greater than or equal to 500
    }}
).then(
        (res) => {    	
    	setTimeout(() => {
    	        this.setState({data: res.data})
                }, 
                2000)
}).catch(e => {
    	console.log(e.response)
    })

**Comment by MohAbdelhamed** [comment]
The below **Worked** with me:
const deptsURL = "http://localhost:8099/ords/hr/hrm/depts";
var vAttributes = {};
            vAttributes = {
              departmentid: model.attributes[model.idAttribute]
              , departmentname: $("#newDepartName").val()
              , managerid: 100
              , locationid: 1700
            };
const ops = {
              method: 'POST',
              headers: { 'content-type': 'application/json' },
              data:  JSON.stringify(vAttributes) ,
              url: deptsURL
            };
axios( ops).then((res) => {
              console.log("post response: " + res);
            }).catch(function (error) {
              console.log("post error: " + error);
            });
