### ISSUE TITLE
Request method changed on redirect

### ISSUE THREAD

**Issue by alcalbg** [axios/axios#1158]
Hi,

I'm using axios v0.17.0 with HEAD method like this:

`axios.head('http://example.com'); `

(let's suppose http://example.com is set to redirect 301 to http://www.example.com)

For some reason Request method will change on the first redirect to GET instead of keeping HEAD all the way down. This will read in logs like this:

```
example.com:80 10.0.0.1 - - "HEAD / HTTP/1.1" 301 237 "-" "axios/0.17.0"
example.com:80 10.0.0.1 - - "GET / HTTP/1.1" 200 246 "-" "axios/0.17.0"
```

instead of this:

```
example.com:80 10.0.0.1 - - "HEAD / HTTP/1.1" 301 237 "-" "axios/0.17.0"
example.com:80 10.0.0.1 - - "HEAD / HTTP/1.1" 200 246 "-" "axios/0.17.0"
```

When I do the test in Firefox it keeps original request method (HEAD) all the way down.

Any idea why is this?

Thanks,
Milos

**Comment by alcalbg** [comment]
Ok, apparently this is an issue in follow-redirects package included in the axios.

**Comment by alcalbg** [comment]
It turns out that  olalonde/follow-redirects package is following RFC specifications which says that  [Request method is case-sensitive](https://tools.ietf.org/html/rfc7230#section-3.1.1) as pointed out by @RubenVerborg [here](https://github.com/olalonde/follow-redirects/pull/73#issuecomment-341865982) but axios is passing lowecase verb `head` causing the wrong redirect behavior.

**Comment by krmcbride** [comment]
Just thought I would chronicle how I arrived at this issue, which ultimately solved the problem I was seeing:

It started with a `uncaughtException ` node crash caused by `Error: "toString()" failed` while using axios to send a `HEAD` to inspect headers of a supposed PDF (let's say `http://example.com/file.pdf`).  This seemed pretty weird, being a `HEAD` and all.  It turns out that V8 6.1 and below (node 8 and below) has a 256MB string size limit (I believe its been bumped to 1GB in 6.2) and this `HEAD` was attempting to build a 350MB string.  This was due to the https redirect converting the `HEAD` to a `GET` because of the lower/uppercase mismatch.

So that's a `HEAD` that downloaded a 350MB PDF and crashed node. I thought that was pretty cool  😆 

For now I'm using a request interceptor to uppercase the method, which plays nicely with `follow-redirects` and now my `HEAD` stays a `HEAD` and doesn't explode.

**Comment by RikkiGibson** [comment]
I'm experiencing this issue as well. Is anyone working on this? Would a PR that does something like uppercase the HTTP method before passing it to follow-redirects be accepted?

**Comment by aPoCoMiLogin** [comment]
If you change method to uppercase here: https://github.com/axios/axios/blob/master/lib/adapters/http.js#L84 it will still broken, since it will not follow redirect with body or query string.

xhr adapter already got uppercase method: https://github.com/axios/axios/blob/master/lib/adapters/xhr.js#L45

**Comment by RikkiGibson** [comment]
@Khaledgarbaya @axe312ger @emilyemorehouse  This is still a problem requiring a [fairly strange workaround](https://github.com/Azure/ms-rest-js/blob/bfeb1adfc9c7aed940e26f5ebfdeb94d8ae51010/lib/axiosHttpClient.ts#L16) that is actually now broken with the new type definitions.

Would be very happy to open the PR to just uppercase the HTTP method before passing it off to follow-redirects. Just wanted to check again: is that something you guys would accept? :)

**Comment by axe312ger** [comment]
If your PR has a test case for this I am happy to review it :)
