### ISSUE TITLE
Typescript problem: Cannot invoke an expression whose type lacks a call signature. Type 'AxiosInstance' has no compatible call signatures.

### ISSUE THREAD

**Issue by tonoslav** [axios/axios#1172]
### Summary

Keep getting this error even when I use it correctly (at least I think I do)

![image](https://user-images.githubusercontent.com/3399021/32496664-51dcd6f6-c3ca-11e7-8766-651aa3f71dc7.png)

![image](https://user-images.githubusercontent.com/3399021/32496689-5f3b55e8-c3ca-11e7-8c05-906afb030565.png)

### Context

- axios version: *v0.17.0*
- Environment: *node v8.6.0, tslint v8.6.0, VSCode, 1.18.0 - insider, windows 10*

**Comment by tonoslav** [comment]
**fixed** added `.request`

![image](https://user-images.githubusercontent.com/3399021/32504642-a29c7914-c3e0-11e7-95b0-d30086adde60.png)

**Comment by nickuraltsev** [comment]
Yeah, you cannot use an axios instance as a function.

**Comment by hhamilto** [comment]
Not to dig up an old thread, but I did just find this issue by searching: How come the axios docs seem to indicate otherwise?
![Screen Shot 2020-02-12 at 6 22 24 PM](https://user-images.githubusercontent.com/2374444/74386709-a7a8ae80-4dc4-11ea-944c-083396b51c0f.png)

Seems like a bug in the type definitions to me?
