### ISSUE TITLE
transformResponse runs, even if error code is received

### ISSUE THREAD

**Issue by lpender** [axios/axios#1176]
**Steps To Reproduce**

1. Make an axios request to an endpoint that will return an error code (i.e. `404` or `500`.

**Expected Result**

`transformResponse` should not run

**Actual Result**

`transformResponse` runs, attempting to transform a response that is, i.e. 

- empty
- an HTML description of the 404
- etc

the actual error code is not allowed to bubble up to the `catch` listener

 instead we generally get some sort of syntax error (without copious defensive programming techniques)

**Comment by robcresswell** [comment]
I've got the same issue. Is there no way to discern whether the request was successful? At the moment I'm just programming around it, but it's not really ideal.

**Comment by HelloQingGuo** [comment]
Can I ask why you guys use transformResponse ? I was thinking to put the data transformation logic in the transformResponse, but not sure if it is a right place to do so, espcially seeing this issue ! 
Thanks a lot for discovering this issue !

**Comment by ventralnet** [comment]
In my case I need to use transformResponse to convert a string representation of json to actual json.  The api call is to a third party so I can't correct the response coming from the API

**Comment by Tinoooo** [comment]
Any news on this? The workarounds for this error tend to become pretty messy :(

**Comment by ghbakhtiari** [comment]
Any updates on this?

**Comment by calumjames** [comment]
> Can I ask why you guys use transformResponse ? I was thinking to put the data transformation logic in the transformResponse, but not sure if it is a right place to do so, espcially seeing this issue !
`transformResponse` is a lovely design pattern for transforming the response in the way the client requires it if the service doesn't quite do that, or if a specific client needs to do something different with response data compared to another client. Or if we just want the response as a JavaScript object rather than a string. It's a more pleasant pattern than using interceptors or dealing with each response in a different way.

To keep our code clean and to negate unnecessary and harder-to-maintain defensive programming, it would be great if we can define different transforms for success responses compared to error responses. Perhaps `transformResponse` could continue to handle both (to ensure backward compatibility) but `transformSuccessResponse` and `transformErrorResponse` could be added to help us with this?

**Comment by chinesedfan** [comment]
No intentions to change this "traditional" behavior. But glad to accept a pull request to mention it in our document.
