### ISSUE TITLE
Error 413 does not contain status code

### ISSUE THREAD

**Issue by robbiemu** [axios/axios#1187]
#### Summary

In the follow code snippet,
```js
axios.post('/api/files/new', formData, config)
    .then(response => this.fileUploaded(response.data, name, size))
    .catch(e => {
        console.log('error uploading file:')
        console.warn(e.response)
    })
```
if the api rejects with 413 ("file too large"), e.response is undefined. Multiple reasons can lead to a nul response, and we need to be able to distinguish. In this case, at the reject phase, that status is lost.

At the same time, servers should not have to attach response bodies for all forms of malformed requests. 

#### Context

- axios version: 0.15.3
- Environment: vueJS/node custom project

**Comment by janober** [comment]
Sounds like it is related to my issue #1168

**Comment by teodors** [comment]
I have been pulling my hairs out with this issue for a couple of days now, not being able to detect error status code.

**Comment by janober** [comment]
I switched in the end to "request-promise", can just advise you to do the same. There getting the actual error is very simple.

**Comment by mindjuice** [comment]
I've got the same issue.  The response contains an error message I want to show to the user, but it's not available.

Will this be fixed?

**Comment by raygesualdo** [comment]
Hey all, I took a few minutes to troubleshoot this issue. Here are some things I found:

1. I created an example of @robbiemu's code that works. The codesandbox can be viewed here: https://codesandbox.io/s/80jv7k528. Note that while the example makes a cross-domain request, the server is correctly configured for CORS. Let me know if that is helpful.
1. I found that, when making a cross-domain request, if the server isn't correctly configured for CORS, axios returns an error without `error.response` populated. This is because the XHR request fails at the browser level (during the `OPTIONS` call), which is technically a network error. For network errors, axios does not provide a response because one is not provided by the browser. If one debugs the network error returned to axios from an invalid `OPTIONS` call, one will notice that there is no way to know the status.

**Comment by ben-eb** [comment]
I was able to work around this issue by testing that the error message includes `413` and displaying a more user friendly error. It's not elegant though! 😃 

```js
axios.post('/api/files/new', formData, config)
  .catch(err => {
    if (err.message && err.message.includes('413')) {
      console.log('The file you tried to upload is too large.')
    }
  });
```

**Comment by chinesedfan** [comment]
I think the reason is `validateStatus`. See [my notes](https://github.com/chinesedfan/You-Dont-Know-Axios/blob/master/README.md#response-schema). And feel free to remind me if it is not solved.
