### ISSUE TITLE
Refused to set 'user-agent'

### ISSUE THREAD

**Issue by aaroncraig10e** [axios/axios#1231]
This isn't technically an issue with this library, however it should be noted that neither Chrome nor Safari currently allow setting the "user-agent" header, both throw `Refused to set unsafe header "user-agent"` errors.

It might be responsible to detect whether or not the browser allows for setting this header to avoid spurious errors getting thrown.

I'm happy to open a PR if there's a chance it will go in. We'd certainly like that, as currently we're getting this error on every page load.

**Comment by brpaz** [comment]
Because of this I am unable to use Travis CI API in a nodeJS / electron app because it requires you to send an User Agent. Is there a workaround for this?

**Comment by sueblue** [comment]
I meet this problem also.  it's upsetting .   I require to set the http headers by myself ,but axios thorw  refuse msg .    Is there a way to solve this? or I maybe not use it

**Comment by steelbrain** [comment]
I've opened https://github.com/axios/axios/pull/1715 to fix this

**Comment by aguynamedben** [comment]
This is super annoying. Everything works, but my console is flooded with this warning. I also tried setting my adapter to the http adapter but that is not working.

Any other ideas? Is this just considered a bug?

**Comment by jverhoelen** [comment]
In Chrome for example the annoying issue of logging the errors `Refused to set unsafe header "user-agent"` and `Refused to set unsafe header "Accept-Encoding"` still persists.
Both headers are present in the list of automatically set headers but `xhr.js` adapter is not filtering them out.

I think the block in `xhr.js` handling this should look like this:

```
// Add headers to the request
if ('setRequestHeader' in request) {
  utils.forEach(requestHeaders, function setRequestHeader(val, key) {
    if (typeof requestData === 'undefined' && key.toLowerCase() === 'content-type') {
      // Remove Content-Type if data is undefined
      delete requestHeaders[key];
    } else if (key.toLowerCase() === 'user-agent' || key.toLowerCase() === 'accept-encoding') {
        // don't do anything
    } else {
      // Otherwise add header to the request
        console.log('axios/lib/adapters/xhr')
      request.setRequestHeader(key, val);
    }
  });
}
```

Is there any reason against solving it like this which should be considered?

**Comment by aguynamedben** [comment]
@jasonsaayman Is there a recommended workaround so Chrome isn't logging this annoying message?

**Comment by jasonsaayman** [comment]
@aguynamedben can you give me an example for me to reproduce?

**Comment by aguynamedben** [comment]
@jasonsaayman In my app we use Axios directly, but we don't try to set the user-agent header, so we're not getting this error because of our own actions.

We are, however, using [@slack/web-api](https://www.npmjs.com/package/@slack/web-api), which depends on Axios, and it must be setting the user-agent header.

![2021-05-28_17-31-33 (1)](https://user-images.githubusercontent.com/107841/120052609-f179d000-bfda-11eb-921c-e3b21da1e53e.gif)

I think the issue has something to do with Electron and whether the xhr or http adapter is chosen. It seems like many user have run into problems with the xhr adapter being chosen in Electron environment.
* [Potentially problematic line for Electron users](https://github.com/axios/axios/blob/master/package.json#L69)
* Historic issues
  * https://github.com/axios/axios/issues/2232
* [One workaround](https://github.com/axios/axios/issues/552#issuecomment-604468438) (requires forking Axios)
* [Repro case](https://github.com/axios/axios/issues/2731#issuecomment-613937080) - xhrAdapter automatically chosen for Node environment when user would rather have http adapter

I'm not well-versed on why/how adapters are chosen with Axios. I'm not sure how to tweak @slack/web-api's Axios usage. I guess I could hack up my webpack to alias the xhr.js path within @slack/web-api to point to the https adapter?

Happy to help more. Maybe "global" adapter selection (i.e. including Axios buried within a dependency) could be managed by setting a variable like Axios.globalAdapter. Then app developer could indicate to any dependency using Axios how it should work. I'm not sure if that makes any sense.

**Comment by aguynamedben** [comment]
Also, if you're not familiar with Electron, [Electron Fiddle](https://www.electronjs.org/fiddle) can be a helpful tool to play with. I tried a repro case with direct Axios usage, and even though it used xhrAdapater (fine with me?) I didn't see this error, presumably because my repro case didn't try to set the User-Agent header.

**Comment by MarkPieszak** [comment]
> In Chrome for example the annoying issue of logging the errors `Refused to set unsafe header "user-agent"` and `Refused to set unsafe header "Accept-Encoding"` still persists.
> Both headers are present in the list of automatically set headers but `xhr.js` adapter is not filtering them out.
> 
> I think the block in `xhr.js` handling this should look like this:
> 
> ```
> // Add headers to the request
> if ('setRequestHeader' in request) {
>   utils.forEach(requestHeaders, function setRequestHeader(val, key) {
>     if (typeof requestData === 'undefined' && key.toLowerCase() === 'content-type') {
>       // Remove Content-Type if data is undefined
>       delete requestHeaders[key];
>     } else if (key.toLowerCase() === 'user-agent' || key.toLowerCase() === 'accept-encoding') {
>         // don't do anything
>     } else {
>       // Otherwise add header to the request
>         console.log('axios/lib/adapters/xhr')
>       request.setRequestHeader(key, val);
>     }
>   });
> }
> ```
> 
> Is there any reason against solving it like this which should be considered?

I have ran into this exact issue as well (not using Axios directly, but something else in an Application is). A fix like above does infact make it go away, but that's only temporarily + locally (aside from writing scripts to update this after "install" :D)

If it's as simple as getting a PR in to fix this, I'd be more than happy to help!
(Unless there's a good reason we can't do this?)

**Comment by jasonsaayman** [comment]
@MarkPieszak please can you submit a PR, and update me?

**Comment by derammo** [comment]
@jasonsaayman I don't think this is fixed in any of the referencing PRs?

**Comment by cimd** [comment]
Hi,
Why is this marked as closed as the problem still exists?
