### ISSUE TITLE
nested array in patch not working 

### ISSUE THREAD

**Issue by sirb0rab0g1** [axios/axios#1300]
let data = {
      head: {
        name: 'Arnel Tambassss'
      },
      tracking_number: '2017'
}
return new Promise((resolve, reject) => {
      Http.patch(url, data)
//success

it only update the tracking number but not the head object in respose

**Comment by Axnyff** [comment]
Hello,
Did you check the network to verify whether it could be a problem linked to the server?
Otherwise, could you please provide a reproduction of your bug?
In your example I guess that Http is axios but it's not sure, could you clarify?

**Comment by emilyemorehouse** [comment]
Hi @sirb0rab0g1,

If you can submit a short snippet that shows a reproducible bug, I'm happy to help. Since this issue hasn't received a response and this doesn't look like an Axios bug based on the info we have, I'm closing this issue.

If you need further assistance debugging your code, please post on [Stack Overflow](http://stackoverflow.com/questions/ask?tags=axios), [Gitter](https://gitter.im/mzabriskie/axios), or comment again on this issue. 

Thanks!
