### ISSUE TITLE
Passing an XML Payload for a Put Request [question]

### ISSUE THREAD

**Issue by Artiiz-ZA** [axios/axios#1311]
#### Summary

I am rather new to making use of Axios, and I seem to have hit a block, I am probably just not fully understanding the capabilites, but after searching through the documentation I can still not figure it out.

I am trying to pass XML code as the payload of an API Put request. I am basically wondering if this is either not possible with Axios, or if it is; please could someone assist me in a description of how I would be able to make this happen?

Thank you very much for your assistance!

#### Context

- axios version: *e.g.: v0.16.0*
- Environment: *e.g.: node v6.9.4, chrome 54, windows 10*

**Comment by Axnyff** [comment]
Hello,
what did you try?
I think something like

    var config = {
       headers: {'Content-Type': 'text/xml'}
    };

    axios.put(myUrl, xmlString, config); 

should work

**Comment by emilyemorehouse** [comment]
Hi @Artiiz-ZA,

Since this issue hasn't received a response and this doesn't look like an Axios bug based on the info we have, I'm closing this issue.

If you need further assistance debugging your code, please post on [Stack Overflow](http://stackoverflow.com/questions/ask?tags=axios), [Gitter](https://gitter.im/mzabriskie/axios), or comment again on this issue. 

Thanks!
