### ISSUE TITLE
how to read response headers from HEAD request

### ISSUE THREAD

**Issue by refucktor** [axios/axios#1324]
#### Summary
Doing a HEAD request I got a successfully 200 response and I can see all data related to the request and response <b>in the BROWSER</b>

#### Context
The HEAD request is looking like the following:

```javascript
axios.head("samplePath/sampleFile", {params: {fileName}})
    .then(response => console.info("response:", response)) //Log is giving an undefined response
    .catch(handleErrorResponse);
```

<b>I want to read Headers from the response, specifically *Content-Length*</b> and in a HEAD request the response is undefined after the promise is resolved.
Any suggestion?

- axios version: *e.g.: v0.17.1*
- Environment: *e.g.: node v8.9.3, chrome 63, Debian*

**Comment by Axnyff** [comment]
Hello,
could you provide some more information regarding the bug?

If I do, in my browser (chrome)

`
axios.head("/", { params: {"foo": "bar"}})
    .then(response => console.info("headers:", response.headers))
`

It correctly log the headers. Are you sure your head request does not return an empty response?

**Comment by emilyemorehouse** [comment]
Hi @refucktor,

Since this issue hasn't received a response and this doesn't look like an Axios bug based on the info we have, I'm closing this issue.

If you need further assistance debugging your code, please post on [Stack Overflow](http://stackoverflow.com/questions/ask?tags=axios), [Gitter](https://gitter.im/mzabriskie/axios), or comment again on this issue. 

Thanks!

**Comment by unguul** [comment]
For people getting here after searching "axios access response headers": 

remember js has array access so you can do: `response.headers['my-header-name']`;

Here's a pull request making this clear in the docs: https://github.com/axios/axios/pull/1901
