### ISSUE TITLE
the response interceptor cannot intercept the error message returned

### ISSUE THREAD

**Issue by Keecat** [axios/axios#1338]
i have created an axios instance, binding the response intercepetor for it, but response interceptor can't get error message, err.response is null. i want get error status code, i need your help.

axios version: 0.17.1

![image](https://user-images.githubusercontent.com/20496148/35839818-9141c7b6-0b2d-11e8-8df0-278c93776b87.png)

**Comment by Khaledgarbaya** [comment]
Can you share a code snippet ?

**Comment by emilyemorehouse** [comment]
@Keecat here's a working example:

<img width="765" alt="screen shot 2018-02-18 at 1 04 23 pm" src="https://user-images.githubusercontent.com/4264897/36356241-45f3eed2-14ac-11e8-9539-27dfdac85169.png">

And copy/paste friendly:
```
var axios = require("axios")

function onFullfilled(response) {
    console.log('onFullfilled');
    return response;
}
function onRejected(err) {
    console.log(`onRejected: ${err}`);
    console.log(`status: ${err.response.status}`);
    return Promise.reject(err);
}

var axiosInstance = axios.create();
axiosInstance.interceptors.response.use(onFullfilled, onRejected)

// call endpoint that purposefully does not exist
axiosInstance.get('https://jsonplaceholder.typicode.com/post')
.then(function(resp) {console.log(resp);})
.catch(function(err) {console.log(err.response.status);})
```

Since this doesn't look like an Axios bug, I'm closing this issue.

If you need further assistance debugging your code, please post on [Stack Overflow](http://stackoverflow.com/questions/ask?tags=axios), [Gitter](https://gitter.im/mzabriskie/axios), or comment again on this issue and I'll try to help.

**Comment by Strateus** [comment]
Any hints where this bug may come from? I see similar behavior and it might be related: https://github.com/axios/axios/issues/1827#issuecomment-588225077
