### ISSUE TITLE
how to override axios.defaults.headers.common for crossdomain requests

### ISSUE THREAD

**Issue by vesper8** [axios/axios#1346]
In my app which uses X-CSRF-TOKEN in all api requests to MY server, I wanted to use axios to also perform an api GET request to an external server (giphy in this case)

I kept getting this error 
```
Request header field X-CSRF-TOKEN is not allowed by Access-Control-Allow-Headers in preflight response.
```

Basically my understanding of this error is that Giphy's server does NOT want this header to be included

This header is included by default in my axios configuration however. I tried many things to get it to NOT send this header, but nothing worked until I came up with this rather ugly hack:

```
var self = this;
var axiosCrossDomain = axios;
delete axiosCrossDomain.defaults.headers.common["X-CSRF-TOKEN"];
axiosCrossDomain(apiEndPoint, {
	method: "GET",
	params: {
		api_key: publicKey,
		q: self.query.split(" ").join("+"),
		limit: 50
	}
})
	.then(function(response) {
		self.results = response.data.data;
		self.current_gif = false;
	})
	.catch(function(error) {
		console.log(error);
	});
```

This works.. it was not required for me to make a copy of axios like I did but since my app is a SPA I wanted to make sure that I was not removing the X-CSRF-TOKEN from all instances of axios

But surely there must be another, better way to do this?

Anyone know?

Thanks

**Comment by emilyemorehouse** [comment]
Just to make sure I understand, at some point you're adding the X-CSRF-TOKEN header to your global configuration, correct? That header shouldn't be included as one of the default headers out of the box.

Otherwise, I would suggest using multiple instances in order to separate your API endpoints, like this:
```
var instance = axios.create({
    headers: {
        common: {
            'X-CSRF-TOKEN': 'totallyfaketoken',
        },
    },
});
```

This supports the full configuration as well, in case there's anything else you want to include. If you are using any other forms of configuration (global, etc.), I recommend checkout out the docs on [config precedence](https://github.com/axios/axios#config-order-of-precedence).

**Comment by emilyemorehouse** [comment]
@vesper8 did this solve your issue? 

In an effort to get our GitHub issues under control, I'm going to close this out. If you still need assistance, feel free to comment again and I'll see if I can help!

**Comment by agm1984** [comment]
Here is my solution. This allows me to rely on the default Laravel implementation for default headers in `bootstrap.js` and then every time I make an external API request, I use this:

``` javascript
// temporarily wipe 'X-CSRF-TOKEN' header for Google CORS
const instance = axios.create();
instance.defaults.headers.common = {};
instance.defaults.headers.common.accept = 'application/json';

const { data } = await instance.get(generatedUrl);
```

`generatedUrl` is of course proprietary to your app, like https://www.com/api

The absolute trick is that, in my case, Google's API requires that the `'X-CSRF-TOKEN'` header be absent, so you can't simply set it to `undefined`. So after dealing with this problem off and on for several weeks, my above solution is what I have ended up with.

The trick is to don't even go down a path of trying to temporarily mutate `axios.defaults.headers` because you will encounter horrific async issues if you make an external API call while a page loads and a user on your site submits a form that makes an internal API call.

If the `axios.defaults` were mutated during that time, you will of course experience the full wrath of shared mutable state. Fire up a separate axios instance, and make your external API calls using that.

Relevant docs are likely here if you want to investigate other trinkets: https://github.com/axios/axios

``` javascript
// function signature
const config = {};
const instance = axios.create(config)
```

NOTE: You cannot assign the headers in the config object. You must mutate them afterwards with:
``` javascript
instance.defaults.headers.common = {};
instance.defaults.headers.common.accept = 'application/json';
```

**Comment by wmcmurray** [comment]
The best approach I've found (for my case) was to **not use** default headers at all, :man_shrugging: 
but instead a feature called [Interceptors](https://github.com/axios/axios#interceptors) :sparkles: 

exemple :

```js
axios.interceptors.request.use(function (config) {
    if(typeof config.headers['X-CSRF-TOKEN'] === 'undefined') {
        // add X-CSRF-TOKEN header only if url begins with "/api/" or is on same domain
        if(config.url.substring(0,5) === '/api/' || config.url.indexOf(window.location.hostname) !== -1) {
            config.headers['X-CSRF-TOKEN'] = 'tok,tok,tok,ken est là?';
        }
    }

    return config;
});
```
This function will be called before sending every requests.

_PS : This approach is a tiny bit less optimized (because this code gets evaluated on every requests), but it strips away the annoyance of dealing with multiple instances of axios in an app where axios is used in hundreds of places !_

**Comment by trevormccasland** [comment]
https://github.com/ctimmerm/axios-mock-adapter/blob/0901797ecbd324cae2e1e0ddaa04ae16ab1670e6/src/utils.js#L11 even if headers is `{}` this will still create and error, can we at least support not creating an error if the _client headers_ aren't set in the headers object?

**Comment by choyan** [comment]
After logging in I am setting my interceptors default header to the access token
  
`API.defaults.headers.Authorization = 'Bearer ' + res.data.access_token;`

All of my requests are now having the access token properly.

**Comment by surekhag** [comment]
How to update this token value on session expiry ? i am using function to update header config and now token is in closure so even when i remove old token from local storage, its still there in global object. and requests still refer to old token

**Comment by Kevin-cengage** [comment]
> How to update this token value on session expiry ? i am using function to update header config and now token is in closure so even when i remove old token from local storage, its still there in global object. and requests still refer to old token

Same issue here. I can not change default one
