### ISSUE TITLE
axios vs fetch - no-cors mode...

### ISSUE THREAD

**Issue by JohnRSim** [axios/axios#1358]
Axios - fails
```javascript
	axios('https://pagead2.googlesyndication.com/pagead/js/adsbygoogle.js', {
		method: 'HEAD',
		mode: 'no-cors',
		headers: {
			'Access-Control-Allow-Origin': '*',
			Accept: 'application/json',
			'Content-Type': 'application/json',
		},
		withCredentials: true,
		credentials: 'same-origin',
		crossdomain: true,
	}).then((response) => {
		console.log(response);
	}).catch((e) => {
		console.log(e);
	});
```

Fetch - works
```javascript
	const testURL = 'https://pagead2.googlesyndication.com/pagead/js/adsbygoogle.js';
	const myInit = {
		method: 'HEAD',
		mode: 'no-cors',
	};

	const myRequest = new Request(testURL, myInit);

	fetch(myRequest).then(function(response) {
		return response;
	}).then(function(response) {
		console.log(response);
	}).catch(function(e){
		console.log(e);
	});
```

#### Summary
in Axios I get the following cors error but if I replace with standard fetch it works fine.
I've tried a few different configurations with axios and must be missing something?

Error:
```
Failed to load https://pagead2.googlesyndication.com/pagead/js/adsbygoogle.js: Response to preflight request doesn't pass access control check: No 'Access-Control-Allow-Origin' header is present on the requested resource. Origin 'http://localhost:8080' is therefore not allowed access.
```

#### Context

- axios version: * axios v0.17.1 
- Environment: * Chrome 63.0.3239.132 (Official Build) (64-bit)

**Comment by JohnRSim** [comment]
The head response is 200 I'm unsure why its tracking as an error.

![image](https://user-images.githubusercontent.com/364208/36077774-ca04ebe0-0f66-11e8-87a7-c3e560100976.png)

**Comment by emilyemorehouse** [comment]
Hi @JohnRSim,

It's important to note is that `mode`, `credentials`, and `crossdomain` aren't supported for configuring Axios. The reason why your example works when using `fetch` is because those options are part of the Request API (docs for `mode` are [here](https://developer.mozilla.org/en-US/docs/Web/API/Request/mode)).

Probably TMI, but Axios uses a [XMLHttpRequest](https://developer.mozilla.org/en-US/docs/Web/API/XMLHttpRequest) under the hood, not [Request](https://developer.mozilla.org/en-US/docs/Web/API/Request).

I believe that your request using Axios fails because CORS is still being enforced, though I'm not sure why you're getting a Network Error. I'll try to duplicate this locally as well.

**Comment by JohnRSim** [comment]
@emilyemorehouse ahh 👍 thanks for letting me know.
I was looking through other issues and saw a number of users using the Request options so I added them to try to get it to work. 

Let me know if you can replicate the issue.
Thanks

**Comment by emilyemorehouse** [comment]
@JohnRSim Unfortunately, I think this boils down to one of the dreaded CORS issues that developers often face. I could duplicate this and I tried a bunch of ways to poke at it to get the preflight request to work, but I couldn't find an opening in the server to let me through. 😞 

Since this isn't really an issue Axios can solve currently (it's possible that fetch could be supported in the future, but we'd lose browser compatibility), I'm going to close this out. Feel free to comment and I'll still respond if I can help any further!

**Comment by tomjdickson** [comment]
I am getting the exact same issue at the moment, was anyone able to overcome the issue?

**Comment by phdog** [comment]
Same here

**Comment by frinkfromthedrink** [comment]
For anyone facing this issue using express.js, I used

```js
var allowCrossDomain = function(req, res, next) {
    res.header('Access-Control-Allow-Origin', "*");
    res.header('Access-Control-Allow-Methods', 'GET,PUT,POST,DELETE');
    res.header('Access-Control-Allow-Headers', 'Content-Type');
    next();
};

app.use(allowCrossDomain);
```

This solved the issue, while still restricting to the methods I needed. Let me know if this helps

**Comment by Ethan0007** [comment]
Hi, Just want to ask what is the exact way to request in axios when in CORS?
I'm getting the same issue when i used axios, but i works in jQuery.

![image](https://user-images.githubusercontent.com/12542052/51535230-70462780-1e7a-11e9-8ede-64c725c8abbf.png)

Thanks

**Comment by b4dnewz** [comment]
so there is no way to make axios bypassing cors errors?

**Comment by chovy** [comment]
I'm also using a proxy to send an http request from the client side an I am getting cors errors in axios. With fetch I can send the request through a cors-proxy server, but I would rather use a proxy server to avoid cors.

**Comment by guoxiangwen** [comment]
@emilyemorehouse  So how to solve this problem as `fetch cors mode` with use axios?

**Comment by Yakimych** [comment]
Hi

> Since this isn't really an issue Axios can solve

Could you elaborate why it's not solvable? My understanding is that CORS should only be an issue when the request is performed from the browser. Currently I am getting this CORS error when making requests with axios from tests (running via jest testrunner).
In my understanding this should not be an issue at all in this case (but correct me if I am wrong :)). Is axios blocking cross-site requests because it is trying to behave like a browser even when run via a test runner? Why would we not allow setting no-cors in this case?

**Comment by Favna** [comment]
@Yakimych It's not the answer you're looking for, but Jest uses JSDom in the background which does in fact "behave like a browser" as you stated.

**Comment by Yakimych** [comment]
@Favna - good to know, thanks! Does this mean that running tests via a different testrunner could solve the problem?

**Comment by Favna** [comment]
@Yakimych that would be a possibility but you should not make the decision lightly. Since we're talking frontend here and you're using Jest I'll assume you're creating a React or Vue app. Jest is undoubtedly the best test framework for React, I can't speak much about Vue. For example if you would use Mocha instead of Jest you'd also have to use Sinon for mocking your functions and still JSDom for component tests, though you could then use something like node-fetch for contract testing but that is arguably a horrible design decision because it means you're testing with a different request handler (Request) than your main code uses (XMLHttpRequest).

The far better solution is to ensure that the backend you're trying to talk to in your test (and your main code for that matter) supports CORS, as it should if it's a backend designed for frontend consumption.

**Comment by Yakimych** [comment]
@Favna good point, we're indeed developing a React app. Hmm, perhaps in our use-case, it would be possible to run unit tests with jest, and only run API-tests with something else. And yes, I fully agree that testing with different request handlers is a bad idea - the main point of having those tests on the frontend for us is to make sure the views are calling the same code as the tests, so that could be an issue.

> The far better solution is to ensure that the backend you're trying to talk to in your test (and your main code for that matter) supports CORS, as it should if it's a backend designed for frontend consumption.

The product I am working on - both frontend and backend is deployed as a single web application, so we really don't have a use case where a frontend application would talk to our API from a different domain. Therefore we really don't want to open up CORS in production just for the sake of being able to run those tests.

In any case - thanks for the clarification!

**Comment by AlaEddineLaouir** [comment]
Anyone with this problem i suggest to add 'proxy':'baseUrlForTheAPI', if we need one API. if you need many APIs checkout http-proxy-middleware : https://www.npmjs.com/package/http-proxy-middleware
