### ISSUE TITLE
how can I get 2 response in same .vue

### ISSUE THREAD

**Issue by ahmetscil** [axios/axios#1373]
hi!
I want 2 get data in same .vue page. 

    created() {
        axios.get(`http://jsonplaceholder.typicode.com/posts/${this.$route.params.id}`)
        .then(response => {
            this.Blog = response.data
        }),
        axios.get(`https://jsonplaceholder.typicode.com/users/` + Blog.userId )
        .then(getUser => {
            this.User = getUser.data
        })
    }

if I write 
axios.get(`https://jsonplaceholder.typicode.com/users/1`)
it's working. But I want "Blog.userId"
axios.get(`https://jsonplaceholder.typicode.com/users/` + Blog.userId )

how can i do that ?

thank u.

**Comment by matsilva** [comment]
This doesn't seem like an issue with the Axios project. Maybe I am wrong here but stack overflow would be a better place to ask this question?

Nevertheless, I suspect `Blog.userId` is throwing an error this you are assigning `this.Blog = response.data` and then trying to reference `Blog.userId` which is undefined as is because Blog is being assigned to `this`. So you you could try `this.Blog.userId` instead.

`axios.get(`https://jsonplaceholder.typicode.com/users/` + this.Blog.userId )`

**Comment by Khaledgarbaya** [comment]
This has nothing to do with axios, please check stack overflow and I am sure users can help you there
