### ISSUE TITLE
i wanna finish in 'interceptors > error'

### ISSUE THREAD

**Issue by haeyon098** [axios/axios#1374]
hi. I'm using `axios`. 
When session timeout, i want to show only alert. i wrote like this.

```javascript
axios.interceptors.response.use(function (response) {
    return response;
}, function (error) {
    if (403 === error.response.status || 401===error.response.status) {
        // alert
        swal({
            title: 'Fail',
            text: 'You logged out.',
            icon: 'error',
            confirmButtonText: 'Confirm',
            buttonsStyling: false
        }).then(function () {
            location.href = '/user/singin'
        });
    } else {
        return Promise.reject(error);
    }
});
```
But, it must return `then` or `catch`. i just want to finish in `function(error) {..}`.
1. i really wanna know how to don't return. 

2. Or, if you know how to do session timeout, let me teach that.

please reply..!

**Comment by emilyemorehouse** [comment]
There's no way to bypass the request handler (`.then` or `.catch`) completely. 

You can still reject in your `if (403 === error.response.status || 401===error.response.status) {` . See this related issue: #1375 

Since this doesn't look like an Axios bug, I'm closing this issue.

If you need further assistance debugging your code, please post on [Stack Overflow](http://stackoverflow.com/questions/ask?tags=axios), [Gitter](https://gitter.im/mzabriskie/axios), or comment again on this issue and I'll try to help!
