### ISSUE TITLE
interceptors ,how to don't return then or catch ?

### ISSUE THREAD

**Issue by hskim1226** [axios/axios#1375]
hi!
I wanna use `interceptors`
[this is my sample project ](http://jsbin.com/wexoworime/1/edit?html,js,console)

i just want to finish when error  response  status is 404 .
But, it must return catch.

If you reply, it help me a lot.

**Comment by emilyemorehouse** [comment]
Why don't you use `return Promise.reject(error);` within `if(error.response.status===404)`?
You don't have to do anything in the `.catch`, but you have to reject the promise in order to stay out of the `.then`.

Since this doesn't look like an Axios bug, I'm closing this issue.

If you need further assistance debugging your code, please post on [Stack Overflow](http://stackoverflow.com/questions/ask?tags=axios), [Gitter](https://gitter.im/mzabriskie/axios), or comment again on this issue and I'll try to help!
