### ISSUE TITLE
__WEBPACK_IMPORTED_MODULE_5_axios___default.a.get(...).than is not a function

### ISSUE THREAD

**Issue by maratmkhitaryan** [axios/axios#1376]
Webpack error :(
```
    axios.get(`https://jsonplaceholder.typicode.com/users`)
    .then(res => {
      const persons = res.data;
      alert(persons)
    })
```

**Comment by emilyemorehouse** [comment]
Hello!

From what I can gather, this looks like an error with your Webpack configuration. Without more information, there's not much we can do to help you.

Since this doesn't look like an Axios bug, I'm closing this issue.

If you need further assistance debugging your code, please post on [Stack Overflow](http://stackoverflow.com/questions/ask?tags=axios), [Gitter](https://gitter.im/mzabriskie/axios), or comment again on this issue and I'll try to help!
