### ISSUE TITLE
Problemm cancelling requests

### ISSUE THREAD

**Issue by bcazu** [axios/axios#1378]
Hi.
I have a problem canceling requests. I'm doing "n" number of requests and I need to cancel all or some of them in specific but only one cancels me.
`function getRequest(){
    for(let value of data){
      axios.get(value.url, { 
          cancelToken: source.token, 
      }).then(function(response){
          console.log(response);
      }).catch(function(thrown) {
           if (axios.isCancel(thrown)) {
               console.log('Request canceled', thrown.message); 
            } else {
              console.log(thrown);  
            }
       }); 
    }
}
function cancelRequest(){
    for(let value of data){
     source.cancel();
   }
}`

**Comment by emilyemorehouse** [comment]
Hello!

There's information in #1361 or #1294 on managing cancel tokens for multiple requests. You'll need a unique token for each request that needs to be canceled, as all requests associated with a token are canceled when `.cancel()` is called on your source.

Since this doesn't look like an Axios bug, I'm closing this issue.

If you need further assistance debugging your code, please post on Stack Overflow, Gitter, or comment again on this issue and I'll try to help.
