### ISSUE TITLE
Interceptors array potentially growing indefinitely

### ISSUE THREAD

**Issue by pendenaor** [axios/axios#1380]
Hi,

While testing my application, i notice that the `handlers` array of axios interceptors only increase, even if i use the `eject` method.

In fact, `eject` only nullify interceptor entry
https://github.com/axios/axios/blob/a105872c1ee2ce3f71ff84a07d9fc27e161a37b0/lib/core/InterceptorManager.js#L32

and `use` always push new handler and return `length - 1`
https://github.com/axios/axios/blob/a105872c1ee2ce3f71ff84a07d9fc27e161a37b0/lib/core/InterceptorManager.js#L22

Is it not dangerous (or expensive) to have this type of behaviors?

Regards

**Comment by Axnyff** [comment]
Hello,
I had a quick look and I don't really know what could be a good alternative (without breaking changes) because the ids are necessary to eject so new interceptors always need to be a new array key, we cannot just filter the array as this will change the ids.

Deleting keys instead of just putting null could help a little but it would just create sparse arrays, I'm not sure this is much better.

Maybe using a plain object to store the interceptors and another array to know in which order call the interceptor could work ( I don't think relying on keys order in object is a good idea, it's only sure to work in ES6 compliant implementation)

**Comment by pendenaor** [comment]
And reusing nulled index instead of returning directly last index in `use`?

**Comment by Axnyff** [comment]
Wouldn't that change the order of execution of interceptors? 
I also think that there's a chance that somebody depends on the fact the the indexes always grow to keep track of the last added interceptor so I don't know if that would be ok

The more I think about it, the more I'd say that using just an object to store the interceptors could actually be a good idea.

**Comment by pendenaor** [comment]
Ok, order is important... maybe, a `Map` with an auto-incremented numeric key?

**Comment by Axnyff** [comment]
Yes, that seems like the best idea. That's kind of what I was suggesting but with a plain JS object to make sure it will be ES5 compatible

**Comment by viktoriiakrause** [comment]
Hi!
Are there any updates on this issue?

**Comment by takirohit** [comment]
@Axnyff Using plain JS object(Map implementation) looks good approach. is there any update/plan to implement it ?

**Comment by pendenaor** [comment]
ES5 complient? See https://github.com/axios/axios/issues/1380#ISSUECOMMENT-372155759 where @Axnyff suggests object + array

**Comment by Axnyff** [comment]
My PR should work with only an id and a count: https://github.com/axios/axios/pull/1410
I had some requested changes but I don't know how to profile for memory though
