### ISSUE TITLE
Axios timeout not working on expo react native over LTE

### ISSUE THREAD

**Issue by spierr** [axios/axios#1403]
Currently I´m using axios in an expo react native app to make a GET request to a server. I've set the timeout for this request to 15000 ms and it works perfectly when I try to make the request over WiFi. The thing is that when I try to do exactly the same request over LTE or 3g the timeout doesn't work and the request takes like 2 minutes to throw a connection error.

Environment:

"axios": "^0.17.1",
"expo": "^22.0.0",
"react": "16.0.0-beta.5",
"react-native": "https://github.com/expo/react-native/archive/sdk-22.0.2.tar.gz",

**Comment by msmaromi** [comment]
same problem

**Comment by baryla** [comment]
The problem doesn't lie on axios' side. It's a problem a lot of developers have been facing with RN or Expo for this matter. I have the exact same issue where the requests are fine if the APP and the API are on the same network but if they're on separate networks, it starts to timeout. I read that setting the packer hostname for RN should fix that issue but for me, it doesn't. This is 100% not an axios issue because if you swap axios for the built in Fetch API, you'll get the same issue.

**Comment by chinesedfan** [comment]
Seems that @baryla has given a good explanation.
