### ISSUE TITLE
Why do we need error handler in request interceptor?

### ISSUE THREAD

**Issue by totalamd** [axios/axios#1556]
```
axios.interceptors.request.use(function (config) {
    // Do something before request is sent
    return config;
}, function (error) {
    // Do something with request error
    return Promise.reject(error);
});
```

What kind of errors should I expect if we have not sent any request yet?

**Comment by zcei** [comment]
Handling errors is always best practice, and as you could always decide in your interceptor to throw (or just have a typo, or something async fails) you need to be able to handle it.

E.g. an interceptor which first talks to your OAuth service to obtain a token to send along in the request headers. Imagine the service being down, you probably want to know about that instead of wondering why all request are returning `401`s

**Comment by totalamd** [comment]
But if we fetch something in `function(config) {}` and it fails its never gets into `function(error) {}` by the `.then(response, reject)` rules, doesn't it?

**Comment by zcei** [comment]
Mhm fair enough 🤔 So for my example you'd need to use two interceptors.
I always thought Axios would handle this accordingly internal, so that it actually does `.then().catch()`, but I just looked it up and it's exactly as you stated. So your interceptor is actually handling the errors of the previous interceptors, which doesn't feel right / modular to me, as they need to have knowledge about the potentially thrown errors.

**Comment by littlee** [comment]
I don't know when will the **request interceptors** error handle callback will be called, either.

when the user is offline or the request is timeout, only the **response interceptors** error handle callback is callled.

**Comment by chinesedfan** [comment]
> So your interceptor is actually handling the errors of the previous interceptors, which doesn't feel right / modular to me, as they need to have knowledge about the potentially thrown errors.

Agreed with @zcei. I have to admit that axios is simple and sometimes not very convenient.
