### ISSUE TITLE
Axios post call issue

### ISSUE THREAD

**Issue by zohaib85** [axios/axios#1588]
Hi Guys,
I have backend using java spring jwt token. I can't do post request using axios it fails.
Any recommendations?
 axios.request({
                    url: "/auth/login",
                    method: "post",
                    baseURL: "http://localhost:8080/",
                    headers: {
                        'Access-Control-Allow-Origin': '*'
                    },
                    data: {
                        username: "admin",
                        password: "123"
                    }
                }).then(response => {
                    console.log(response)
                })
![image](https://user-images.githubusercontent.com/13233663/41001512-0316bdfe-6909-11e8-9aeb-3e0737d1347d.png)

Same end point responds fine in postman
![image](https://user-images.githubusercontent.com/13233663/41001533-14a26d84-6909-11e8-80eb-e631454716f4.png)

**Comment by dotboris** [comment]
The error your getting about the preflight request is because the server is not responding with the proper CORS headers.

From your code, it seems like you're trying to pass the CORS headers on the client. CORS headers need to be returned by the server. You need to change your Java backend so that it handles CORS properly.

There's a guide on the spring site explaining this: https://spring.io/guides/gs/rest-service-cors/

CORS are a very important security feature in the browser. You should really understand how they work and what kind of security implications they have.

MDN has a in-depth article on this: https://developer.mozilla.org/en-US/docs/Web/HTTP/CORS

Here's an article that describes what the security implications of CORS are: https://mobilejazz.com/blog/which-security-risks-do-cors-imply/

**Comment by emilyemorehouse** [comment]
I agree with @dotboris (thanks for posting such a thorough response!)

Closing this out since it doesn't appear to be an Axios issue.
