### ISSUE TITLE
onDownloadProgress has progressEvent.total property with zero value

### ISSUE THREAD

**Issue by dobeerman** [axios/axios#1591]
I've the simplest code like 
```js
onDownloadProgress: function(progressEvent) {
    console.log('download', progressEvent);
},
```
It returns object with `total: 0` property.

Is there are any way to obtain `total` property with correct value?

**Comment by msouidi309** [comment]
I just tested the code in a get request, and it works, I think it's a problem with your request. How do you call it ?

**Comment by looterz** [comment]
I'm getting the same issue, in the latest chrome browser. The only options configured for the axios instance are `baseURL` and `onDownloadProgress`.

**Comment by kyledavelaar** [comment]
I am having the same issue with multiple browsers.  I can get all the other properties just fine but total is always coming to 0.

**Comment by ybroch** [comment]
i also get this same issue, when i deal with download progress function ,it can mark width axios require file, when in progressEvent ,its loaded has change value, but its total always 0.

**Comment by qkdreyer** [comment]
Ensure that your server is sending the Content-Length response header

**Comment by muthami** [comment]
> Content-Length response header

I had the same problem (_download progress total property as zero_) and when i made sure the server was returning `Content-Length response header,` all went well.

**Comment by Ruan-tang** [comment]
I have Content-Length, but total is always 0, which is not resolved

**Comment by Ruan-tang** [comment]
Can anyone tell me what should I do

**Comment by jasonsaayman** [comment]
If it is Chrome there is pretty much nothing

> Axios binds the `onDownloadProgress` function directly to native `progress` event of the `xmlhttprequest` instance: [xhr.js#L145](https://github.com/axios/axios/blob/503418718f669fcc674719fd862b355605d7b41f/lib/adapters/xhr.js#L145).
> The problem is in gzipped responses. Chrome for example has always for such responses `lengthComputet=false` and `total=0`. This makes also sens, as `total` reports the size of the content itself, and browsers can't predict how many bytes will be the content. `loaded` reports the size after decoding, so even if you read the `content-length` header with
> 
> ```js
> onDownloadProgress(event) {
>   event.srcElement.getResponseHeader('content-length')
> }
> ```
> 
> at some point you will get `loaded > contentLength`. A workaround would be to send the actual size in headers, smth. like `X-Actual-Content-Length` and then read the correct size in `onDownloadProgress`.

**Comment by Ruan-tang** [comment]
Hello, I still don't understand, sorry.what should I do, or leave it to back-end developers to do it? Enterprise-level projects will definitely enable gzip compression. Does it require back-end developers to return my real content-length?

**Comment by jasonsaayman** [comment]
Well the back end developer could send you the content length or file size in bytes via a header, that should solve part of your issue.

**Comment by Ruan-tang** [comment]
But I already have the content-length field, total is always 0

**Comment by manuel-delaiglesia** [comment]
The issue here is that the <code>onDownloadProgress</code> event don't get fired at all, so no matter what you can send on any custom headers.
This issue should be reopened

**Comment by Grant10k** [comment]
> Axios binds the `onDownloadProgress` function directly to native `progress` event of the `xmlhttprequest` instance: [xhr.js#L145](https://github.com/axios/axios/blob/503418718f669fcc674719fd862b355605d7b41f/lib/adapters/xhr.js#L145). The problem is in gzipped responses. Chrome for example has always for such responses `lengthComputet=false` and `total=0`. This makes also sens, as `total` reports the size of the content itself, and browsers can't predict how many bytes will be the content. `loaded` reports the size after decoding, so even if you read the `content-length` header with
>```js
>onDownloadProgress(event) {
>  event.srcElement.getResponseHeader('content-length')
>}
>```
> at some point you will get `loaded > contentLength`. A workaround would be to send the actual size in headers, smth. like `X-Actual-Content-Length` and then read the correct size in `onDownloadProgress`.

Hours of searching on how to solve this gzip download size problem and this finally got me to a solution. I could not for the life of me find anywhere that answered how to get the response headers _before_ the response is finished downloading. I knew Axios had it somewhere in there because it gets the content-length for when `onDownloadProgress` works correctly. 

A key component I was missing for a while is that `onDownloadProgress` isn't the event anymore, but a few useful numbers _and_ the event, so it's a level deeper. I also missed that since the `.getResponseHeader()` is a function it doesn't show up when you just `console.log(progress)` and try to scour the result looking for a useful number. I had set my own header with the original file size (before gzipping) to `X-File-Size` and allowed it to be read in the browser with `res.set({'Access-Control-Expose-Headers': "X-File-Size"});` but couldn't seem to access it until the response was done and it didn't matter anymore. 

I ended up with 
```js
onDownloadProgress(progressEvent){
    const progress = progressEvent.loaded / progressEvent.event.target.getResponseHeader('x-file-size');
    const percent = Math.round(progress * 100);
    console.log("Percent Complete " + percent + "%")
}
```
`srcElement` and `target` both seem to work. 

I was about to come up with some crazy workaround by sending an ID with the request, and the server would send the original file size out as a websocket message along with the file, which the browser would receive first and then start calculating the download size... I'm glad I found the real solution because it was just out of reach for several hours.

**Comment by jaredhill4** [comment]
Can you reopen issue https://github.com/axios/axios/issues/2709?

It seems it is not resolved and I'm still experiencing the issue.

**Comment by mrvcoder** [comment]
same

**Comment by rabin999** [comment]
still the same, what a mess
