### ISSUE TITLE
Add support for async transformRequest

### ISSUE THREAD

**Issue by aartek** [axios/axios#1601]
Hello, I have a feature request to this project. It would be great if you could add support for async transformRequest functions.

The goal I want to achieve is to add oauth2 token to the authorization header, but this token must be fetched from external service, and sometimes must be refreshed, so the function which manages it is asynchronous. 

It'd be great if that code could work:
```
        const instance = axios.create({
            transformRequest: [async function (data, headers) {
                headers['Authorization'] = 'Bearer ' + await loginService.getToken()
            }],
        });
```

**Comment by baijunjie** [comment]
I have the same need

**Comment by baijunjie** [comment]
`interceptors.request` support for async function.

```js
axios.interceptors.request.use(async function (options) {
    options.headers['Authorization'] = await getToken();
    return options;
}, function (error) {
    console.log('Request error: ', error);
    return Promise.reject(error);
});
```

**Comment by gabrielwillemann** [comment]
+1

**Comment by chinesedfan** [comment]
I know a tricky way is based on that, an async function returns a Promise.

```
.use(() => {
   return (async function() {})();
})
```

**Comment by amoshydra** [comment]
Hi, I don't think the [proposed solution work](https://github.com/axios/axios/issues/1601#issuecomment-564110779). Not sure why this issue is closed though...

Looking at how `transformRequest` is used in `transformData`, returning a Promise inside `transformRequest` may yield incorrect result.
https://github.com/axios/axios/blob/203cbc2da0ef0f68d517ba2a6176df1d48efc2fb/lib/core/transformData.js#L13-L20

I don't think `transformRequest` allow async operation out of the box.


#### Alternative?
However, I think the requirements from both @aartek and @baijunjie  can be solved with [Axios' request interceptor](https://github.com/axios/axios/blob/e50a08b2c392c6ce3b5a9dc85ebc860d50414529/lib/core/Axios.js#L60-L62)?

```ts
axios.interceptors.request.use(async (config) => {
  config.headers['Authorization'] = 'Bearer ' + await loginService.getToken()
  return config;
})
```
