### ISSUE TITLE
Axios does not catch error response

### ISSUE THREAD

**Issue by johnsoncherian** [axios/axios#1613]
In my reactjs application I have axios call as shown below.
```
axios(authOptions).then(response => {
 /* Do something */
}).catch(err => {
 if(err.response.status === '401') /* 'err.response' is undefined if 'No 'Access-Control-Allow-Origin' header is present on the requested resource' error occurs  */
    logoutFn(); /* this function logs out the user form ui */
})
```
I am getting following error when this code is executed. 

> Failed to load http://xxxxxxx:xxxx/xxxxxx/xxxx/xxx: No 'Access-Control-Allow-Origin' header is present on the requested resource. Origin 'http://localhost:3000' is therefore not allowed access. The response had HTTP status code 401.

I know this is because there is no 'Access-Control-Allow-Origin' in the response headers. But why is that when this error occurs `err.response` is an undefined object (unlike in the cases of 500 and 401 where err.response give the info like status status code etc)

**Comment by mknx-io** [comment]
It not relies to Axios, this a browser feature.

When you make an AJAX request to a host that is different from the one the app is served on, the browser first performs an OPTIONS request (also known as **preflight request**), in order to check if the CORS headers are present and valid. If not, the JS console will you show you the error you print above, and no further request is performed. That's why you don't have any response object.

To fix it, you should first fix your CORS problem, then try again to retrieve the response object.

**Comment by mknx-io** [comment]
Btw I don't think this is the best place for sharing this post... [StackOverflow](https://www.stackoverflow.com) will give you better answers.
