### ISSUE TITLE
export axios request as curl command [node] [feature request]

### ISSUE THREAD

**Issue by damianobarbati** [axios/axios#1615]
Would it be possible to add a feature like this one without external "plugins" to allow quick debugging of requests?

**Comment by delirius325** [comment]
I believe this could probably be useful! Just a simple configuration boolean to change to true (or false) and then every requests made with axios could "console.log" the cURL equivalent.

**Comment by delirius325** [comment]
@damianobarbati 

If you're interested, the module "axios-curlirize" has now been published. It's simple to implement but only supports axios@0.17.1 as of right now. This is due to the fact that we're using "axios-middleware" for this version. 

We'll be creating our own middleware and using it instead in a very near future, this way we won't be dependent of any other third-party solutions.

Thanks,

**Comment by damianobarbati** [comment]
Sounds good! I'll be downgrading axios and testing this right tomorrow, thanks @delirius325 :)

**Comment by delirius325** [comment]
@damianobarbati 

Don't even bother downgrading :) ! We just pushed a new version making use of axios's interceptor instead of a third-party middleware. This way you can basically use any of axios' versions. 

Have fun testing the module tomorrow, and don't be shy to provide us with feedback!

**Comment by emilyemorehouse** [comment]
Glad to see people helping people!

Thanks for creating this, @delirius325. Feel free to issue a PR and tag me if you want to add https://github.com/augmnt/axios-curlirize to the Axios README so people can find it. 😄
