### ISSUE TITLE
Axios : Authorization Bearer not sent on iOS

### ISSUE THREAD

**Issue by ligne13** [axios/axios#1632]
Hi,

I attach on every outgoing request an Authorization header whose value is 'Bearer {access_token}' with the following command : `window.axios.defaults.headers.common['Authorization'] = 'Bearer ' + localStorage.getItem('access_token');`

This works fine everywhere except on iOS where the header is not attached to the request. I also tried to attach it on a single request, and same issue. The header is not present in the request and the server returns a 401 Unauthorized error (Laravel).

The bug happens whatever the browser is on iOS : Safari, Chrome, Firefox. It is really specific to iOS (my version is 11.3.1). No problem on Android or on Desktop (MacOS, Windows). I made some debugging with the iOS Simulator (where the problem also happens) : there is an item named `access_token` in the localStorage so the problem is not related to that.

What is happening??

thanks

**Comment by OpenGG** [comment]
Make a simple online demo please.

**Comment by leandroferreira** [comment]
See https://github.com/axios/axios/issues/1469

**Comment by robertleeplummerjr** [comment]
We had a similar issue in an native app where we use webviews which use safari on ios and would fail only in that environment.  The response was a very nondescript: "Error: Network Error".  No warnings, no information, just essentially silence.  It ended up being that ios + safari (around v12?) puts a sort of lock on the browser's `XMLHttpRequest`'s and `setTimeout`'s when the browser isn't visible.  We had animated the webview out of view and allowing the user interface on mobile to set settings that would trigger the webview to fire off more events that would result in the above error.

We were able to get around this issue by converting out call from:
```js
function event() {
  callbackThatSetsOffRequest();
}
```

to wrapping with a simple `setTimeout`:
```js
let timeoutId = null;
function event() {
  if (timeoutId) {
    window.clearTimeout(timeoutId);
  }
  timeoutId = setTimeout(() => {
    callbackThatSetsOffRequest();
  }, 3);
}
```

We set the milliseconds to `1` at first with a lot of success, but it failed once in 50 attempts, so we bumped it to `3`.

I've not seen this documented anywhere, but only was able to infer that it is a behavior because no matter how many times I tried, I couldn't get something like `setTimeout(() => alert("hi mom!"), 1);` to trigger while the webview was out of focus.  The good news is that as soon as the webview came back into focus, `setTimeout` would continue where it left off, and `XMLHttpRequest` is restored to proper functionality.

**Comment by AIR-FRAME** [comment]
> We had a similar issue in an native app where we use webviews which use safari on ios and would fail only in that environment. The response was a very nondescript: "Error: Network Error". No warnings, no information, just essentially silence. It ended up being that ios + safari (around v12?) puts a sort of lock on the browser's `XMLHttpRequest`'s and `setTimeout`'s when the browser isn't visible. We had animated the webview out of view and allowing the user interface on mobile to set settings that would trigger the webview to fire off more events that would result in the above error.
> 
> We were able to get around this issue by converting out call from:
> 
> ```js
> function event() {
>   callbackThatSetsOffRequest();
> }
> ```
> 
> to wrapping with a simple `setTimeout`:
> 
> ```js
> let timeoutId = null;
> function event() {
>   if (timeoutId) {
>     window.clearTimeout(timeoutId);
>   }
>   timeoutId = setTimeout(() => {
>     callbackThatSetsOffRequest();
>   }, 3);
> }
> ```
> 
> We set the milliseconds to `1` at first with a lot of success, but it failed once in 50 attempts, so we bumped it to `3`.
> 
> I've not seen this documented anywhere, but only was able to infer that it is a behavior because no matter how many times I tried, I couldn't get something like `setTimeout(() => alert("hi mom!"), 1);` to trigger while the webview was out of focus. The good news is that as soon as the webview came back into focus, `setTimeout` would continue where it left off, and `XMLHttpRequest` is restored to proper functionality.

I have a similar issue, can you please explaing what you are going inside "callbackThatSetsOffRequest" ?

**Comment by robertleeplummerjr** [comment]
Literally just an axios get request.

**Comment by chinesedfan** [comment]
Closed due to stale. If the issue is still there, feel free to open a new one.
