### ISSUE TITLE
How to Trigger A refresh Token?

### ISSUE THREAD

**Issue by chobo2** [axios/axios#1674]
I am wondering what the best way to handle refresh tokens are. 

I followed the implementation from this book: [ASP.NET-Core-2-and-Angular-5][1] but I am not using Angular, instead I am using Axios + reactjs.

I been looking around and seems like I need to use Axios interceptors but I am not really sure how to really use.

I found [this example][2], but I am not 100% clear on what is happening in the code.

    client.interceptors.request.use((config) => {
      let originalRequest = config;
      if (tokenIsExpired && path_is_not_login) {
        return issueToken().then((token) => {
          originalRequest['Authorization'] = 'Bearer ' + token;
          return Promise.resolve(originalRequest);
        });
      }
      return config;
    }, (err) => {
      return Promise.reject(err);
    });

Right now I have an Axios instance that I created like this

    export const axiosInstance = axios.create({
        baseURL: 'https://localhost:44391/api',
        timeout: 5000,
        contentType: "application/json"
      });

so would I first add the interceptor before I export it?

Second with the book example I get a token response like this

    {
        "token": "",
        "expiration": 1,
        "refreshToken": ""
    }

So I am not sure, if I should be return a date instead to be checking instead of in minutes how long till it expires(ie 1 minute after being issued).

Though do you guys agree with the offer, I understand what he is trying to do to save a call to the server and then having it rejected at which point then you would ask for a refresh token and try the request again.

I am just a bit worried if say the token is like 1 second away from expiring and it passed the check of "tokenIsExpired" but by the time the server gets the request the token is expired and it fails.

Though I am not sure really how these axios interceptors work, like this one seems to happen before a request, I am not sure if they got one for if a request fails.

  [1]: https://github.com/PacktPublishing/ASP.NET-Core-2-and-Angular-5
  [2]: https://medium.com/@mateioprea/maintaining-api-authentication-using-axios-e70ba174da6

**Comment by delirius325** [comment]
Hi there,

I would indeed, as you suggested, make the expiration comparison against a date in ms (Unix time) instead of minutes. This way you'll be super accurate. 

At first I was also going to explain the interceptor you mentionned, but seems like you get it.

Cheers :smile: !

**Comment by chobo2** [comment]
@delirius325  

Yea, I understand it more now that I know is a request one and response one.

I ended up something like this, I opted to do it in the response as I just know there is going be that one time that the race condition will fail and the stored date will say it is valid but by the time the server gets there it will be expired.

```
axiosInstance.interceptors.response.use(
  function(response) {
    return response;
  },
  function(error) {
    const originalRequest = error.config;
    console.log("e");
    if (error.code != "ECONNABORTED" && error.response.status === 401) {
      if (!originalRequest._retry) {
        originalRequest._retry = true;
        return axiosInstance
          .post("/tokens/auth", {
            refreshToken: getRefreshToken(),
            grantType: "refresh_token",
            clientId : "sourceLine"
          })
          .then(response => {
            localStorage.authentication = JSON.stringify(response.data);
            updateAuthInstant();
            return axiosInstance(originalRequest);
          });
      } else {
        localStorage.removeItem("authentication")
        console.log("fafaf")
        browserHistory.push({
            pathname: '/login',
        });
      }
    
    }
    return Promise.reject(error);
  }
);
```

I am though open to suggestions.

**Comment by delirius325** [comment]
Hey @chobo2,

Doing it on the response is a good idea! 😄 

If your problem is solved, feel free to close the issue 👍 !
Cheers and have a wonderful day,

**Comment by chobo2** [comment]
@Dinuz 

Can you explain more what you mean? I sort of switched away from this though my new way still has some bugs.

The reason I left this way was if I had multiple requests going off at one and one of them triggered a refresh it was possible for the others to have an invalid token.

I gone to a method that checks a couple mins before the refresh token needs to be refreshed and it does  this before any other request goes out but I got some bug where I guess this is not happening and I get logged out.

So I am still looking for a good solution.

**Comment by Dinuz** [comment]
@chobo2 what I do is choosing a time limit (eg 2 minutes), and check in the request if the refresh token it’s still valid (if not, logout and redirect to login). If the refresh token is valid, then check the access token expiration time, again here I use a safe time, meaning if I am close to expiration I refresh otherwise I proceed doing nothing except setting in the header the access token (or if not required leaving it empty). 
I use a Vuex solution to manage the state, and I get the data (expirations, tokens etc) from there.
The actions in my store are involving calls to my axios client setup(for calling my backend api). Here you need to be particularly careful because if for example you use the same axios instance to call a method that is referred inside of your interceptor you gonna have a circular dependency problem.
The way in which I solve this is defining 2 other axios istances, with their respective interceptors; one for the refresh token (the interceptor set the header to refresh token), and one for not Auth required calls (eg logout), and the interceptor is just a basic one that sets url and options that I want.
The axios calls in your client api are all made with the instance that triggers the refresh(the first one I described with the time limits), except the call to the refresh endpoint that uses the refresh interceptor, and the call to the logout(or any other not Auth required method that you need).

This works extremely well, you cannot have failures because the token check is made in the request (obviously choose your time limit wisely depending on your system - it should take care of concurrently api calls).

I also have an interceptor in the response, but it only handles potential weird errors on server side(like lost connection, page not found etc).

Took me a bit to get this working properly, and only due to the circular dependency(I couldn’t really hijack the first interceptor alone).

I am actually traveling and writing you from my phone, but if you need some help please ask and I can put some code as soon as I land and able to open my laptop.

Cheers

**Comment by chobo2** [comment]
Sure if you can put some sample code that would be great. I not in rush as I was planning to handle this in a few week from now.

**Comment by jeevasusej** [comment]
How do we handle for multiple request?

**Comment by namoojaalallee** [comment]
This is very important

**Comment by delirius325** [comment]
@jeevasusej @namoojaalallee ; this is a very old (and closed issue). For more help, I strongly suggest creating a new issue over at StackOverflow instead of on GitHub.
