### ISSUE TITLE
Denial Of Service (DoS)

### ISSUE THREAD

**Issue by LucasBrazi06** [axios/axios#1696]
# [Denial Of Service (DoS)

## Issue Details

- **Vulnerability**: Denial Of Service (DoS)
- **Severity**: Medium

## Issue Description
axios is vulnerable to denial of service (DoS) attacks. The vulnerability exists as content can continue to be sent through the stream even after the request has exceeded the `maxContentLength`, potentially causing a denial of service attack.

https://github.com/axios/axios/commit/79a1ed204f4c2971b573edde816b3a43b25240da

**Comment by delirius325** [comment]
Hey there,

axios requests are based on the [follow-redirect](https://github.com/olalonde/follow-redirects) module. As you can see in follow-redirect's code here :

https://github.com/olalonde/follow-redirects/blob/master/index.js#L78
```javascript
  // Only write when we don't exceed the maximum body length
  if (this._requestBodyLength + data.length <= this._options.maxBodyLength) {
    this._requestBodyLength += data.length;
    this._requestBodyBuffers.push({ data: data, encoding: encoding });
    this._currentRequest.write(data, encoding, callback);
  }
  // Error when we exceed the maximum body length
  else {
    this.emit("error", new Error("Request body larger than maxBodyLength limit"));
    this.abort();
  }
```

If the content-length is bigger than the max, an error is thrown and the request is aborted. We can also see the part of axios' code that handles the error part :

https://github.com/axios/axios/blob/master/lib/adapters/http.js#L196
```javascript
stream.on('error', function handleStreamError(err) {
  if (req.aborted) return;
  reject(enhanceError(err, config, null, lastRequest));
});
```

Isn't that enough already? Otherwise, then adding the stream.destroy() is a great idea.
Cheers 😄 ,
