### ISSUE TITLE
Axios is sending the Authorization header in preflight requests

### ISSUE THREAD

**Issue by CheyenneForbes** [axios/axios#1835]
#### Summary

Axios is sending the Authorization header in preflight requests, which it shouldn't

There should be an option to enable/disable this

The error is
`Request header field Authorization is not allowed by Access-Control-Allow-Headers in preflight response.`

This doesn't work (the jquery ajax alternative works)
```
    HTTP.get("http://mysite.com/",{
      responseType: 'text',
      withCredentials: true,
      auth: {
        username: "abcd",
        password: "1234"
      }
    })
    .then(response => {});
```

This works (after entering the username and password in the pop up)
```
    HTTP.get("http://mysite.com/",{
      responseType: 'text',
      withCredentials: true,
      /*auth: {
        username: "abcd",
        password: "1234"
      }*/
    })
    .then(response => {});
```

#### Context

- axios version: 0.18.0

**Comment by Maksio** [comment]
I decide this issue with setting server's answer 
`$response->headers->add('Access-Control-Allow-Headers', 'Authorization, Content-Type');`

**Comment by nicroto** [comment]
I am having a similar issue. I am not setting the Authorization header anywhere from my client code.

Unfortunately, I can't work around it since I don't have any control over API server I am calling. I can't ensure they send the Authorization header.

Is there any way to explicitly tell axios not to ask for this header in the preflight request.

(happens on Chrome Version 71.0.3578.98, and I am using the latest nuxtjs/axios module)

**Comment by FatimahSanni** [comment]
If you are doing this from your local environment i.e. localhost, you might have to move to server side but to test on client, just install [Allow CORs](https://mybrowseraddon.com/access-control-allow-origin.html) extension in Chrome and turn it on.

**Comment by chinesedfan** [comment]
[CORS](https://developer.mozilla.org/en-US/docs/Web/HTTP/CORS) problem, instead of an axios issues.

**Comment by stouch** [comment]
I really think Axios has a CORS issue..... Someone has found a solution ?
