### ISSUE TITLE
In IE 11, for XHR calls, resolve or reject sometimes waits for arbitrary seconds when there is no user interaction

### ISSUE THREAD

**Issue by racsonleung** [axios/axios#1862]
#### Summary

In the initialization of my app, about 30 XHR calls are fired continuously. Normally, the initialization is completed in 1-2 seconds. However, there is a weird case. If I stop any interaction on the app (no keyboard press, no mouse move, no mouse click) when the app is initializing, some XHR calls takes 2-4 seconds to complete for each. If F12 Developer Tools is not opened, they may take even more seconds to complete.

After I drilled into the code and add some logs in _\node_modules\axios\lib\adapters\xhr.js_, the cause is found. In _xhr.js_, _settle(resolve, reject, response)_ is called. In _\node_modules\axios\lib\core\settle.js_, _resolve()_ and _reject()_ sometimes wait for arbitrary seconds to complete.

It seems that it is not a problem of axios, but IE 11. After googling, it seems that fetch (another AJAX call lib) encounted the same problem too.

> Thanks for letting us know. Unfortunately, I don't think there is anything we can do here to fix IE behavior, sans wrapping every XHR call in an arbitrary setTimeout. We won't do that, because if we choose a value for the timeout e.g. 10 seconds, then we prevent everyone from making requests that may take longer than 10 seconds.

Ref: https://github.com/github/fetch/issues/533

They suggest to wrap _resolve()_ and _reject()_ with _setTimeout()_. I tried the workaround in _settle.js_ and it works.
`setTimeout(function() {resolve(response);}, 0);`

Did anyone else encounter this problem?

#### Context

- axios version: v0.18.0
- Environment: Windows 7, Internet Explorer (v11.0.9600.19080IS)

**Comment by zkf** [comment]
Thank you @racsonleung for taking the time to describe this issue! I arrived here after extensive googling about a similar issue I am encountering while running automated tests in IE11. I use Selenium/Webdriver and a Virtualbox virtual machine running Windows 10. At first it looked like an XMLHttpRequest was hanging or freezing in the background.

Now I cannot be sure that what I’m seeing is the exact same issue you’re having, but if it is, it has nothing to do with Axios. It is triggered while using Promises in IE11 and there is no mouse movement (my tests become unstuck if I move the mouse pointer across the browser viewport).

Note that IE11 has no native Javascript Promises, they have to be polyfilled. I have tested with [core-js/es6.promise.js][1], [promise-polyfill][2], [es6-promise][3], [native-promise-only][4] and even [5][bluebird]; the issue arises no matter which library is in use.

[1]: https://github.com/zloirock/core-js
[2]: https://github.com/taylorhakes/promise-polyfill
[3]: https://github.com/stefanpenner/es6-promise
[4]: https://github.com/getify/native-promise-only
[5]: https://github.com/petkaantonov/bluebird

Version info:
- core-js: 2.6.2
- promise-polyfill: 8.1.0
- es6-promise: 4.2.5
- native-promise-only: 0.8.1
- bluebird: 3.5.3

[This es6-promise issue][2.1] from 2015 seems to be about the same thing. I tested the suggested fix (adding a setTimeout() call) and it works in my case. No need to wrap resolve() in the setTimeout call; all I did was add the following code to the Javascript that is injected when running tests.

```javascript
function t () {
  window.setTimeout(t, 10)
}
t()
```

[2.1]: https://github.com/stefanpenner/es6-promise/issues/109

I’m thinking this may be a feature/bug in IE11 which is rarely encountered, so it has not yet been handled in the Promise polyfill libraries. I have not yet tried to create a minimal test case that will fail consistently, otherwise I would file issues with the library authors.

**I hope I’ve included the correct keywords so the next person googling for this issue will find this information faster than I did :)**
