### ISSUE TITLE
Getting an XMLHttpRequest error on hitting on hitting third party api's

### ISSUE THREAD

**Issue by ashishchauhan9596** [axios/axios#1961]
### Code Is: 
             axios({
                    method: 'GET',
                    url: 'http://api.dataatwork.org/v1/spec/skills-api.json',
                    withCredentials: false,
                    headers: {
                        'content-type': 'application/x-www-form-urlencoded',
                        'Content-Type': 'application/json;charset=UTF-8',
                        'Access-Control-Allow-Origin': '*',
                        'X-Requested-With': 'XMLHttpRequest'
                    }
                })
                .then((response) => {
                    console.log( response );
                })
                .catch(error => {
                    console.log(error);
                    console.log(error.request);
                });
###Error is:
 Access to XMLHttpRequest at 'http://api.dataatwork.org/v1/spec/skills-api.json' from origin 'http://112.196.13.87' has been blocked by CORS policy: Response to preflight request doesn't pass access control check: No 'Access-Control-Allow-Origin' header is present on the requested resource. 
### My environment is:
vue, laravel 
This is solved when i am enabling Allow-Control-Allow-Origin: * extension of google. What to do to resolve this issue permanently?

**Comment by morgangraphics** [comment]
What this error is telling you is the web server you control (presumably the 112.196.13.87 box) is not allowing just any ole access to anyone who asks. It also means that your browser is preventing access to http://api.dataatwork.org because it isn't allowed due to the lack or correct permissions.

CORS requests actually make 2 requests.

1. Origin. It essentially asks "Are you allowed to POST, GET, ..." here? If yes (200 response), then ...
2. Payload. Here is the information I require from the web server. 

You can see this informal introduction the the network tab of your browsers developer tools. 

The Google extension injects a header (Allow-Control-Allow-Origin) a.k.a the permissions mention above into the response that says "I'll accept a connection from you and you and her, and that guy over there"

So, to answer your question. What to do to resolve this issue permanently? You will need to add `Allow-Control-Allow-Origin: * ` header to your server configuration runnig your App. 

This is highly dependent on your server, Express uses `app.use(cors())` where as hapi looks some like 
```
"headers": [{
        "key": "Access-Control-Allow-Origin",
        "value": "*"
      }]
```

What the * is telling the world is that you Browser is allowed to accept a connection from anywhere and anyone. Maybe this is what you want for a public API or web server. This is certainly fine for development.

Or perhaps you want to only accept connections from certain Hostname where you would replace * with 'https://onlythisurl.com' e.g. This would be closer to a production like environment. 

```
"headers": [{
        "key": "Access-Control-Allow-Origin",
        "value": "https://onlythisurl.com"
      }]
```

That being said this has nothing to do with axios and everything to do with your server configuration.
