### ISSUE TITLE
Axios HttpGet vs jQuery HttpGet - CORS

### ISSUE THREAD

**Issue by Ethan0007** [axios/axios#1974]
Hi,

I just want to ask why i'm getting error when trying to request with CORS using axios.
But when i try to used jQuery it works fine.

this is my sample get request:
![image](https://user-images.githubusercontent.com/12542052/51535312-ad121e80-1e7a-11e9-8b5a-f34681cc1688.png)

Thanks!

**Comment by diegosps** [comment]
Compare the headers sent in both requests. 
You might be missing origin or other access-control headers.

**Comment by Ethan0007** [comment]
@diegosps Hi,

This is my axios request that get blocked by cors:

![image](https://user-images.githubusercontent.com/12542052/51577352-2f86f680-1eec-11e9-8dbc-9639ce6a60b0.png)

and this is my jQuery the works fine:

![image](https://user-images.githubusercontent.com/12542052/51577382-3f9ed600-1eec-11e9-920b-453819462e85.png)

Did i forgot something in the request? 

Thank you!

**Comment by diegosps** [comment]
I just started using axios today, but I realized that some configs will dispatch a preflight request before the actual request, even for GET. That is why you are seeing an OPTION request with axios. The default for the jquery is to sent those only with POST requests. You could try it.

The error you are receiving is due to CORS not being setup properly on your server. There is no [Access-Control-Allow-Methods](https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Access-Control-Allow-Methods) response header present.

**For testing purposes only**, set:
Access-Control-Allow-Methods : *
Access-Control-Allow-Origin: *
for your responses.
This should do the trick.

After understanding a little more about CORS, don't forget to set it up properly.

**Comment by Ethan0007** [comment]
@diegosps ,

I already added those set:
but the same issue i received:

![image](https://user-images.githubusercontent.com/12542052/51587331-0af24500-1f13-11e9-80cb-c2d747700f7a.png)

**Comment by chinesedfan** [comment]
@Ethan0007 You should set `Access-Control-Request-Headers: x-request-width`. Because you used a customized header `x-request-width`.

**Comment by Ethan0007** [comment]
@chinesedfan thank you for the reply, just to be specific which part do i set Access-Control-Request-Headers: x-request-width in server or client side?

Thanks

**Comment by chinesedfan** [comment]
@Ethan0007 Server side. You can also learn more about CORS [here](https://developer.mozilla.org/en-US/docs/Web/HTTP/CORS). Simple ways to remember them are,

- requests headers belong to client side, and usually include `request` keyword
- response headers belong to server side, and usually include `allow` keyword

**Comment by AllainPL** [comment]
Just to clarify - you will not get `OPTIONS` request only if it is a _simple_ request - details here https://developer.mozilla.org/en-US/docs/Web/HTTP/CORS#Simple_requests

@emilyemorehouse looks like resolved and ready to close :)
