### ISSUE TITLE
Fetching a chinese website

### ISSUE THREAD

**Issue by josephchan91** [axios/axios#2126]
I'm trying to fetch a Chinese page. But when I do a console.log(response.data), the Chinese characters only show as question marks ����

```
axios.get("https://detail.1688.com/offer/561428603386.html").then(function(response) {
    console.log(response.data);
});
```

I've tried playing with the config params but nothing's worked.

Any suggestions?

**Comment by terminatorheart** [comment]
you have to use responseType: 'arraybuffer' as follows:
```
import axios from 'axios';
import iconv from 'iconv-lite';

axios.get("https://detail.1688.com/offer/561428603386.html", { responseType: 'arraybuffer'}).then(function(response) {
  data = iconv.decode(response.data, 'gbk');
  console.log(data);
});
```
the reason is in this line
[https://github.com/axios/axios/blob/v0.18.0/lib/adapters/http.js#L196-L198](https://github.com/axios/axios/blob/v0.18.0/lib/adapters/http.js#L196-L198)

please refer this issue [https://github.com/axios/axios/issues/332#issuecomment-222082482](https://github.com/axios/axios/issues/332#issuecomment-222082482)

**Comment by Alanscut** [comment]
hi @josephchan91 ，@terminatorheart 's way is a good choice.
