### ISSUE TITLE
node axios https module as a client

### ISSUE THREAD

**Issue by LNyears** [axios/axios#2178]
Hello, I have a need for help here.
I use the node axios https module as a client to send https requests. How to prevent middleman packet capture attacks, what should I do?

**Comment by jasonsaayman** [comment]
Hi,

Could you please provide more information on this issue? If your concern is purely Man in the Middle attacks, the issue would be out of the scope of Axios. I would suggest reading about the use of HTTPS, and CSFR tokens, below are some links that may be of interest:

[CSFR Explanation from Wikipedia](https://en.wikipedia.org/wiki/Cross-site_request_forgery)
[CSFR Token package for Node](https://www.npmjs.com/package/csrf)
[HTTPS with HSTS](https://en.wikipedia.org/wiki/HTTP_Strict_Transport_Security)

Thanks

**Comment by emilyemorehouse** [comment]
Since this issue hasn’t received a response and this doesn’t look like an Axios bug based on the info we have, I’m closing this issue.

If you need further assistance, please post on [Stack Overflow](http://stackoverflow.com/questions/ask?tags=axios), [Gitter](https://gitter.im/mzabriskie/axios), or comment again on this issue.
