### ISSUE TITLE
i suggest : proxy protocol should have default value as  http, if the baseUrl string does not contain this part 

### ISSUE THREAD

**Issue by dimboyNew** [axios/axios#2184]
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by jasonsaayman** [comment]
@dimboyNew Please, can you fill out the required information to create an issue else we will not be able to help you.

Thanks

**Comment by dimboyNew** [comment]
> @dimboyNew Please, can you fill out the required information to create an issue else we will not be able to help you.
> 
> Thanks

@jasonsaayman . Actually i am not sure what information are required . Can you help list, so that i can provide .   This is related to  the $Http.js part, when we parse an httpUrl , we are not consider the http protocol as default . Thanks jason!!    -- dim

**Comment by jasonsaayman** [comment]
@dimboyNew It seems that you would like to log a bug, please try copying this and then filling it in accordingly:



**Describe the bug**
A clear and concise description of what the bug is. **If your problem is not a bug, please file under Support or Usage Question**

**To Reproduce**
Code snippet to reproduce, ideally that will work by pasting into something like https://npm.runkit.com/axios, a hosted solution, or a repository that illustrates the issue. **If your problem is not reproducible, please file under Support or Usage Question**

```js
// Example code here
```

**Expected behavior**
A clear and concise description of what you expected to happen.

**Environment:**
 - Axios Version [e.g. 0.18.0]
 - OS: [e.g. iOS 12.1.0, OSX 10.13.4]
 - Browser [e.g. Chrome, Safari]
 - Browser Version [e.g. 22]
 - Additional Library Versions [e.g. React 16.7, React Native 0.58.0]

**Additional context/Screenshots**
Add any other context about the problem here. If applicable, add screenshots to help explain.

**Comment by ipanasenko** [comment]
Maybe this is the issue OP @dimboyNew is describing:

I'm facing an issue when running jest test, when I make request to protocol-relative urls (//example.com) I see request goes to `localhost:80//example.com`. It wasn't a case with axios v0.18.0

**Comment by jasonsaayman** [comment]
@dimboyNew, is your issue similar to the one @ipanasenko is describing?

**Comment by dimboyNew** [comment]
Can you provide the issue  id or issue url to check , from the description  it differs a little. thanks for replying later after the weekend.

**Comment by jasonsaayman** [comment]
@dimboyNew I don't have an issue number for this one, it had seemd that @ipanasenko was having the same issue as you above he stated the following:

> I'm facing an issue when running jest test, when I make request to protocol-relative urls (//example.com) I see request goes to localhost:80//example.com. It wasn't a case with axios v0.18.0

I was wondering if you were having the same issue as described here or similar? If it similar I can put in a pull request for a fix.
