### ISSUE TITLE
why offer canceltoken instead of expose req.abort for developers  to cancel a request ?

### ISSUE THREAD

**Issue by chenjsh36** [axios/axios#2264]
Hi, I have read part code of axios, it use canceltoken to cancel request base on cancelable promises proposal，it’s  wonderful. But I do not understand why can not  just expose request.abort api for developer to cancel request directly.

**Comment by yyfearth** [comment]
Because there is not such thing called `request` that returned, and you cannot expecting provide the abort function to the request parameter.
Axios always return a promise, and you cannot add `abort` method to a promise. Because it is violate the standard, and also the added `abort` method is not pass though the promise chain.
Actually what they should do is instead of use canceltoken, they should use the new [AbortController](https://developer.mozilla.org/en-US/docs/Web/API/AbortController), or make them both work. They are basically the same thing but different in API.

**Comment by jphilipstevens** [comment]
I would also add that if you are referring to http request: https://nodejs.org/api/http.html#http_request_abort

Axios needs to work in the browser. Request is not in the browser. Axios has worked to hide those details from the developers and as @yyfearth mentioned you only have access to the Promise object created for your call.

**Comment by chenjsh36** [comment]
Thanks for your detail answers. @yyfearth @jphilipstevens
