### ISSUE TITLE
Submit request body woth PROPFIND request

### ISSUE THREAD

**Issue by DeepDiver1975** [axios/axios#2270]
**Describe the issue**
According to the README:
```
  // `data` is the data to be sent as the request body
  // Only applicable for request methods 'PUT', 'POST', and 'PATCH'

```

In case of a PROPFIND request I want to send a body as well - it this possible?

THX

**Example Code**

https://github.com/perry-mitchell/webdav-client/blob/180646b5f4971eec5d4fdea6b5a90136dff68d94/source/interface/directoryContents.js#L10-L25

**Comment by DeepDiver1975** [comment]
Another verb is REPORT which also has a request body

**Comment by jamespearson** [comment]
Did you managed to make PROPFIND work with body data?

**Comment by DeepDiver1975** [comment]
> Did you managed to make PROPFIND work with body data?

no ... still stuck at this ....

**Comment by chinesedfan** [comment]
@DeepDiver1975 "applicable" here is something like "suggested but not disabled".

Closed due to the question has been answered. But if you met problems, hope [this guide](https://github.com/chinesedfan/You-Dont-Know-Axios#problem-solutions) can help you. And feel free to open a new issue when you confirmed that you have discovered something wrong in axios.
