### ISSUE TITLE
Axios.get: Tail zero is missing

### ISSUE THREAD

**Issue by 549393092** [axios/axios#2279]
When call axios.get() method, I checked the response data in the chrome dev tool. 
see below example data.
{"flowId":"3100000002","stdQty":100.000,"netPrice":10.00}
But when using the syntax
axios.get('/orders/123').then((response) => {
   console.log(response.data)
}).catch((error) => {
   console.log(error)
})
When checking the response data, you will find stdQty = 100 and netPrice = 10.
So the tail zero is missing.
How can I keep them?

**Comment by asingh04** [comment]
I guess this is a javascript feature of dropping the trailing zeros of float type data. 
So the trailing zeros after the decimal points get dropped and the value becomes of Int type

**Comment by 549393092** [comment]
Thanks!

**Comment by Chris3y** [comment]
So... what's the fix?

**Comment by yasuf** [comment]
this happens when parsing the response, the trailing 0 after the decimal point are taken out, most likely in https://github.com/axios/axios/blob/097948698a057235140cc275504c12d5d20281b8/lib/defaults.js#L61 , if you want to do something different instead of the JSON.parse, you can try writing your own `transformResponse` in your settings

**Comment by Chris3y** [comment]
OK, thank you!

**Comment by asingh04** [comment]
Yes, there is no fix for it as it is not a bug of any kind. It just how JS works.
If you really need to preserve the 'n' decimal places, you have to use `Number.prototype.toFixed(n)` in your response handler function to get the even trailing 0s.
