### ISSUE TITLE
Access axios instance within interceptor

### ISSUE THREAD

**Issue by ashersaupingomez** [axios/axios#2343]
Simple question: is it possible to access the axios instance itself within a request interceptor?

**Comment by G07cha** [comment]
Unless you pass it from outside, no, it's not possible.

**Comment by ashersaupingomez** [comment]
Ok, that's how I've been building my interceptors. I was asking because I have a few interceptors as packages for axios, but the interceptors themselves require axios as well. So, it's doubling up on its dependency on the axios package.

Depending on axios within an interceptor is required for those that need to make requests within the interceptor (if the interceptor is a separate package). Is this true or is there a better way for me to do things? From some packages I've seen, others might be curious to know too.

**Comment by G07cha** [comment]
Since axios allows to create separate instances with their own configuration you would probably need to rely on provided axios instance rather than use your own, for example by using a common variation of [factory pattern](https://en.wikipedia.org/wiki/Factory_method_pattern):

```javascript
const axios = require('axios')
const makeYourInterceptor = require('./path-to-your-interceptor')

const instance = axios.create()
const yourInterceptor = makeYourInterceptor(instance)

instance.interceptors.request.use(
  yourInterceptor.requestHandler,
  yourInterceptor.errorHandler
)
```

And your interceptor package would look like this:

```javascript
function makeYourInterceptor(axios) {
  return {
    requestHandler: function(config) {
      // use passed axios instance here
    },
    errorHandler: function(error) {
      // use passed axios instance here
    }
  }
}

module.exports = makeYourInterceptor
```

**Comment by ashersaupingomez** [comment]
Hm... Yes, there's that! Thank you.

**Comment by ansonatloop** [comment]
Just wondering, is this not possible due to deep restrictions in the library's implementation? Or is it simply just not implemented? It seems like a no-brainer to me to be able to access the instance in an interceptor. If I want to write an interceptor that is reused across multiple axios instances, it is reasonable to assume I'd like to use the scoped axios instance inside them. For instance, building a request retry mechanism would need the original instance.

I understand the above solution works, but if it's not a big pain to add an `instance` property to the `config`, `response` or `error` arguments, that would be very useful.
