### ISSUE TITLE
incorrect header check

### ISSUE THREAD

**Issue by efreibe** [axios/axios#2406]
Hello, why this code is throwing "incorrect header check"?

```javascript
response = await axios.get(
"https://www.mercadopago.com/instore/merchant/qr/2964465/80d7b33156aa47eea2b9a4ab59f93bd5a52597d9076b47f39f54e2b7412973ed.png", {
      responseType: 'arraybuffer'
    })
```

I tested in the browser (even in incognito mode) and is returning an image.
Changed responseType to 'blob' or 'stream' but I cannot get rid of that exception.

**Comment by efreibe** [comment]
I've discovered that the site is sending a header content-encoding: gzip but the data is sent in plain text, so the libray fails to decompress that data.

There is a workaround to consume this response or remove that header before data is gzipped?

Thank you

**Comment by doplic** [comment]
I've run into this same issue. It looks like the code that attempts to process the compressed data is here:
[https://github.com/axios/axios/blob/master/lib/adapters/http.js](url)
Line 186-190

The axios version I'm using:
"axios": "^0.19.0"

I did a quick ghetto fix adding the following error catching on the decompression code to my local axios library. It just passes the stream data onto the next steps if the decompression fails. It's working for me, but maybe not a committable solution.

```javascript  
case 'gzip':
case 'compress':
case 'deflate':
  // add the unzipper to the body stream processing pipeline
  if(res.statusCode != 204) {
    stream.pipe(zlib.createUnzip()).on('error', function() {
      stream = stream;
    });
  } else {
    stream = stream;
  }

```

**Comment by efreibe** [comment]
Maybe the solution is to analyze the stream and look for the PK signature.

**Comment by doplic** [comment]
Axios tries to handle all that for you by checking the server response headers. The decompression is all taken care of by the zlib library via the "createUnzip()" call in Axios (see [Zlib createUnZip()](https://nodejs.org/api/zlib.html#zlib_zlib_createunzip_options) ). So the Axios library says to the zlib library "decompress this response data for me because the server headers indicate it's compressed", and the Zlib library returns "this isn't compressed data".  Axios just passes that error up to the user, and I don't know of a way of catching that error other than modifying the Axios library code.

Not to steer people away from the Axios library, but I had a much easier time with the 'request' library for edge-cases like the one described above: https://www.npmjs.com/package/request

**Comment by yagodorea** [comment]
Did someone find any solution for this? I'm facing exactly the same issue integrating with MercadoPago.

**Comment by efreibe** [comment]
Please, use @doplic's solution. It's working for MercadoPago.

**Comment by chinesedfan** [comment]
[Ignoring errors during decompressing](https://github.com/doplic/axios/commit/0e83cc5422a54ccca37b992e0d2741bb3c96e3ca) is not the ideal solution. #2661 has added an option to disable the default decompress. Then users can decompress data and handle errors by themselves, with help of `responseType: stream` and `transformResponse`.

If someone can learn how package request does, glad to hear that.

```
axios({
  decompress: false,
  responseType: 'stream',
  // if you want to enhance the default transformResponse, instead of replacing,
  // use an array to contain both the default and the customized
  transformResponse(data) {
    try {
      return data.pipe(zlib.createUnzip())
    } catch (e) { // hope the error can be caught
      return data
    }
  }
})
```

**Comment by ikerya** [comment]
i was experiencing this issue due to an outdated version of axios. I used 0.21.1, after upgrading to 1.6.8 the error ceases to exist.
