### ISSUE TITLE
Function signatures are inconsistent

### ISSUE THREAD

**Issue by milosivanovic** [axios/axios#2431]
The most common use cases for the `axios.get`, `axios.head` or `axios.options` functions are to send an HTTP request, possibly with some params. The same applies for for a `axios.post`, `axios.put` and `axios.patch`, except instead of params, they commonly take a request body.

The current function signatures used in axios are not friendly towards these common use cases in a consistent manner.

As per the documentation in the README, the function signatures are as follows:

```
axios.request(config)
axios.get(url[, config])
axios.delete(url[, config])
axios.head(url[, config])
axios.options(url[, config])
axios.post(url[, data[, config]])
axios.put(url[, data[, config]])
axios.patch(url[, data[, config]])
```

Notice that the `get`, `delete`, `head` and `options` methods do not take `params` as their second parameter. This isn't intuitive, is inconsistent with the remaining functions, and people have been confused by this: https://stackoverflow.com/questions/40947650/axios-get-in-url-works-but-with-second-parameter-as-object-it-doesnt

POST, PUT and PATCH currently take a second parameter that is `data`:
```
axios.post(url[, data[, config]])
axios.put(url[, data[, config]])
axios.patch(url[, data[, config]])
```
GET, HEAD and OPTIONS should follow the same pattern. By definition, GET, HEAD and OPTIONS can only take params and not a body. Thus, I propose the following function signatures:

```
axios.request(config)
axios.get(url[, params[, config]])
axios.head(url[, params[, config]])
axios.options(url[, params[, config]])
axios.post(url[, data[, config]])
axios.put(url[, data[, config]])
axios.patch(url[, data[, config]])
```

This way, we could do:

```
api.get('/my_url', {key: val})
```
which is an extremely common scenario (a GET request with params.)

Instead, right now we have to do:
```
api.get('/my_url', {params: {key: val}})
```
which (as previously described) is not intuitive and is inconsistent with other functions, because it requires `params` as a key (since it's part of the config instead of having its own dedicated parameter like the other functions.)

As for DELETE, since I believe this is most commonly used with a body, it would make sense to have
```
axios.delete(url[, data[, config]])
```
however, this one might not be as clear-cut.

**Comment by yasuf** [comment]
My assumption for why this API was built the way it is, is because POST PUT and PATCH send the data in the body of the request, instead of in the URL, which is the case of `get`, `delete`, `head` and `options`. 

I don't disagree with your arguments but I can see why the original axios developers were ok with having a difference in the signature of the methods that send the payload in the body vs in the query params, since depending on your backend server, middleware, etc. you access body vs query params differently and maybe it served as a reminder of that.

Also for GET requests, it's not always as simple as putting a object in the request, some people use `query-string` and some other people might use something else to add the params to the URL, if we make it so that it takes an object, maybe not everyone is happy since they want to do something especial.

Also you can just go with [this syntax](https://github.com/axios/axios#axiosconfig) to have a more consistent way of making API calls.

Interesting proposal @milosivanovic

**Comment by chinesedfan** [comment]
It is hard to change function signatures now, as axios is too popular. And mixing `params` with `data` will result in some problems. Image cases that we need both of them. Thanks to your advise all the same.
