### ISSUE TITLE
axios not reusing socket even though keepalive is true

### ISSUE THREAD

**Issue by gvemula** [axios/axios#2456]
we are using axios 0.19.0 to make http requests to another server for REST service. we enabled keepalive:true for http/https agent. 

setting tried:
option1: keepalive:true, maxSockets:1 
option2: keepalive:true, maxSockets:Infinity.

In both cases, noticed that it is opening new socket to REST server always, not reusing the connection.

**Comment by yasuf** [comment]
Can you elaborate a little bit further? This is most likely out of the scope of Axios since it's an HTTP client for node servers and multiple browsers. I can't find any maxSockets setting throughout the axios codebase, if this happens to be outside of the library's scope, would you mind closing the issue?

**Comment by yasuf** [comment]
question outside of axios' scope, closing for now until more information is provided
