### ISSUE TITLE
Whats the benefit of creating an instance of axios

### ISSUE THREAD

**Issue by noahehall** [axios/axios#2474]
versus just using axios({...}) to make requests?

**Comment by yasuf** [comment]
Having common settings that apply to all the requests for that instance is one of them, for instance, the `timeout` and `baseUrl` parts of the config. Although you can just have an object and add its key-value pairs to all your requests but it's up to you.

**Comment by noahehall** [comment]
thx @yasuf 

definitely makes sense to keep things DRY.  but there doesnt seem to be any intrinsic value to axios itself?

**Comment by yasuf** [comment]
can you elaborate a little bit more? no intrinsic value in creating an axios instance? or in using axios at all?

**Comment by smilledge** [comment]
Simple projects don't really benefit much from using instances. However, they become extremely useful once you start building more complex projects, especially when you need to integrate with multiple APIs.

Often each API will require slightly different configuration that would be difficult to implement using the default Axios instance, or would require duplicating code throughout your app.

Here are some example of things I regularly implement on instances;
- Building a full url from a path
- Assigning default headers
- Transforming the request and response body (eg, convert between camelcase and snake case)
- Normalizing and handling error responses
- Global handling of network errors 
- Automatically setting the `Authorization` header on requests
- Refreshing access tokens and retrying requests
- Redirecting to a login page if there's an authentication error
- Customer adapters
- Caching
- Etc

So instead of having to write something like this;

```
const data = snakecase({ ... })

try {
  const res = await axios({
    url: 'http://api.myapp.com/v2/comments',
    method: 'post',
    data,
    headers: {
      Authorization: authToken ? `Bearer ${authToken}` : null,
      'X-Custom-Header': '12345'
    }
  })

  return camelcase(res.data)
} catch (e) {
  if (isTokenExpired(e)) {
    // Refresh the token and retry the response if successful...
  }

  if (isUnauthenticated(e)) {
    router.push('/login')
    return
  }

  // Handle network errors...

  // Extract, normalize and display error messages...
  const errors = e.response.data.errors
  showError(errors)
}
```

You can implement all of the above using instance config, transformers and interceptors. Then your requests can be as simple as;

```
const res = appApi.post('comments', { ... })

// OR

const res = authApi.post('login', { ... })
```

**Comment by yasuf** [comment]
Closing as benefits have been described, thanks @smilledge !
