### ISSUE TITLE
Add isTimeout function to static API

### ISSUE THREAD

**Issue by EyalPerry** [axios/axios#2494]
## Summary
isCancel exists, which is awesome. so should isTimeout.
An axios native way of knowing - the error is caused because the request has timed out.

## Proposed Solution
axios.isTimeout function

## PR
https://github.com/axios/axios/pull/2495

**Comment by yasuf** [comment]
What's the use case you'll cover with the `isTimeout` prop? To give me a better idea how this boolean can be used.

**Comment by EyalPerry** [comment]
@yasuf 
1) implementing special handling of timeout errors via interceptor.
For one- exponential backoff.

2) Showing the user a special message, or returning one to the client - 
"Whoops, looks like our servers are unavailable right now", or returning 503 if a calling service is not available.

P.S.
Right now, the only way I know that a request timed out is by inspecting the message, which is far from ideal.

As I mentioned in the initial post, if the library provides an options to reject a promise based on some condition, it should provide a means to distinguish this condition from other ones so that the user may handle it as they see fit, either due to aforementioned or unthought of scenarios.
Much like the very welcome isCancel.

**Comment by rt1517** [comment]
@EyalPerry will this feature help us to find why `Error: timeout of 0ms exceeded` is happening? Because default timeout is set to 0, which seems to be indefinite timeout, i can not find a reason why this `Error: timeout of 0ms exceeded` is happening. This issue is created but no proper solutions or reason is discovered. https://github.com/axios/axios/issues/2103.

**Comment by jasonsaayman** [comment]
Closing in favour of #2103
