### ISSUE TITLE
Migration guides for axios alternatives

### ISSUE THREAD

**Issue by DanielRuf** [axios/axios#2530]
It seems the maintainers of axios can not handle the mass of open issues and PRs and there are issues which makes it harder for us to work with axios in production.

I would like to see migration guides for alternatives like ky, got and others.

Would be great if anyone who has migrated to an alternative can provide some migration steps.

**Comment by DanielRuf** [comment]
Hi @Alanscut,

Why was this issue closed without further notice or feedback?

**Comment by Alanscut** [comment]
Hi, @DanielRuf . sorry for closing this issue. Because I don't think it is a problem of axios. Anyone can choose to use other software instead of axios, but I don't think it is the responsibility of axios itself.
Besides, there are still some maintainers doing their best to maintain axios, closing issues, reviewing PRs, fixing bugs. And the new version v0.19.1 is on the way, after releasing it, we will merge plenty of PRs.

**Comment by yasuf** [comment]
I agree with @Alanscut, don't think axios' README is the place for a migration guide since it depends a lot on which library you'll go with and your use of axios, for some alternatives to axios you can go to https://github.com/sindresorhus/awesome-nodejs#http and again sorry if this issue was closed without an explanation

**Comment by DanielRuf** [comment]
Not the readme but an issue.

**Comment by DanielRuf** [comment]
I did not mean in the readme but in an issue.
