### ISSUE TITLE
onUploadProgress event doesn't give actual upload progress

### ISSUE THREAD

**Issue by surendragalwa11** [axios/axios#2559]
` onUploadProgress: progressEvent => {
                this.setState({totalUploadedSize: progressEvent.loaded});
	        }`

Usage: I'm uploading multiple video files and tracking each file upload progress via progressEvent's loaded value.
When I compare this progress with my backend file size the doesn't event match at all.There is a way way difference b/w actual file upload progress in backend and this `axios` `progress`

**Comment by yasuf** [comment]
we just add a [listener to the `XMLHttpRequest`](https://github.com/axios/axios/blob/6284abfa0693c983e9378b2d074c095262aac7bd/lib/adapters/xhr.js#L156), so that callback is being passed as is to the native browser event that gets called, if it doesn't match the file size on the server there might be other events that are useful for your case, you can check https://developer.mozilla.org/en-US/docs/Web/API/XMLHttpRequest/progress_event for more info

**Comment by islam-abdo** [comment]
> we just add a [listener to the `XMLHttpRequest`](https://github.com/axios/axios/blob/6284abfa0693c983e9378b2d074c095262aac7bd/lib/adapters/xhr.js#L156), so that callback is being passed as is to the native browser event that gets called, if it doesn't match the file size on the server there might be other events that are useful for your case, you can check https://developer.mozilla.org/en-US/docs/Web/API/XMLHttpRequest/progress_event for more info

May you please illustrate more or give a simple example on how to implement that

**Comment by avin-kavish** [comment]
I'm having a situation where the progress event is fired almost instantly when the upload begins with a progress of 100% but the actual network request takes 3s to complete. Is that also related to this?

**Comment by Syarx** [comment]
@avin-kavish  It's probably because your backend is running on localhost. Try to upload it to a remote server. It will return you a normal progress. If you have not access to a server, an alternative is to send reqest to 127.0.0.1 instead of localhost. You will get better feedback is the image is quite large. >2mb

**Comment by avin-kavish** [comment]
@Syarx As I have mentioned already, the upload takes 3 seconds to complete. And no, it wasn't on localhost. The image was like 5mb.

**Comment by chinesedfan** [comment]
> When I compare this progress with my backend file size the doesn't event match at all.

@surendragalwa11 It depends on how you save the uploaded file. Closed due to stale.

> but the actual network request takes 3s to complete.

@avin-kavish `onUploadProgress` doesn't include network transmission time. And better to open as a new issue if you still have problems.
