### ISSUE TITLE
Promise chain not accepting a catch block in higher order promise

### ISSUE THREAD

**Issue by AB1519** [axios/axios#2566]
Hi All,

**example:**

function bar(){
  //returns a promise resolved or rejected
}

function foo(){
  return bar().then((response) => {
     // return resolved state to foo();
  }).catch((error) => {
    //return rejecetd state to foo();
})
}

(function abc(){
      foo().then((response) => {
          //do something
    }).catch((error) => {
   //do something
  })
}());

**My Question**

bar() returns a promise state resolved or rejected. 
foo()  capture the resolved state in then and rejected state in catch block 

abc() is now capturing the resolved /rejected state in then block. 

I would like to achieve my abc() function captures the resolved response in then block and rejected response in catch block.

Please let me know what is wrong with-in my abc() ? Thanks!!

**Comment by codebling** [comment]
The issue here, I believe, is with your expectation of how promises work. 

Promise.reject() will return a rejected promise.
Promise.reject.catch() will return a resolved promise, because the error has been caught. If you want the error to propagate, you need to re-throw is in your catch block, or perhaps not catch it at all. 

Either way this has nothing to do with Axios
