### ISSUE TITLE
Internet Explorer and Edge redirects problem with axios

### ISSUE THREAD

**Issue by AlmotasemEssa** [axios/axios#2586]
hello,

When I make 'GET' request, the website replies with response code 302 and this response contains location, and the browser redirects automatically to this location.

these redirecting works with Chrome and Firefox, but it is not working with IE11.

I checked the request and response headers, I noticed that 'Content-Type' is missed in the header of the **second**  call, which means that 'content-type' exists in the first API call, but it is lost during redirecting.

I was struggling with this issue for quite long time, could anyone help me with this issue please?

**Comment by Alanscut** [comment]
hi @AlmotasemEssa , could you provide your example code?

**Comment by sotwarrior** [comment]
hi @Alanscut,

I have the same issue so far, I can provide you more details.
In short, the same code (see the explanation below) works perfectly in FF/Chrome (all the headers are set for the initial call, the headers/cookies are set and sent for all redirected calls as well).
IE/Edge ignores the header we set for the initial call (Content-Type) in the redirected call.

1/ page opened: https://example.com
2/ GET call made to https://example.com/login with custom headers set 
Content-Type = application/json; charset=utf-8 
and with withCredentials enabled because of CORS. 
data attribute has an empty object as we had an issue in Chrome/FF with headers for the redirected call:

```
            defaultHeaders['Content-Type'] = 'application/json;charset=UTF-8';
            defaultHeaders['X-Header'] = 'http://some-url.com';

            axios({
                method: 'GET',
                url: newURL,
                withCredentials: true,
                headers: defaultHeaders,
                data: {}
            }).then(response => {

```
3/ Server responds with HTTP 302, with Set-Cookie and Location header in the response, we need to send them together with the redirected call: https://example.com/login/auth
4/ For the redirected call to https://example.com/login/auth server responds with HTTP 200, 
json-object returned in case if Content-Type is set in request headers (Chrome/FF works perfectly, headers from the initial call are available for the redirected call as well), 
and html returned if Content-Type request header is missing (IE/Edge)

**Comment by Alanscut** [comment]
hi @sotwarrior ,
I have reproduced this issue, but I don’t think it it related to axios itself. When I use fetch, this problem still exists. I guess it may be caused by improper handling of IE11, but I have not found a way to avoid it.

**Comment by sotwarrior** [comment]
hi @Alanscut,
thank you for the response. Do you have any idea/workaround, how to solve redirect issue in IE?
Thank you in advance!
