### ISSUE TITLE
Axios error: Uncaught (in promise) Error: Request failed with status code 404

### ISSUE THREAD

**Issue by Dagge1** [axios/axios#2596]
#2508 ## Summary
I apologize in advance if that is not proper place to post my issue. At first I'd like to say I am a big fan of Axios. Now I'm having trouble with receiving Axios request on the Node server. I have seen similar problem posted for Apache server but there wasn't solution described. In my case server is Windows server 2016 IIS.

While requests sent to the server located on the same machine / localhost work perfectly, same request sent via Internet to the same machine but connected as remote server fails with above error. I heard somewhere that maybe it's about need for different approach in formatting URL in Axios. I tweaked server for days and every time I get same message. I cannot find out why this error involves 404 code if all routes work properly on localhost. On the Internet I found several peole with similar problems but no solution were mentioned.

Thanks

#### Context

Node v10.2.0, Windows Server 2016 IIS, front end Vue

**Comment by chinesedfan** [comment]
It is a problem that the server can't response correctly, instead of an issue of axios. Before closing, I  want to give you some directions and hope they can help you. You can look for more help in [stackoverflow](https://stackoverflow.com).

- Ping from server1 to server2 to make sure the network works well
- Send the same request by `curl` or other libraries without axios
- Compare request headers between to local with to remote server
