### ISSUE TITLE
Wrong content-type used [serious bug]

### ISSUE THREAD

**Issue by binarykitchen** [axios/axios#2651]
I've manually set the content type to `application/json` before the axios.post() call.

Yet, when the request is made, it's picking `application/x-www-form-urlencoded` huh?
So I've added a `transformRequest` function and printed out the headers there:

<img width="381" alt="Screen Shot 2020-01-10 at 16 43 26" src="https://user-images.githubusercontent.com/177641/72124242-e1068c80-33c8-11ea-88d8-3cf2a4f8382d.png">

You can see the JSON object for header, it's has nested content types inside, for each method. It ignored the content type I've manually set.

If I add these code lines then it will work

```
// unset silly defaults
axios.defaults.headers.post = null
axios.defaults.headers.put = null
```

but that's kinda silly and smells. A bug? I've read documentation carefully still am in the dark.

**Comment by chinesedfan** [comment]
@binarykitchen Right, stupid axios. But can you follow the issue template to provide axios version and your example codes?

**Comment by binarykitchen** [comment]
Apologies. I found the problem and this solves it https://github.com/axios/axios/issues/1910#issuecomment-498704197

Recommend to improve documentation about transformRequest

**Comment by avindra** [comment]
I'm having this issue and I'm not using `transformRequest`. My `axiosInstance` has been created as such:

```js
  const instance = axios.create({
    baseURL: '/api/whatever',
    common: {
      'Content-Type': 'application/json',
      Accept: 'application/json',
    },
  });
```

Since `common` is set, I would _expect_ the default to be `application/json`, but I'm seeing the issue @binarykitchen originally reported, where on _some_ POST calls, the `Content-Type` is erroneously set to `application/x-www-form-urlencoded`.

_Which_ POST calls is completely unknown to me. It appears to be random, but this is just code so I'm assuming there is a reproducible error condition.

**Comment by avindra** [comment]
Update: I figured out when it happens.

So if the code tries to `POST` but the body isn't set, axios resolves to that broken code path that is using the wrong header (picking from axios default rather than the configured options on the instance).

**Comment by chinesedfan** [comment]
@avindra Can you elaborate with axios source codes?
