### ISSUE TITLE
Remove unnecessary setTimeout in test files

### ISSUE THREAD

**Issue by chinesedfan** [axios/axios#2699]
There are lots of `setTimeout` in our tests. Some are unnecessary, i.e.

```
// test/unit/adapters/http.js

axios.get('http://localhost:4444/', {
  maxContentLength: 2000
}).then(function (res) {
  success = true;
}).catch(function (err) {
  error = err;
  failure = true;
});

setTimeout(function () {
  assert.equal(success, false, 'request should not succeed');
  assert.equal(failure, true, 'request should fail');
  assert.equal(error.message, 'maxContentLength size of 2000 exceeded');
  done();
}, 100);
```

**Comment by chinesedfan** [comment]
@yasuf I came up with a kind of explanation that it makes sure `done` will be called within 100ms, no matter whether `axios.get` is succeed or failed. Though you may think writing in a `then` next to `catch` can also achieve that, the current CI runs in about 2 mins, which means the time is not an emergency to consider.

**Comment by reviewher** [comment]
@chinesedfan the timeout is to give the test a little bit of time to run.  In that particular test, the `get` has to be performed and the `catch` block has to run (since that sets `failure = true`).  Running the checks synchronously or with timeout 0 is too early to guarantee the axios part has time to run.

The tests probably should use [`Promise#finally`](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Promise/finally):

```js
      axios.get('http://localhost:4444/', {
        maxContentLength: 2000
      }).then(function (res) {
        success = true;
      }).catch(function (err) {
        error = err;
        failure = true;
      }).finally(function () {
        assert.equal(success, false, 'request should not succeed');
        assert.equal(failure, true, 'request should fail');
        assert.equal(error.message, 'maxContentLength size of 2000 exceeded');
        done();
      });
```

The problem is browser compatibility.  For example, chrome 32+ support catch but finally requires chrome 63+

**Comment by chinesedfan** [comment]
> The tests probably should use Promise#finally

Exactly. And even a second `then` can act as `finally` without compatibility problems.

> it makes sure done will be called within 100ms

I think that's the biggest advantage. If someone breaks `axios` to be never resolved or rejected, we don't need wait the case to timeout.
