### ISSUE TITLE
post giving a unusual result

### ISSUE THREAD

**Issue by Y0geshsharma** [axios/axios#2746]
**Describe the issue**
i used the below code snippet but it just returned me the uid at backend.
**Example Code**
Code snippet to illustrate your question

```js
Axios
.post(url,fileobject)
.then()
.catch(error=>{
console.log(error)
_}_
"```

**Expected behavior, if applicable**
it should give complete file object in body
**Environment:**ˆ
 - Axios Version [e.g. 0.18.0]
 - OS: [e.g. iOS 12.1.0, OSX 10.13.4]
 - Browser [e.g. Chrome, Safari]
 - Browser Version [e.g. 22]
 - Additional Library Versions [e.g. React 16.7, React Native 0.58.0]

**Additional context/Screenshots**
Add any other context about the problem here. If applicable, add screenshots to help explain.

**Comment by chinesedfan** [comment]
It is a problem that the server can't response correctly, instead of an issue of axios. Please look for help in [stackoverflow](https://stackoverflow.com).

A quick solution is that checking **url** and **request headers** and comparing with other ways when you can get the right response. If you confirm that axios sends wrong url/headers, feel free to remind me to reopen.
