### ISSUE TITLE
Collect common strategies to solve issues and help for pulls

### ISSUE THREAD

**Issue by chinesedfan** [axios/axios#2747]
#### Background

Every week axios receives lots of new issues, and most of them are problems about how to get the expected response. Some of them are simple or duplicated, some are similar but with tricky differences, and some are complex without enough and clear information.

#### Possible actions

- [x] maintain a F.A.Q page or tutorial
  - something like https://github.com/axios/axios/issues/1195#issuecomment-579600201, to help users try to solve the issue by themselves first
  - or better website page with interactions or something I don't know
- [ ] update issue templates to collect enough information and ***reject offenders***
  - if users thought they really need to open an issue, make sure others can help them easier
  - if an issue didn't follow the template, or without potential suggestions for axios, it will be closed directly

It may be a little rude for users seeking for help. But please understand the differences between Github issues and stackoverflow questions. Issue readers are same developers like you. The best debugger is yourself, because only you know everything about the problem. You may not familiar with axios codes, but it is simple to read and easy to get familiar with.

#### About pulls

By the way, call help for more reviewers to handle the accumulated pull requests. Anyone in the community can leave comments for them. The main strategy is conservative and do not introduce bugs and too much breaking changes.

----

Everything above is my personal thoughts, which doesn't stand for axios official decisions. Forgive my non-native English, and I just wish this project can be better with the community's help.

**Comment by chinesedfan** [comment]
The first version of tutorial is done. See https://github.com/chinesedfan/You-Dont-Know-Axios.

**Comment by jonchurch** [comment]
Hey there! I'm curious about who maintains this project currently, and if the team would like help.

I saw some talk over in this somewhat hostilely titled issue https://github.com/axios/axios/issues/1965 and see on the people page of the repo @emilyemorehouse @mzabriskie @nickuraltsev @rubennorte listed as maintainers.

I wanted to possibly open up a dialogue with the maintainers, and point ya'll to the [nodejs/package-maintenance](https://github.com/nodejs/package-maintenance) working group, set up specifically to help aid packages of importance to the ecosystem, and support lovely people who create them. Perhaps @wesleytodd or @mhdawson can give a little more color about that particular group if they so desire. 

Perhaps you're already aware of the group, or have interacted with them in the past.

Personally I don't think I have the bandwidth to jump in currently, but I am a member of the Triage initiative that we have kickstarted over at https://github.com/expressjs/discussions/issues/92 which has been quite successful so far. 


## My goal here is to ask: What do you need? Do you want help from other projects?

From the looks of things, the project has lots of good information for [collaborators](https://github.com/axios/axios/blob/master/COLLABORATOR_GUIDE.md) and has a lot of activity happening, so you are much better off than many projects out there. 

Like Express (and specifically [multer](https://github.com/expressjs/multer)) I understand axios is a project that a lot of newer developers or people new to JS interact with, and combined with it's popularity, that means _lots_ of issues often from folks looking for basic support (which seems to be the point of this issue).

I'd suggest, if it's not already in place, creating an official Triage effort in order to empower folks who specifically want to contribute by answering questions, categorizing issues, reproducing bugs, etc. 

The [story from](https://github.com/axios/axios/issues/1965#issuecomment-580177276) @chinesedfan is quite a powerful one (and encapsulates the sort of positive effects we've started to see over at Express as well):

> Share a personal story and some news for users in this thread,
>
> I noticed the situation of axios like you guys in Feb 2019 and triaged about 30 issues+pulls.
Got no responses from the maintainers and felt a little disappointed. But still kept an eye on it.
Luckily, I was invited as a collaborator in Dec 2019. That started my issue killer time. Total issues have decreased from ~600 to less than 300 now.
I created a plan for the next release. See axios/axios/projects/4. I know there are still some problems in axios, but I hope we can fix those hottest first.
>
> I don't need your words to pay too much time on it, but would someone mind helping review those features when you are free, to make the next release better?

## Possible Next Steps

If this is something that interests the team, I think the [nodejs/package-maintenance](https://github.com/nodejs/package-maintenance) would be willing to talk about what they've learned so far from Express Triage, as well as other ways to help support the maintainers of this project. (Although I shouldn't speak for them, I'm not a member but that is my interpretation of their mission).

**Comment by wesleytodd** [comment]
While I don't have a ton of time to get involved on a new project, I can say that the triage effort and the plans from the Package Maintenance group have been super helpful for Express.  If you all are interested, we had a plan to use Express and MQTT as pilot projects, maybe we could add Axios to that list.  If maintainers from here want to reach out to me or the PM group, please go ahead and open an issue on the repo linked above by @jonchurch.

**Comment by ghinks** [comment]
@jasonsaayman can we assume things are ok and that this issue may be closed ( Package Maintenance Group were monitoring the situation but it looks like it is resolved now )

**Comment by jasonsaayman** [comment]
@ghinks Yeah I think we should be ok :) thanks for the help!

**Comment by chinesedfan** [comment]
Before [axios official docs repository](https://github.com/axios/axios-docs) was ready, I'd like keep this issue pinned to guide users to [chinesedfan/You-Dont-Know-Axios](https://github.com/chinesedfan/You-Dont-Know-Axios).

**Comment by jasonsaayman** [comment]
Agreed 😄
