### ISSUE TITLE
Error: Request failed with status code 500 in live server

### ISSUE THREAD

**Issue by mofizul21** [axios/axios#2757]
My website live link http://themepack.net/aaa/vuenote/notewithdb-search.php and code is here- https://github.com/mofizul21/vuenote

The website is working fine in localhost, but not in live server. How to I can solve the error?

**Comment by chinesedfan** [comment]
It is a problem that the server can't response correctly, instead of an issue of axios. Please look for help in [stackoverflow](https://stackoverflow.com).

A quick solution is that checking **url** and **request headers** and comparing with other ways when you can get the right response. If you confirm that axios sends wrong url/headers, feel free to remind me to reopen.
