### ISSUE TITLE
Allow cross origin access error

### ISSUE THREAD

**Issue by Ask149** [axios/axios#2776]
Hi, I'm am working on integrating a vuejs template in spring boot admin, and I was successful in integrating the same. As per the project requirement, I was required to make a GET request to a specific URL which is in the same service ( http://localhost:8080/... ). However, the url of the service varies as per the environment it is running on. But, when the GET call is requested through axios along with the headers for CORS ( Allow Cross Origin... ), I'm getting an error specifying Allow cross origin headers not present. To make sure I try every other alternatives, I've even added the required Bean in Spring Java Code for CorsConfiguration and also added properties for CORS in application.properties file. Could you help me with this issue? 

I have also reviewed the similar issues, but none of the solutions were helpful to me.

**Comment by chinesedfan** [comment]
Closed by the issue bot. Make sure you have followed the issue template.

We suggest users ask similar questions in [stackoverflow](https://stackoverflow.com), instead of Github issues. In fact, you can learn almost everything about CORS from [MDN](https://developer.mozilla.org/en-US/docs/Web/HTTP/CORS).
