### ISSUE TITLE
Unexpected memory usage

### ISSUE THREAD

**Issue by maurocchi** [axios/axios#2783]
**Describe the bug**

I observe a potential memory leak while posting data from a stream using Axios.

**To Reproduce**

Having a fake server (`nc -kl localhost 5000`), let's profile this simple script:
```shell
mprof run -C -T1 timeout 60 node test_axios.js < /dev/urandom
```
```js
// test_axios.js
const axios = require("axios");
const followRedirects = require("follow-redirects");
followRedirects.maxBodyLength = Number.MAX_SAFE_INTEGER;
axios.post("http://localhost:5000", process.stdin);
```
This produces the following chart:
![test_axios](https://user-images.githubusercontent.com/240925/75448641-e1a0b580-596b-11ea-920a-862376e568fe.png)

**Expected behavior**

Then consider the following equivalent axios-agnostic script:
```js
const http = require("http");
const options = {
  host: "localhost",
  port: "5000",
  path: "/",
  method: "POST"
};
const req = http.request(options, res => {});
process.stdin.pipe(req);
```

It produces:
![test_http](https://user-images.githubusercontent.com/240925/75448846-422ff280-596c-11ea-936d-05e2fdd1cc25.png)

Here the memory is properly garbaged.

**Environment:**
 - Axios Version [e.g. 0.19.2]
 - OS: Ubuntu 18.04.4
 - Profiling tool: [memory-profiler](https://pypi.org/project/memory-profiler/)

**Comment by chinesedfan** [comment]
See #1997 and related pull requests. Thanks for your reporting and hope someone can solve it.

**Comment by loic-couharde** [comment]
Hi, maybe the bug has something in common with the problem related in this [comment](https://github.com/visionmedia/supertest/issues/634#issuecomment-631069536) ?

**Comment by jasonsaayman** [comment]
@loic-couharde, thanks for a very helpful comment here. Seems the issue was with follow redirects, if we bump this to the latest version I think we should be ok.

**Comment by tnolet** [comment]
@maurocchi @jasonsaayman I can with 99% certainty confirm this. We upgraded a deamon worker yesterday that uses axios heavily. Since then, we have a memory leak with the classic saw pattern.

![image](https://user-images.githubusercontent.com/3802923/87525762-3da17780-c68a-11ea-8a72-45c78fdfdf8e.png)

**Comment by maurocchi** [comment]
@tnolet I have just run the above test again using axios 0.20.0-0.
Unfortunately the outcome is the same, so I can't confirm the fix.

**Comment by westhom** [comment]
@maurocchi I'm not sure the code you provided is demonstrating a memory leak. You set follow-redirect's max buffer to ~9000 terabytes and then make a single request that writes random data at a high rate for 60s. follow-redirects buffers the request data in memory in case it needs to be replayed on the next 3xx. Growing memory usage for a never-ending request is what I would expect. Comparing to native `http` module isn't helpful because they don't share functionality.

The question to ask is, over time after multiple large requests, are objects left in memory that are un-GCable? If not, are we seeing undesirable GC behavior and is there a way to prevent that?

Based on @tnolet's graph, I think it's more likely undesirable GC behavior and not a leak, meaning eventually the GC kicks into gear and memory is freed.

Here's a test I made that posts 20GB over 20~ requests. Memory gets high because the requests allocate 1GB each, but eventually settles to 3MB~.

```js
const axios = require("axios").default;
const randomBytes = require('crypto').randomBytes;

const followRedirects = require("follow-redirects");
followRedirects.maxBodyLength = Number.MAX_SAFE_INTEGER;

const sendAbout = 1024 * 1024 * 1000 * 20; // 20GB
let totalSent = 0;

(async function(){
  while(totalSent < sendAbout){
    try {
      const opts = {
        method: 'post',
        url: "http://localhost:8585/test-data",
        headers: {
          'content-type': 'application/octet-stream'
        },
        data: randomBytes(1024 * 1024 * (Math.random() * 100 + 900))
      };

      console.log(`sending: ${opts.data.byteLength} bytes`);

      const res = await axios(opts);

      totalSent += opts.data.byteLength;
      console.log(`progress: ${((totalSent / sendAbout) * 100).toFixed(2)}%`);
    }
    catch(err){
      console.log(err.message);
    }
  }

  console.log("done");

  // force new execution context
  setInterval(function(){
    console.log(new Date());
  }, 10000);
})();
```

Test server:
```js
const express = require('express');
const rawParser = require('body-parser').raw;
const app = express();

// dead end for data
app.post('/test-data', rawParser({limit: '2GB'}), (req, res) => {
  console.log(`parsed: ${req.body.length} bytes`);
  res.send();
});

app.listen(8585, () => {
  console.log("server listening");
});
```

<img width="197" alt="Screen Shot 2020-07-20 at 8 20 57 AM" src="https://user-images.githubusercontent.com/921720/87937341-8b3f2b00-ca62-11ea-8c6c-9779ba3bc02f.png">

There may be a trick to get the GC to clean up sooner, but it tries to balance large memory allocations, run time, processor usage, etc.

**Comment by maurocchi** [comment]
So what I assumed to be a memory leak was the expected behavior of follow-redirects buffering mechanisms!

In fact this problem disappears by disabling the following of redirects:
```
const axios = require("axios");
axios.post("http://localhost:5000", process.stdin, { maxRedirects: 0 });
```

Thanks @westhom!

**Comment by tnolet** [comment]
@jasonsaayman ignore my contribution. This was the ‘debug’ library of all things!

**Comment by marlonklc** [comment]
> So what I assumed to be a memory leak was the expected behavior of follow-redirects buffering mechanisms!
> 
> In fact this problem disappears by disabling the following of redirects:
> 
> ```
> const axios = require("axios");
> axios.post("http://localhost:5000", process.stdin, { maxRedirects: 0 });
> ```
> 
> Thanks @westhom!

Works for me a problem to high usage of memory. Thanks @westhom @enerdgumen  !
