### ISSUE TITLE
Wrong version of follow-redirects used

### ISSUE THREAD

**Issue by aseprano** [axios/axios#2818]
Your package.json on github requires the follow-redirects: ^1.10.0 library, whereas the package.json in the npm bundle (https://registry.npmjs.org/axios/-/axios-0.19.2.tgz) refers to the older 1.5.10 version of follow-redirects.
Can you fix this depencency issue since the latest version of follow-redirects has a better redirect management, pls?

**Comment by chinesedfan** [comment]
It is normal that some changes have been made in the master branch, but a new version hasn't been released. I can only say be patience because I have no npm publish permissions.

If you were eager to use it, a possible workaround is making your package.json points to the special git commit temporarily (check npm docs to learn how). You can also keep an eye on #2812 to share your advises.

**Comment by aseprano** [comment]
ok but current version of follow-redirects is 1.10, whereas you refer to 1.5 that is way older. Hence this is something that has been going on for a while, pls update your npm package. You have no privileges, but somebody else in the team can.

**Comment by chinesedfan** [comment]
This problem should have been fixed.
