### ISSUE TITLE
Request works, but no response 

### ISSUE THREAD

**Issue by pfundstein** [axios/axios#2839]
Hello,

I hope this is the right place to post this. I have the following issue:

My backend is only a simple PHP script, that returns a JSON like `{ "success": true }` and when I call my endpoint with Postman this absolutely works fine.

From my Vue app using axios it works also (it creates the entry in the database), but no response shows up: Not in the console and not even in the developer tools of Chrome (Network tab, the response is just empty).

JavaScript client side code:
`const formData = new FormData();
formData.append("something", "ABC");
Vue.axios
        .post(endpoint, formData)
        .then(response => {
          console.log(response);
        });`

Now the strange thin is, when I not return a JSON from the server, but instead just echo any string, then I see a response! Of course the response header is set to `header('Content-Type: application/json');`

I have no idea what's going on, anyone here has an idea?

It's only about the response that is just not there, but the backend just works. With axios it sends the parameters successfully (as FormData) and the response should be a JSON... the backend sends this out correctly.

**Comment by chinesedfan** [comment]
It is a problem that the server can't response correctly, instead of an issue of axios. Please look for help in [stackoverflow](https://stackoverflow.com).

A quick solution is that checking **url** and **request headers** and comparing with other ways when you can get the right response. If you confirm that axios sends wrong url/headers, feel free to remind me to reopen.
