### ISSUE TITLE
axios post works on android emulator but not on actual android device

### ISSUE THREAD

**Issue by tae-at-speer** [axios/axios#2867]
I'm using axios for react native and post call works fine on postman but I was getting `[Error: Network Error]` 
so I've looked into this issue and tried to resolve it by adding `android:usesCleartextTraffic="true" ` to /android/app/src/main/AndroidManifest.xml
and it post call was successful on my emulator but it is keep raising  `[Error: Network Error]`  on my actual device (LG G6).
I've tried to reboot the phone, delete and reinstall but keeps showing that.
I'm using server domain not localhost.
Is there a way to resolve this?

**Comment by chinesedfan** [comment]
Better to open an issue to React Native.

If it is a problem that the server can't response correctly, instead of an issue of axios. Please look for help in [stackoverflow](https://stackoverflow.com).

A quick solution is that checking **url** and **request headers** and comparing with other ways when you can get the right response. If you confirm that axios sends wrong url/headers, feel free to remind me to reopen.

**Comment by tae-at-speer** [comment]
This issue was fixes after I updated my device to Android 8. My device was Android 7 when I faced this issue.

**Comment by victorwpbastos** [comment]
Solution: https://github.com/facebook/react-native/issues/28551#issuecomment-624347067
