### ISSUE TITLE
Invalid HTML String returned

### ISSUE THREAD

**Issue by stacksapien** [axios/axios#2871]
For some URL - e.g : `https://nozakconsulting.com/work-for-us/`  Axios GET request sends invalid HTML string.

`axios.get("https://nozakconsulting.com/work-for-us/", {})
.then((response) => {
    console.log(response.data);
})
.catch(err => {
    console.log(err);
})
`
[logs.txt](https://github.com/axios/axios/files/4421810/logs.txt)

**Comment by chinesedfan** [comment]
It is a problem that the server can't response correctly, instead of an issue of axios. Please look for help in [stackoverflow](https://stackoverflow.com).

A quick solution is that checking **url** and **request headers** and comparing with other ways when you can get the right response. If you confirm that axios sends wrong url/headers, feel free to remind me to reopen.
