### ISSUE TITLE
XHR failed loading: POST

### ISSUE THREAD

**Issue by vindecodex** [axios/axios#2881]
**Describe the issue**
Cannot proceed to `.then` and `.catch` after `axios.post` but still data was sent on my database.

**Example Code**
```js
axios.post('/api/v1/accounts', this.registerInput)
.then(res =>  console.log(res))
.catch(err => console.log(err))
```

**Expected behavior, if applicable**
must proceed to console.log either in `.then` or `.catch`

**Environment:**
 - Axios Version [0.19.2]
 - OS: [OSX 10.15.2]
 - Browser [Chrome]
 - Browser Version [80.0.3987.163 ]
 - Additional Library Versions [Vue-cli 4.2.3]

**Additional context/Screenshots**
![image](https://user-images.githubusercontent.com/50949760/78746104-94672900-7998-11ea-8ee0-6ecc857f4d63.png)

**Comment by chinesedfan** [comment]
It is a problem that the server can't response correctly, instead of an issue of axios. Please look for help in [stackoverflow](https://stackoverflow.com).

A quick solution is that checking **url** and **request headers** and comparing with other ways when you can get the right response. If you confirm that axios sends wrong url/headers, feel free to remind me to reopen.
