### ISSUE TITLE
Always getting Error: Request aborted.

### ISSUE THREAD

**Issue by viveksinghmehta** [axios/axios#2883]
**Describe the issue**
My axios request always returns
Error: "Request aborted"
    exports https://unpkg.com/axios/dist/axios.min.js:2
    onabort https://unpkg.com/axios/dist/axios.min.js:2

**Example Code**
Code snippet to illustrate your question

```js
axios({
        url: 'https://jsonplaceholder.typicode.com/todos/1',
        method: 'get'
    })
        .then(function (response) {
            console.log(response);
        })
        .catch(function (error) {
            console.log(error);
        });
```

**Expected behavior, if applicable**
I should get the json response form the server.

**Environment:**
 - Axios Version [e.g. 0.18.0]
 - OS: [e.g. iOS 12.1.0, OSX 10.13.4]
 - Browser [e.g. Chrome, Safari]
 - Browser Version [e.g. 22]
 - Additional Library Versions [e.g. React 16.7, React Native 0.58.0]

**Additional context/Screenshots**
Add any other context about the problem here. If applicable, add screenshots to help explain.

**Comment by chinesedfan** [comment]
It is a problem that the server can't response correctly, instead of an issue of axios. Please look for help in [stackoverflow](https://stackoverflow.com).

A quick solution is that checking **url** and **request headers** and comparing with other ways when you can get the right response. If you confirm that axios sends wrong url/headers, feel free to remind me to reopen.
