### ISSUE TITLE
Request failed with 403 response while making a get request.

### ISSUE THREAD

**Issue by UsamaDanish** [axios/axios#2897]
I have tried to get data from my server to another but every time it responds with 403 error. it works well on the localhost but always gives error whenever I get this from live.

const result = await axios.get(url);

**Comment by sultan-arshi** [comment]
+1

**Comment by aligoren** [comment]
Are Axios and your backend server run on different locations? You may be getting a CORS error.

**Comment by chinesedfan** [comment]
It is a problem that the server can't response correctly, instead of an issue of axios. Please look for help in [stackoverflow](https://stackoverflow.com).

A quick solution is that checking **url** and **request headers** and comparing with other ways when you can get the right response. If you confirm that axios sends wrong url/headers, feel free to remind me to reopen.

**Comment by UsamaDanish** [comment]
> Are Axios and your backend server run on different locations? You may be getting a CORS error.

no! axios and backend server are on same location.

**Comment by UsamaDanish** [comment]
> It is a problem that the server can't response correctly, instead of an issue of axios. Please look for help in [stackoverflow](https://stackoverflow.com).
> 
> A quick solution is that checking **url** and **request headers** and comparing with other ways when you can get the right response. If you confirm that axios sends wrong url/headers, feel free to remind me to reopen.

yes I have been digging the StackOverflow but couldn't find yet. hearders in browsers and in axios.get request has been compared and they are same.
