### ISSUE TITLE
Axios POST

### ISSUE THREAD

**Issue by thomasoren** [axios/axios#2921]
I'm trying to submit a form with title, description, price and image. My only problem is that only title and image is posted. I also get this error message: The JSON value could not be converted to System.Int32

This is my code: 
`export default {
    name: "DishForm",
    data(){
        return {
            newDish: { name: "", description: "", price: "", imageSrc: "" },
            file: null,
            postStatus: ""
        }
    },
    methods: {
        postDish(){
            this.newDish.imageSrc = this.file.name;

            let data = new FormData();
            data.append("file", this.file);

            axios.post("https://localhost:5001/mydish", this.newDish)
                .then( result => {
                    this.postStatus = JSON.stringify( result.data );
                    console.log( result.data );
                    this.newDish.price = "";
                    this.newDish.description = "";

                    axios({
                        method: "POST",
                        url: "https://localhost:5001/mydishadmin/UploadImage",
                        data: data,
                        config: { headers: { 'Content-Type': 'multipart/form-data' } }       
                    })

                } )
        }
    }
}`

**Comment by chinesedfan** [comment]
It is a problem that the server can't response correctly, instead of an issue of axios. Please look for help in [stackoverflow](https://stackoverflow.com).

A quick solution is that checking **url** and **request headers** and comparing with other ways when you can get the right response. If you confirm that axios sends wrong url/headers, feel free to remind me to reopen.
