### ISSUE TITLE
Http error from "handleStreamEnd" function

### ISSUE THREAD

**Issue by markb-trustifi** [axios/axios#2963]
**Describe the bug**
I get this error after some unknown request:

RangeError [ERR_INVALID_OPT_VALUE]: The value \"2193491065\" is invalid for option \"size\"\n at Function.allocUnsafe (buffer.js:358:3)\n at Function.concat (buffer.js:543:25)\n at IncomingMessage.handleStreamEnd (**/app/node_modules/axios/lib/adapters/http.js:230:37**)\n at IncomingMessage.emit (events.js:228:7)\n at IncomingMessage.EventEmitter.emit (domain.js:475:20)\n at endReadableNT (_stream_readable.js:1185:12)\n at processTicksAndRejections (internal/process/task_queues.js:81:21)

**To Reproduce**
The URL is unknown, cannot reproduce.

**Environment:**
 - Axios Version: 0.19.2
 - OS: OSX 10.14.6
 - NodeJs: 12.15.0

**Comment by chinesedfan** [comment]
It is a problem that the server can't response correctly, instead of an issue of axios. Please look for help in [stackoverflow](https://stackoverflow.com).

A quick solution is that checking **url** and **request headers** and comparing with other ways when you can get the right response. If you confirm that axios sends wrong url/headers, feel free to remind me to reopen.
