### ISSUE TITLE
need help to convert to axios

### ISSUE THREAD

**Issue by enfratec2** [axios/axios#2971]
i am 3 days trying to make this work! and I couldn't even get close! could any one help me to convert this python scraper to javascript using axes

`import requests
import time

s = requests.Session()
s.headers.update({'Content-Type': 'application/x-www-form-urlencoded',
                  'Accept': 'application/json',
                  'authorization': 'Basic Y3VycmVuY3lfd2lkZ2V0OmN1cnJlbmN5X3dpZGdldA=='
                  })

url = "https://widget.sentryd.com/widget/sentry/api/Pricing"
data = {'Type': 'Pricing',
        'Products': 'EUR/GBP',
        'POSTAccessCode': 'sentryPricingApi',
        'POSTAccessPassword': 'sentrypricingapi_213',
        'timestamp': str(round(time.time() * 1000))}

r = s.post(url, data=data)
print(r.json())`

**Comment by mustaphee** [comment]
`
var axios = require('axios');

var url = "https://widget.sentryd.com/widget/sentry/api/Pricing"
var headers = {'Content-Type': 'application/x-www-form-urlencoded',
                         Accept': 'application/json', 'authorization': 'Basic 
                         Y3VycmVuY3lfd2lkZ2V0OmN1cnJlbmN5X3dpZGdldA==' 
                        }
var data = { 'Type': 'Pricing', 'Products': 'EUR/GBP', 'POSTAccessCode': 'sentryPricingApi',
                   'POSTAccessPassword': 'sentrypricingapi_213',
                   'timestamp': new Date().getTime()
                 }

axios.post(url, data, {headers: headers})
.then(response => {
 response.data // Do whatever you like with your data. It is JSON formatted already 
} )
.catch(err => err)

If you are on a browser environment, instead of 'requiring axios' in the first line,  you will import axios using the usual <script src>, then enclose the above code in a script tag and use as usual 
`

**Comment by chinesedfan** [comment]
Another thing should be mentioned is that encoding `data` correctly.

See,
- https://github.com/axios/axios#using-applicationx-www-form-urlencoded-format
- https://github.com/chinesedfan/You-Dont-Know-Axios#submit-data-successfully.
