### ISSUE TITLE
Issue using Self Signed Cert

### ISSUE THREAD

**Issue by liamkeily** [axios/axios#3005]
My api is using a self signed cert which works fine in the browser. I am trying to use axios to connect to this api from a test.

I'm getting the following error `Error: Error: unable to verify the first certificate`

I've tried 

```
const axiosInstance = axios.create({
	httpsAgent: new https.Agent({
		ca: fs.readFileSync('/Users/liam/Projects/Desktop/ca.crt')
	})
});

const res = await axiosInstance.get('https://dev.domain.com/users');
```

I've tried

```
const axiosInstance = axios.create({
	httpsAgent: new https.Agent({
		rejectUnauthorized: false
	})
});

const res = await axiosInstance.get('https://dev.domain.com/users');
```

Both give the same error :( 

Any ideas?

**Comment by DylanSp** [comment]
I'm having the same problem. The cert is a self-signed cert from IIS Express; it's trusted by Chrome without issues. I've tried the above, as well as setting `NODE_EXTRA_CA_CERTS=/path/to/exported_cert.pem`.

**Comment by cipher-code** [comment]
Self signed certs can work but they can be tricky to configure both in the browser and node. Its possible to do it in node by monkey patching TLS but I wouldn't recommend that method.

If you have your API running locally, one easy way around this is to use expose.sh. You can run `expose 80` then it'll generate a public HTTPs URL which will forward to localhost that you can use for local development, like `https://a8kc.expose.sh`. I've written a step by step guide [here](https://expose.sh/blog/2020/07/11/local-https-testing?utm_source=githubIssues).

**Comment by shangchengxiang** [comment]
I do some changes in my codes because I want to use SSL .
Just like this :
req.httpsAgent = new https.Agent({
ca: fs.readFileSync(filepath)
});
file is endwith .pem or .p7b
filepath is good ,it's can read data from CAFile. axios.req also can get data, I make a breakpoint to confirm it .
But it's look like does'nt working. I change the data as my mind , but it's also can get the response . So data can be change as my wish , How can I verify my CAFile ? In my PC , it look like does'nt working. But in my team others PC can verify the CAFile is unable , them can't get the response .
I don't know if I'm going to configure something on the server.

**Comment by shangchengxiang** [comment]
There was an error when I was using the certificate.
UNABLE_TO_VERIFY_LEAF_SIGNATURE
How to fix it ?

**Comment by bwackwat** [comment]
I imported an expired self signed cert into Chrome as a Root CA Cert. Pretty sad. It worked.

**Comment by jasonsaayman** [comment]
Please see #3304 if you can give us a full example we can have a look but for now I am closing this issue.
