### ISSUE TITLE
Issued on an old Android is clipped

### ISSUE THREAD

**Issue by valery-lavrik** [axios/axios#3025]
Android 4.2.2
react-native  "axios": "^0.19.2",

The problem is the answer axios.
Sometimes the answer is cropped to 44 characters. I looked at the full answer and found this:
![image](https://user-images.githubusercontent.com/8047999/84667219-b8ac2c80-af2a-11ea-8724-d26af7331b25.png)
the text is just cropped!
I do not understand why

Here is an example of the entire issue object - https://pastebin.com/urjrMcVG

**Comment by chinesedfan** [comment]
It is a problem that the server can't response correctly, instead of an issue of axios.

A quick solution is that checking **url** and **request headers** and comparing with other ways when you can get the right response. If you confirm that axios sends wrong url/headers, feel free to remind me to reopen.
