### ISSUE TITLE
Priority

### ISSUE THREAD

**Issue by Manikanta-20** [axios/axios#3132]
#### Is your feature request related to a problem? Please describe.
N/A
#### Describe the solution you'd like
Add parameter key(importance /priority):value(high/medium/low).
It should work for all protocol of( 'http'/ 'https'/ 'http/2' ).

#### Describe alternatives you've considered
n/a.
#### Additional context
https://developer.mozilla.org/en-US/docs/Mozilla/Firefox/Releases/1.5/Changing_the_priority_of_HTTP_requests
https://developers.google.com/web/updates/2019/02/priority-hints

**Comment by sourabhv-toptal** [comment]
So what happened to this feature request? Was this implemented? Did you find a workaround?

**Comment by grindpride** [comment]
Any news?

**Comment by AyushiBShah** [comment]
Any update on this? @jasonsaayman

**Comment by rahulnag** [comment]
Similar ask,
i am also looking for something similar.

Any update Axios Team ?

**Comment by leefsmp** [comment]
This was closed as completed… would you mind giving some more hints pls, couldn’t find anything related in the doc so far. Thanks 🙏🏻

**Comment by Usnul** [comment]
Had a look through the code, really new to `axios`, couldn't find exact point where `fetch`(or equivalent) is done. The documentation for `Request` config doesn't include `priority` as of yet either:
https://axios-http.com/docs/req_config

can someone who knows a bit of background on this issue shed some light on the current status for us?

**Comment by BliemHax** [comment]
you must use the fetch api instead of axios. no anwser for this question because this feature is not avaliable yet!!
你必须使用fetch api 而不是axios。这个问题没办法解答因为这个功能没写。

I am using electron, and many requests will block a more important request in the rendering process. Since I use axios, now I can only choose to use fetch api instead of axios (but I will use a simpler method: put the important axios requests run in the main process)
我正在使用electron，许多的请求在渲染进程中会阻塞某个更加重要的请求，由于我使用axios，现在我只能选择使用fetch api来替代axios（不过我会使用更简单的方法：将重要的axios请求在主进程中运行）

I'm concerned about axios' project maintenance activity!
我对axios的项目维护活跃度感到担忧！

-- translated by google translator from chinese to english.

**Comment by janswist** [comment]
@Manikanta-20 any news? `Closed as completed` but no one can find it

**Comment by ermite1408** [comment]
Found a solution to prioritize request:

`axios.post(url, data, { adapter: 'fetch', fetchOptions: { priority: 'high' } });`
