### ISSUE TITLE
409 error not caught

### ISSUE THREAD

**Issue by OriginLive** [axios/axios#3340]
#### Describe the bug
Just updated axios to latest version and it seems it's not catching errors as it used to on v19.2

#### To Reproduce

try catch any response with 409,

with v20 it passes through, here's an example of returned value (as a value, not as an error)

`{error_id: "568347a4-594d-4be1-8f76-a67994237499", statusCode: 409, error_code: "HTTP_ERROR_PLEASE_WAIT_DELAY", message: "Please try again a little later.", uri: "/v1/resend/a659d785-cf40-4b99-9598-b42409ad88fb"}
error_code: "HTTP_ERROR_PLEASE_WAIT_DELAY"
error_id: "568347a4-594d-4be1-8f76-a67994237499"
message: "Please try again a little later."
statusCode: 409
uri: "/v1/resend/a659d785-cf40-4b99-9598-b42409ad88fb"`

#### Expected behavior
It should have caught it in try/catch clause.

#### Environment
 - Axios Version [0.20.0]
 - Adapter [XHR/HTTP]
 - Browser [all]
 - OS: [all]
 - Additional Library Versions [React 16.7]

**Comment by chinesedfan** [comment]
Can you paste a reproducible example? Including the sample server which returns 409 http status.

**Comment by Brianzchen** [comment]
I'm experiencing same issue, though I'm on v0.19.2 and haven't touched this lib since I added it. My catch statement doesn't contain what I expect when error code is 409. I'm expecting an object from the backend so that I can print errors to users, but instead I'm just getting an error trace when I log error in the catch statement.

<img width="536" alt="Screen Shot 2020-11-16 at 9 54 44 am" src="https://user-images.githubusercontent.com/12436524/99199275-01c21e80-27f2-11eb-87cf-af9c92a38f55.png">
<img width="776" alt="Screen Shot 2020-11-16 at 9 56 01 am" src="https://user-images.githubusercontent.com/12436524/99199276-04247880-27f2-11eb-8a1c-51c2a0d5753e.png">
