### ISSUE TITLE
How do you get the response's body of a failed request?

### ISSUE THREAD

**Issue by zachariapopcorn** [axios/axios#3535]
#### Describe the issue
Question basically is the title, how do you get the response's body of a request that failed with a status code 403, 400, 401, etc

#### Example Code
--

#### Expected behavior, if applicable
--

#### Environment
 - Axios Version: 0.21.0
 - Node.js Version: 12.6.0
 - OS: Windows 10 20H2

#### Additional context/Screenshots
--

**Comment by michalskula** [comment]
You can do it in the interceptors, or .catch method, that depends on your use case, what is it?

**Comment by zachariapopcorn** [comment]
I use try/catch, though when I did console.log(request.data) it turned up as undefined

**Comment by zachariapopcorn** [comment]
Uhh hello?

**Comment by Grismar** [comment]
When using `axios.get(< some params >).catch(e => { console.log(e); }`, I get an error with a `.response` that I can access (as well as the status, like 404), but using `axios(method: 'GET', <some params>).catch(e => { console.log(e); }`, the response is no longer on the error and it appears to be just the error text. I doubt that's by design? Shouldn't the error objects be identical in either case?

**Comment by zachariapopcorn** [comment]
Hello?

**Comment by iranaahsanali** [comment]
Facing same issues!

**Comment by jasonsaayman** [comment]
if you are facing undefined then the request itself did not have any body/response. also if you are unable to catch are you certain you are actually passing the http status code? if you could can you please drop a reproducible example?
