### ISSUE TITLE
User-Agent header not recognized correctly

### ISSUE THREAD

**Issue by vkana** [axios/axios#3625]
#### Describe the issue
I have this call working from curl fine, but not using axios in a nodejs file. I read this has been fixed fixed in https://github.com/axios/axios/issues/69, but happening again. Can you please check?
I have full details in my stackoverflow question. https://stackoverflow.com/questions/66036078/axios-is-replacing-user-agent-string?noredirect=1#comment116756815_66036078

Thanks!
#### Example Code
Code snippet to illustrate your question

```
https://stackoverflow.com/questions/66036078/axios-is-replacing-user-agent-string
```

#### Environment
 - Axios Version 0.21.1
 - Adapter [e.g. XHR/HTTP]
 - Browser [e.g. Chrome, Safari]
 - Browser Version [e.g. 22]
 - Node.js Version 0.21.1
 - OS: Windows 10
 - Additional Library Versions [e.g. React 16.7, React Native 0.58.0]

#### Additional context/Screenshots
Add any other context about the problem here. If applicable, add screenshots to help explain.

**Comment by chinesedfan** [comment]
I have to admit that it is annoying. Even by curl, it will return 412 and a bad html with title "Verify Your Identity" at the first time, which is the same with axios if you set header "accept: null".

So the best pratice is checking the server codes and find out why it returns 412. You can also test with Node.js native http module or other clients like request or node-fetch. At least, I can promise that axios sends the correct headers with User-Agent, because I saw it.
