### ISSUE TITLE
How to get axios to include X-XSRF-TOKEN header on cross domain requests

### ISSUE THREAD

**Issue by Wendelstein7** [axios/axios#4094]
### I can not get axios to provide the `X-XSRF-TOKEN` header in cross-domain requests.

I am developing a web-application. The back-end is powered by Laravel with sanctum providing an authentication platform. The front-end is a seperate Vue-project. Both of these projects will "run" on different subdomains, e.g. `api.domain.tld` and `app.domain.tld`. I am using axios within the Vue project to het anti xsrf tokens via cookies, after which axios automatically includes the xsrf token in the specified header for subsequent requests.

This all works fine in a local test environment where both the api and the app operate on the same domain (`localhost`) as also [stated on the Laravel documentation](https://laravel.com/docs/8.x/csrf). But this breaks when moving to a production or staging environment where the front-end and back-end operate on different subdomains.

How can I instruct axios to include the `X-XSRF-TOKEN` header in cross-domain requests aswell?

#### Environment
 - Latest axios via npm 0.21.4
 - _Other packages (Laravel, Vue, etc) should be irrelevant._

### Flow
1. Axios (JavaScript executing in a browser environment "from" **app**.domain.tld) requests a xsrf token from `api.domain.tld/sanctum/csrf-cookie` via a HEAD request.
2. Laravel Sanctum returns a response with a `set-cookie` header containing a new xsrf token.
2. Axios requests an xsrf protected action (such as a user registration request) from `api.domain.tld/api/register` via a POST request. **This request should now contain the `X-XSRF-TOKEN` header, but it does not. It only does under a localhost testing environment.**

**Comment by Wendelstein7** [comment]
Update: A basic solution was to set the cookie domain to `.domain.tld` (note the leading dot) to allow the cookie to be accessed by all subdomains.

**Comment by lbragile** [comment]
@Wendelstein7 Thank you for adding the update as it pointed me in the right direction.

However, in my case where I have `cookie: false` (as I am using `express-session` with ExpressJS), this was not enough to get things working.

I had to also adjust the cookie settings in the response so that it also worked for subdomains.

The change was:
```ts
res.cookie("XSRF-TOKEN", req.csrfToken())

// becomes ↓

res.cookie("XSRF-TOKEN", req.csrfToken(), {
    domain: 'example.com',
    secure: true
})
```

### Key Points
1. It is important **not** to set `httpOnly` in the response cookie as axios seems to depend on `document.cookie` to set the token header value. 
2. "XSRF-TOKEN" should match whatever your [axios instance configuration](https://axios-http.com/docs/req_config) sets `xsrfCookieName` to.
3. From what I can tell by reading the [documentation](https://developer.mozilla.org/en-US/docs/Web/HTTP/Cookies#domain_attribute), there is no need to prefix the domain with `.`
4. Make sure to clear storage from server (to remove cookies) before re-checking client side behavior since response might use outdated cookies.

**Comment by Deniz073** [comment]
> Update: A basic solution was to set the cookie domain to `.domain.tld` (note the leading dot) to allow the cookie to be accessed by all subdomains. Axios now automatically seems to include the XSRF header again.

Hello i am running into the same issue, but i also have the problem that when the server returns the set_cookie the cookie is not set on the client nextjs application. Also no xcsrf header for subsequent requests to the api. The api and client run on 2 different domains (so no subdomain). I also posted my question on laracast with some extra detail: https://laracasts.com/discuss/channels/requests/cross-domain-requests

Do you possibly know how i can fix this?

**Comment by dangnhdev** [comment]
Since this question related to Laravel. I propose the following solution to address the issue:
New Laravel project already provides the middleware **App\Http\Middleware\VerifyCsrfToken** class which extends the default internal **Illuminate\Foundation\Http\Middleware\VerifyCsrfToken**. The default behavior of this class is to always check for the X-XSRF-TOKEN header. You can check the function source [here](https://github.com/jimrubenstein/laravel-framework/blob/f7ba54c132319631163ac0c98101da0a3b16c3ca/src/Illuminate/Foundation/Http/Middleware/VerifyCsrfToken.php#L134C18-L134C18)

 You can extend its behavior, for example:

**- To always check for XSRF token:**

```php
//file: app/Http/Middleware/VerifyCsrfToken.php
<?php

namespace App\Http\Middleware;

use Illuminate\Foundation\Http\Middleware\VerifyCsrfToken as Middleware;

class VerifyCsrfToken extends Middleware
{
    /**
     * The URIs that should be excluded from CSRF verification.
     *
     * @var array<int, string>
     */
    protected $except = [
        //
    ];
   //add our custom getTokenFromRequest function
    protected function getTokenFromRequest($request)
    {
        //keep default behavior, use parent method first
        $token = parent::getTokenFromRequest($request);
        //if token not found we will get token from cookie
        if (!$token){
            $token = $request->cookie('XSRF-TOKEN');
        }
        return $token;
    }
}
```

**- Only check XSRF token if a specific header is provided:**

```php
    protected function getTokenFromRequest($request)
    {
        $token = parent::getTokenFromRequest($request);
        //X-NEED-AUTH is your custom header
        if (!$token && $request->header('X-NEED-AUTH') === 'true'){
            $token = $request->cookie('XSRF-TOKEN');
        }
        return $token;
    }
```

On the client side, the axios instance that you want to send requests to the Laravel backend can be pre-configured to include your custom headers. By doing so, the cookie can be HTTP-only, and your request is secured safely.
