### ISSUE TITLE
Usage of AbortController ist breaking for setup without DOM Library

### ISSUE THREAD

**Issue by smirowstanitzok** [axios/axios#4124]
#### Describe the bug
Axios has been using the `AbortController` from the DOM library since version 0.22.0 (# 3305). Since then, the DOM library has to be stored in tsconfig.json. Without DOM the new version is breaking for our setup and can no longer be used.

#### To Reproduce
Use `axios.get()` without DOM Library. To reproduce change `tsconfig.json` to eg.:

```
...
    "lib": ["ES2020"],
...
```

#### Expected behavior
axios should work without DOM. Maybe there is an alternative for `AbortController`?

#### Environment
 - Axios Version 0.22.0
 - Adapter http
 - Browser none
 - Node.js Version 14.18.0
 - OS: macOS 11.6

#### Additional context/Screenshots
Given Exception:

```
> @smirowstanitzok/trendytag-sdk@3.1.2 build /home/runner/work/trendytag-sdk/trendytag-sdk
> tsc

Error: node_modules/axios/index.d.ts(81,12): error TS2304: Cannot find name 'AbortSignal'.
Error: src/index.ts(189,13): error TS2322: Type 'unknown' is not assignable to type 'AxiosResponse<ContactFormResponse> | undefined'.
  Type 'unknown' is not assignable to type 'AxiosResponse<ContactFormResponse>'.
Error: src/index.ts(189,88): error TS2345: Argument of type 'ContactForm' is not assignable to parameter of type 'ContactFormResponse'.
  Property 'messageId' is missing in type 'ContactForm' but required in type 'ContactFormResponse'.
npm ERR! code ELIFECYCLE
npm ERR! errno 2
npm ERR! @smirowstanitzok/trendytag-sdk@3.1.2 build: `tsc`
npm ERR! Exit status 2
npm ERR! 
npm ERR! Failed at the @smirowstanitzok/trendytag-sdk@3.1.2 build script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/runner/.npm/_logs/2021-10-01T08_27_20_612Z-debug.log
Error: Process completed with exit code 2.
```

**Comment by DigitalBrainJS** [comment]
I guess importing typings from `node-abort-controller` polyfill for nodejs environment will fix this.

**Comment by mark-night** [comment]
@DigitalBrainJS Thanks for looking into this quickly and helped to setup the sandbox.

So I tested it for a while and finally realized that it was the `transformResponse` in instance config that caused the issue. 
If you take a look at this [sandbox](https://codesandbox.io/s/axios-issues-post-test-forked-d527x?file=/src/index.js) forked off yours, I have `transformResponse` set in the instance config, it does nothing and just return data received. With that set, the `data` destructed from `response` is of type `string`, and has to be manually parsed as json.

*This is not the case back in v0.21.1.*

According to documentation, 
>// `transformResponse` allows changes to the response data to be made before
>// it is passed to then/catch

It indeed makes sense if `data` should be manually parsed here if developer is to manipulate it here, however, I personally prefer more the way v0.21.1 deals this (`data` is pre-parsed before passed into `transformResponse` as argument):
- It's more conventional.
- Manipulating `data` is not always the logic in `transformResponse`, e.g., developer might just want to log something or simply (conditionally) do something with the `data`, although the config field is named as "transform", it does not limit usages not transforming...

At least we know now where the issue is. I'd recommend making it the same as before, i.e. with `transformResponse` configured, `data` is still parsed before passed down. Or, if there are good reasons for Axios to take current approach (not parsing if configured), it'd be better if an option can be provided for developer to choose whether to parse `data` or not so it's clear to developer what should be done, besides, it is a breaking change that should be mentioned. 

Other issues regarding typing changes since v0.22.0 is pretty obvious, and are mentioned in other issue reports as well, so I guess there is no need to setup sandboxes to demonstrate them.

Thanks. Great library by the way!

**Comment by jan-molak** [comment]
In the past, whenever Axios has accidentally started to rely on DOM-only types, the preferred fix was to revert such types back to `any`, see #3228 and #3237. I'd be happy to prepare a PR if that's the preferred way to fix it in this case too?

> Btw node v15+ has native AbortController implementation.

Good point. However, Node 15 is an ["experimental" branch](https://nodesource.com/blog/understanding-how-node-js-release-lines-work/) and Node 16 LTS still has [a month left](https://nodejs.org/en/about/releases/) before becoming the "active" development line. 

My suggestion would be to fix the current issue by setting the type to `any`, and then reverting it back to `AbortController` when Node 16 becomes the new "active" line.

**Comment by DigitalBrainJS** [comment]
I don't think it's really necessary to define a more generic type `any | object` for AbortController since:
- node.js v15 is almost at the LTS stage, I guess there are a few months left
- we will make the typing weaker for the client build too
- it's easy to import the AbortController polyfill that provides TS types - the packet size of a few KB doesn't really matter for the server-side, even if you don't use AbortController in the server code yet.
But this is just my personal opinion, and since I do not use TS, I am not too concerned about typings exactness.

**Comment by pbrennand-francis** [comment]
This just created a fairly gnarly build issue via another library (NestJS) which uses Axios, so I'd like to second the "setting the type to any" solution, if only to minimise the number of engineers who need to trace this down.

**Comment by jan-molak** [comment]
> * we will make the typing weaker for the client build too

You're right, that's the consequence of using `any`.

An alternative would be for Axios to provide its own copy of `AbortController`, `AbortSignal`, `AbortSignalEventMap` until Node 16 reaches LTS ([source]( https://github.com/microsoft/TypeScript/blob/f8cb5fa1d7b36d93f63597354106c7d900396bb5/lib/lib.dom.d.ts#L1899-L1936)). This doesn't seem too terrible and provides stronger typing for both front-end and back-end implementations at the cost of slight overheard over a couple of months for Axios:

```typescript
/** A controller object that allows you to abort one or more DOM requests as and when desired. */
interface AbortController {
    /**
     * Returns the AbortSignal object associated with this object.
     */
    readonly signal: AbortSignal;
    /**
     * Invoking this method will set this object's AbortSignal's aborted flag and signal to any observers that the associated activity is to be aborted.
     */
    abort(): void;
}

declare var AbortController: {
    prototype: AbortController;
    new(): AbortController;
};

interface AbortSignalEventMap {
    "abort": Event;
}

/** A signal object that allows you to communicate with a DOM request (such as a Fetch) and abort it if required via an AbortController object. */
interface AbortSignal extends EventTarget {
    /**
     * Returns true if this AbortSignal's AbortController has signaled to abort, and false otherwise.
     */
    readonly aborted: boolean;
    onabort: ((this: AbortSignal, ev: Event) => any) | null;
    addEventListener<K extends keyof AbortSignalEventMap>(type: K, listener: (this: AbortSignal, ev: AbortSignalEventMap[K]) => any, options?: boolean | AddEventListenerOptions): void;
    addEventListener(type: string, listener: EventListenerOrEventListenerObject, options?: boolean | AddEventListenerOptions): void;
    removeEventListener<K extends keyof AbortSignalEventMap>(type: K, listener: (this: AbortSignal, ev: AbortSignalEventMap[K]) => any, options?: boolean | EventListenerOptions): void;
    removeEventListener(type: string, listener: EventListenerOrEventListenerObject, options?: boolean | EventListenerOptions): void;
}

declare var AbortSignal: {
    prototype: AbortSignal;
    new(): AbortSignal;
};
```

However, please note that when I proposed a similar solution for `ProgressEvent` back in #3228, @chinesedfan has chosen an alternative fix using `any` instead ([#3227](https://github.com/axios/axios/pull/3237#issuecomment-691423337)). So with the above proposal, I wanted to stay compatible with their design choices..

> * it's easy to import the AbortController polyfill that provides TS types - the packet size of a few KB doesn't really matter for the server-side, even if you don't use AbortController in the server code yet.

I believe Axios should work for both front-end and back-end without resorting to force developers to use polyfills for the current LTS versions of major runtime environments, such as Node.

---

@chinesedfan - apologies for tagging you in this reply, but could you please let me know which design direction you'd prefer (`any` vs a copy of `AbortController`) and I'd be happy to propose a PR.

Thanks,
Jan

**Comment by armandodlvr** [comment]
Does anyone know if the PR is going to be merge soon? https://github.com/axios/axios/pull/4229

**Comment by andynunes** [comment]
+1 This is causing an issue when upgrading `axios` in a NuxtJS project as well, which is only needed to avoid a vulnerability in earlier versions.

This solution allows upgrading to the latest version of axios without forcing an upgrade to Node v16, which is important.

**Comment by nyalsadiq** [comment]
Any chance a fix will be merged soon? Is there anything we can do to help? :)
