### ISSUE TITLE
JSON requests with an empty string payload have the string `""` passed instead

### ISSUE THREAD

**Issue by moustafaelsisy** [axios/axios#4146]
#### Describe the bug
Somewhere between 0.21.1 (exclusive) and 0.21.4 the behaviour of passing an empty string to the `data` parameter while having the `"Content-Type": "application/json"` header changed. In 0.21.1 the request would still be sent as an empty string, while in 0.21.4 the string `""` (two double quotes) would be sent as the request body instead.

This is not necessarily wrong, as one could argue that an empty body might be an invalid JSON body, although I do find such usage pretty common. But I think this would definitely be a breaking change, and one such example is when calculating request signatures and sending the signature with the request. Users would calculate the signature for an empty string, and not the `""` string.

#### To Reproduce

You can the code below on [runkit](https://npm.runkit.com/axios) and it will print out the `data` for the final `config` object that was used for the request. Notice that it differs from the `data` parameter passed to the axios call.

```js
axios({ method: 'GET', url: 'https://api.github.com', data: '', headers: {Accept: 'application/json', 
"Content-Type":"application/json"} }).then(r => console.log(r.config.data));
```

#### Expected behavior
The request body that was sent would remain empty

#### Environment
 - Axios Version 0.22.0
 - Node.js Version 12.18.3
 - OSX 11.5.2

#### Workaround

One can switch the `Content-Type` header based on whether the request body has any length.

**Comment by jasonsaayman** [comment]
Closing as the above comment address why this functions like It does.

**Comment by bilalmohib** [comment]
Actually @DigitalBrainJS there is a problem that I have API built from Backend Developer and i am working on front end but the api i know its not the best approach but it is a post request with an empty body and has a barrier token authorization header but axios is not accepting it and the header is also cleaned when the body is empty meaning i am receiving unauthorized for that request. I think you must allow the header to be there instead of cleaning it on case of empty body. 

Thanks.
