### ISSUE TITLE
Infinite cycle request

### ISSUE THREAD

**Issue by mila76** [axios/axios#4182]
#### Describe the bug
Infinite cycle request after updating on 1.21.2 and Quasar/Vue
I can't figure out what's is the root cause of that , maybe related to other "similar" bug.
At least if i can have some sort of help what the root cause maybe a possible fix can made on quasar/vue side

#### To Reproduce
I made two simple codepen where you can see the problem
[1.21.1](https://codepen.io/mila76/pen/wvexgoE)
[1.21.2](https://codepen.io/mila76/pen/abwjpdd)

#### Expected behavior
Only one request...

#### Environment
 - Browser [Chrome, Firefox]
 - Browser Version [92+]
 - OS: [Windows]
 - Additional Library Versions [Quasar 2.1.2, Vue 3.2.20]

**Comment by davidmcl** [comment]
Sorry for the delayed response...and I don't really have a preference here, since I now understand the reason for the previous failure was that the `data` parameter should not have been specified for a `GET`, but just a thought...

Since, by definition: The value `null` represents the intentional absence of any object value.

Would it not be acceptable/consistent when `data` is passed as null, that there is no value passed for the body; and aren't you applying semantics when you do a `JSON.stringify` ?  :smile: 

Question... If a `null` was passed for `data` in an axios request using POST, PUT, etc., where `data` is a valid parameter -- would the payload be `null`, empty, or  `'null'` ?  _My_ preference would be option 1, option 2 would be OK, but option 3 is not what I would expect.

Cheers,
David

**Comment by DigitalBrainJS** [comment]
> Would it not be acceptable/consistent when data is passed as null

no, empty body is not a valid JSON payload, so JSON.parse('') will throw an exception

> would the payload be **null**, empty, or 'null' 

The first option confuses me. I wonder how you're going to transfer `null` javascript type through the plain-text protocol without serializing it to a string :) In any case, we're not TC39 and we don't maintain the RFC. If the Axios request is JSON, it follows the JSON RFC.

The other two cases `[empty]|"null"`depend on `content-type` header.
Both `null` & `undefined` passed as the payload will be treated as empty request payload (0 bytes), unless the `content-type` header is set to `application/json`. In this case JSON.stringify is used for non-undefined values:
`undefined` => not set ([empty body])
`null` => `"null"`
`string` => `"string"`
`number` => `String(number)`
`boolean`=> `String(boolean)`
