### ISSUE TITLE
Axios timeout is global and not per request #4236

### ISSUE THREAD

**Issue by Niek** [axios/axios#4237]
#### Describe the bug
This bug was reported 3+ years ago, but closed: #1518

With parallel requests, the timeout options is not honoured per request. Instead, it is taken as a global setting.

#### To Reproduce
Sample code to reproduce:

```js
const axios = require('axios').default;

(async () => {
  const requests = Array.from({ length: 1000 }, (_, i) => {
    return axios.get('https://ipinfo.io/', {
      timeout: 1000
    })
  })

  const resp = await Promise.allSettled(requests)
  console.log(`${resp.filter(r => r.status === 'fulfilled').length} succesful requests`)
  console.log(`${resp.filter(r => r.status !== 'fulfilled').length} failed requests`)
})()
```

#### Expected behavior
By changing the array length to small values (like 10) or by increasing the timeout you will see that all requests succeed.

#### Environment
 - Axios Version: latest (0.24.0)
 - Adapter: HTTP
 - Browser: none
 - Browser Version: none
 - Node.js Version: 16
 - OS: any
 - Additional Library Versions: none

#### Additional context/Screenshots
N/A

**Comment by DigitalBrainJS** [comment]
Hmm. Are you sure that the target server can handle 1000 requests from the same IP just in one second? The request timeout starts counting from the moment its socket is acquired.

**Comment by Niek** [comment]
> Hmm. Are you sure that the target server can handle 1000 requests from the same IP just in one second? The request timeout starts counting from the moment its socket is acquired.
Yes, you can also try e.g. https://www.google.com/favicon.ico as URL instead. Set the # of requests high enough and you will see the majority fails. Increase the timeout again and it fixes the issue.

**Comment by DigitalBrainJS** [comment]
At first sight, it seems that `follow-redirects` makes some bottleneck since we have different results when we use native  HTTP agent by setting maxRedirects to 0.

```
return axios.get('https://www.google.com/favicon.ico', {
  timeout: 1000
})
```
```
4 succesful requests
996 failed requests
```
vs
```
return axios.get('https://www.google.com/favicon.ico', {
  timeout: 1000,
  maxRedirects: 0
})
```
```
806 succesful requests
194 failed requests
```

P.S. I was banned from ipinfo.io with 429 http code just after the first running :)

**Comment by Niek** [comment]
@DigitalBrainJS I tried the `maxRedirects: 0` setting, and that seems to work better indeed. It still fails, but a lot less. So it it related to the timeout at all?

**Comment by nadavpld** [comment]
Adding my 2 cents

I have the following services : 

![image](https://user-images.githubusercontent.com/23098930/144739443-86415446-4119-4a0f-8855-5c54a5482610.png)

Service A is polling Services B, C, D
`await Promise.all(services.map => axios.get(...))`

I took down the **container** of Service D

If the timeout property is not set (i.e using the default one) it works fine, Service B,C are replying and the request to Service D hangs with the default timeout.

Than I've changed the polling to use a timeout as follows :
`await Promise.all(services.map => axios.get(..., { timeout: 2000 }))`
While all services (B,C,D) are running, everything works fine.
Taking down the **container** of Service D causes **all** services to reply with a timeout error.

The more interesting thing - the requests to Service B, C are not arriving.
I've set a breakpoint in both services and it doesnt hit.
After starting the container of Service D, the breakpoint hit and it works fine again.

If I dont take the container down, just shut down the service inside the container, everything works fine.
Services B,C are replying, Service D throws a timeout error after 2000ms.

**Comment by DigitalBrainJS** [comment]
@nadavpld Does the error still occur if `maxRedirects` is set to 0? It would be more convenient to use `allSettled` instead of `all` to dump all responses in the batch.

**Comment by nadavpld** [comment]
@DigitalBrainJS 
I wrote a simple utility service to test some scenarios in order to get some insights

`const results = await Promise.allSettled([axios.get("http://service_a/api/v1/service/health", {timeout: 2000, maxRedirects: 0}), axios.get("http://service_b/api/v1/service/health", {timeout: 2000, maxRedirects: 0})]);`

The `/api/v1/service/health` is a common middleware used by our services.

It acts the same as

`const results = await Promise.allSettled([axios.get("http://service_a/api/v1/service/health", {timeout: 2000}), axios.get("http://service_b/api/v1/service/health", {timeout: 2000})]);`

Both services (or actually, few dozens) were almost Idle so it is not a question of performance.
Just to be sure, I ran the above queries on online containers every 50ms just to be sure it is not a performance issue.

I looked at it further and checked with node-fetch

`
await Promise.allSettled([fetch("http://service_a/api/v1/service/health", {timeout: 2000, follow: 0}), fetch("http://service_b/api/v1/service/health", {timeout: 2000, follow: 0})]);
`

without the `follow` param the result was an `EAI_AGAIN` error.
with the `follow` param the result was a `FetchError: network timeout...`

It seems to me that it might be related with dns resolving in docker.

**Comment by jasonsaayman** [comment]
Closing seems to not be related to Axios
