### ISSUE TITLE
There are inference patterns whose return value is not AxiosInstance.

### ISSUE THREAD

**Issue by kzmat** [axios/axios#4253]
#### Describe the bug

There are inference patterns whose return value is not AxiosInstance.

#### To Reproduce

```ts
import axios from 'axios'

const bar = () => axios.get('')

// compile error
const response: string = await bar()

// Don't detect compile error, although #axios.get return value is AxiosResponse
const response2: string = await axios.get('')
```

#### Expected behavior
response2 detect compile error because `axios.get('')`'s return value is AxiosResponse

#### Environment
 - Axios Version [0.24.0]
 - Node.js Version [16.6.2]
 - OS: [OSX 11.5.2]

#### Additional context/Screenshots
If this type inference is as expected, would you tell me why it is so please.

**Comment by chinesedfan** [comment]
> get<T = any, R = AxiosResponse<T&gt;>(url: string, config?: AxiosRequestConfig): Promise<R&gt;;

Yes, this type inference is as expected. Why not restrict `R` as `extends AxiosResponse<T>`? That's because axios supports interceptors, which can make `axios.get` returns any type of things. See #1605.

> const bar = () => axios.get('')
> const response: string = await bar()

The return type of `bar` is infered as `Promise<AxiosResponse<any>>`(the default T and R). But `bar` is not a generic function, then you can't assign to `response: string`.

> const response2: string = await axios.get('')

Here `axios.get` is a generic function, and `R` was infered as string. So it's OK. Closing first and feel free to reopen if didn't solve your problem.
