### ISSUE TITLE
Question - second axios request wait until the first one finish its job..!

### ISSUE THREAD

**Issue by mohsenomidi** [axios/axios#4265]
#### Describe the issue
I have a react app that uses axios to call the web services. I faced this behavior when the one of my post request takes time. 
assume you are the two axios calls like this: 

if the first axios call takes time to response the second one will not initiate, and just wait till the first call finished.
as I know each axios call will run asyn during the code execution. 

call 1; 
call 2; 

#### Example Code
Code snippet to illustrate your question

```js

axios({
      method: "POST",
      url1,
      data1,
      headers: {
        "System-Context": JSON.stringify(systemContext),
      }
    })
      .then(response => {
        console.log(response);
        return response.data;
      })
      .then(data => resolve(data))
      .catch(error => reject(error));
  });

axios({
      method: "POST",
      url2,
      data2,
      headers: {
        "System-Context": JSON.stringify(systemContext),
      }
    })
      .then(response => {
        console.log(response);
        return response.data;
      })
      .then(data => resolve(data))
      .catch(error => reject(error));
  });
```

#### Expected behavior, if applicable
each axios call should be execute separately without pending to finished first one  

#### Environment
 - Axios Version [0.21.1]
 - Adapter [XHR/HTTP]
 - Browser [Chrome]
 - Browser Version [95.0.4638.69]
 - Node.js Version [e.g. 13.0.1]
 - OS: [Linux 5.4.0-89-generic #100-Ubuntu]
 - Additional Library Versions [React 17.0.2]

#### Additional context/Screenshots
Add any other context about the problem here. If applicable, add screenshots to help explain.

**Comment by dfdeagle47** [comment]
@mohsenomidi 

I think it will be hard for someone to help you out because your code is not a complete example reproducing the issue (also see [this resource](https://stackoverflow.com/help/minimal-reproducible-example)).

Regarding your remark: indeed the API calls are done asynchronously, so API call 2 shouldn't wait for API call 1 to finish before starting AFAIK.

I would suggest giving a more complete example in a CodePen or a similar platform highlighting the issue and that you could share here.

Here's an example of multiple calls to Axios with an artificial delay: https://codesandbox.io/embed/laughing-noyce-9lrbg?fontsize=14&hidenavigation=1&theme=dark

It's not perfect since it doesn't actually increase the request time, but it might help you figure out why it doesn't work in your codebase.

**Comment by mohsenomidi** [comment]
Thank you so much for your distinct and clarity explanation 

It seems you are completely right, the axios works fine in the example, I also developed the API backed in C++ and after some investigation after your reply I find the issue in that part, let me some time to fix that and will reply about the result

Regards,

**Comment by mohsenomidi** [comment]
This was my backend problem. 
Thanks for your help 👍
