### ISSUE TITLE
app configure restClient.axios(axios) gives security warning about unsanitized input from data (SSRF)

### ISSUE THREAD

**Issue by stevek-pro** [axios/axios#4358]
#### Describe the issue
Server Side Request Forgery SSRF: Unsanitized input from data from a remote resource flows into axios, where it is used as an URL to perform a request. This may result in a Server-Side Request Forgery vulnerability.

#### Example Code

```js
app.configure(restClient.axios(axios));
```

#### Expected behavior, if applicable
How can I sanitize this code to get our security scanners to be happy?

#### Environment
 - Axios Version `"^0.24.0"`
 - Browser: BackEnd
 - Node.js Version `^16.0.0`
 - Additional Library Versions `Feathers 4.5.11`

#### Additional context/Screenshots
-

**Comment by Jayqe** [comment]
Hi Steve,

I was facing this issue sending a POST request to hcaptcha (snyk as security scanner) and it turns out this was caused by me missing a line in hcaptcha's documentation as I had the parameters in the URL where the endpoint expected them to be contained in the request body.

Regarding sanitization, In my case, I'm just using the regex.test method expecting an alphanumeric string as a token (Using .match adds another vulnerability warning for CWE-20 aka Improper Input Validation)

Hope this helps you, or anyone else that may end up here, and if doesn't I would suggest adding additional screenshots of the code highlighted in your scanner.

**Comment by nydk2021** [comment]
![ssrf](https://user-images.githubusercontent.com/85289480/176132364-5a245dae-ea88-49a8-aa58-0a214561dfcb.png)

Hello, this is a screenshot of the security scan of our project. We are now using regular verification and have not rescanned. I hope it will be helpful to Axios
