### ISSUE TITLE
Happy Eyeballs with Axios?

### ISSUE THREAD

**Issue by josedgm** [axios/axios#4534]
Hi

Is there a way to implement something like Happy Eyeballs (RFC 8305) in Axios?

This means that if a hostname has several A records in its DNS answer, Axios must continue trying IP after IP until one gets a proper reply. 

Currently, Axios only uses the 1st IP from the DNS reply. Is there a way to force it to continue trying other IPs if the first one is not responsive?

Thanks

**Comment by jasonsaayman** [comment]
Hi,

There is no support for this, however if you want to give it a shot please open a pull request and tag me to review it.

Thanks

**Comment by rpassmore01** [comment]
I am going to try to add this feature unless someone else is already working on this.

**Comment by Rishi556** [comment]
@rpassmore01 Have you made any progress?

**Comment by rpassmore01** [comment]
Sorry I forgot to follow up with this one. I did quite a bit of work trying to get this working, but realized during testing that the HTTP library's request does in fact check other addresses including ipv4 and ipv6. I'm pretty sure that the HTTP library does not use the happy eyeballs algorithm under the hood, so this could still be implemented into Axios. However, it seemed redundant to me since all IPv4 and IPv6 addresses are checked anyways.

**Comment by CommanderStorm** [comment]
@josedgm 
I think this issue is resolved partially in node > 20 as stated in https://github.com/nodejs/node/issues/48145 as node now supports Happy Eyeballs.

(tracking the rest upstream seems like a solid choice)
