### ISSUE TITLE
Use semantic versioning

### ISSUE THREAD

**Issue by mastazi** [axios/axios#4614]
#### Is your feature request related to a problem? Please describe.
In version 0.25, breaking changes were introduced in Axios, despite this being a minor version. This makes life harder for people who manage Updates by Dependabot, Renovate or similar tools.

#### Describe the solution you'd like
Semver

#### Describe alternatives you've considered
Adding Axios to Dependabot's ignore list - but it's not great.

#### Additional context
An example of breaking changes in a minor version can be seen here: https://github.com/axios/axios/blob/master/CHANGELOG.md#0250-january-18-2022

**Comment by jasonsaayman** [comment]
We will be releasing a v1 after 0.27, this should then fix the issues people have with versnioning. However please keep in mind that when releasing unde v0 we are in accordance with SemVer allowed to make breaking changes as we have in the past.

**Comment by DigitalBrainJS** [comment]
Hmm. But minor unstable versions (before v1.0.0) are intended for breaking changes. Only patch versions <v1.0.0 should ensure that there are no breaking changes, so they may consist of new features and/or fixes.
Following npm version resolving rules (https://semver.npmjs.com/): 
^1.2.0 - will select 1.2.0, 1.2.1, **1.3.0, 1.3.1**, and so on
while the same minor operator ^
^0.2.0 - will select only 0.2.0, 0.2.1, 0.2.2 but not **v0.3.0** since it can consist breaking changes.

**Comment by mastazi** [comment]
> But minor unstable versions (before v1.0.0) are intended for breaking changes. Only patch versions <v1.0.0 should 

that's true, fair enough. closing.
