### ISSUE TITLE
AxiosError: Request failed with status code 400

### ISSUE THREAD

**Issue by diegozl** [axios/axios#5691]
### Describe the issue

Hi,

I have a script at Discord that receives messages in one channel and sends them to another via webhook, using Axios. The problem is that it manages to do this only when the message is without an image.

When there is image, it gives the following error:
`AxiosError: Request failed with status code 400`

I activated the console.log to see if it was receiving the URL and Name variables and it is.
`AxiosError: Request failed with status code 400`

The problem is in this line:
`files: [{url: attachments[0].url, filename: attachments[0].name}]`

Does anyone know how to resolve? Thanks! 

### Example Code

```js
const webhookFr = 'https://discord.com/api/webhooks/1101899486201841.../SjzEplc43SamDHuCTsKFHMSe3fh7uRxjLC-BmVlsJ175ByJ-zf2krSQdsEY0hhhSk...';

function whfr(message, nick, avatarURL, attachments) {
  console.log('-');
  console.log(`Message: ${message}`);
  console.log(`User: ${nick}`);
  console.log(`Avatar: ${avatarURL}`);
    console.log(`Link: ${attachments[0].url}`);
    console.log(`Name: ${attachments[0].name}`);
    console.log('-');
    axios.post(webhookFr, {
      content: message,
      username: nick,
      avatar_url: avatarURL,
      files: [{url: attachments[0].url, filename: attachments[0].name}]
    })
      .then(response => console.log(':heavy_check_mark: Sent!'))
      .catch(error => console.log(`🚨 Error: ${error}`))
  }
```

### Expected behavior

I would like the message, username, avatar_url and attachment to be sent, but the attachment is not being sent.

### Axios Version

^1.3.4

### Node.js Version

9.5.0

### OS

Windows 10

**Comment by harshkumar742** [comment]
Based on your issue, it seems that you are trying to send an attachment (image) using the files property in the Axios POST request. However, Discord webhook API expects the image as an embed rather than directly in the files property.

To fix the issue, you should send the attachment as an embed in your Axios POST request. Here's the updated whfr function:

`function whfr(message, nick, avatarURL, attachments) {
  console.log('-');
  console.log(`Message: ${message}`);
  console.log(`User: ${nick}`);
  console.log(`Avatar: ${avatarURL}`);
  console.log(`Link: ${attachments[0].url}`);
  console.log(`Name: ${attachments[0].name}`);
  console.log('-');
  axios.post(webhookFr, {
    content: message,
    username: nick,
    avatar_url: avatarURL,
    embeds: [{
      image: {
        url: attachments[0].url
      }
    }]
  })
    .then(response => console.log(':heavy_check_mark: Sent!'))
    .catch(error => console.log(`🚨 Error: ${error}`))
}
`

**Comment by yasuf** [comment]
closing for now since there have been no more updates
