### ISSUE TITLE
When using headers in axios.get cors error throws

### ISSUE THREAD

**Issue by glassesUSA** [axios/axios#5727]
### Describe the bug

When running my axios request without headers it gets the data with no issue, with header it fails with a cors error.

### Code snippet

```js
const { data } = await axios.get(
      `https://optimaxdev.github.io/perfect-match-iframe/products.csv`,
      {
        headers: {
          "Cache-Control": "no-cache",
          "Content-Type": "application/x-www-form-urlencoded",
          "Access-Control-Allow-Origin": "*",
        },
      }
    );
```

### Expected behavior

For it to work

### Axios Version

1.4.0

**Comment by drod1107** [comment]
The CORS error occurs due to how the server at `https://optimaxdev.github.io/perfect-match-iframe/products.csv` is configured. CORS, or Cross-Origin Resource Sharing, is a mechanism that uses additional HTTP headers to tell browsers to give a web application running at one origin (domain) permission to access selected resources from a server at a different origin.

When you add the headers to your axios request, the request becomes a "non-simple" request and the browser performs a preflight request before the actual request. This preflight request is an OPTIONS request that checks if the CORS protocol is understood and if the actual request is safe to send.

The problem is that the server must include the appropriate CORS headers in the response to the preflight request, indicating that it accepts the actual request. If the server doesn't include the necessary headers in its response, the browser denies the request and you get a CORS error. 

In your case, you are trying to add the "Access-Control-Allow-Origin" header on the client side, but this is a response header, not a request header. It should be set by the server, not the client. You don't have control over the server at `https://optimaxdev.github.io/perfect-match-iframe/products.csv`, so you can't make it add this header to its responses.

You might be able to solve this problem by removing the "Access-Control-Allow-Origin" header from your axios request. But if you need to add headers to your request, and the server doesn't include the necessary CORS headers in its response to the preflight request, you might have to use a proxy server that adds these headers.

Here's an example of how you might modify your axios request:

```javascript
const { data } = await axios.get(
  `https://optimaxdev.github.io/perfect-match-iframe/products.csv`,
  {
    headers: {
      "Cache-Control": "no-cache",
      "Content-Type": "application/x-www-form-urlencoded",
    },
  }
);
```

This might not fix your problem if the server doesn't handle preflight requests properly. In that case, you might need to use a proxy server. In that case, you may need to set up your call on a backend of your own and use your frontend API to call that instead.

Let me know if that helps/makes sense!

**Comment by junkiet** [comment]
today i just happened this case, i use about 3 hours to fix it.

**Sender side:**
// this line very important
axios.defaults.headers.post['Content-Type'] = 'application/x-www-form-urlencoded';
const response = await axios({
    url: `http://localhost:3000/api/auth`,
    method: 'POST',
    data:  {
       username: 'user',
       password: 'pass123'
    },
});

**Server side:**
// this is also very important
// remember set this in header or maybe in middleware request
 setResponseHeaders(event, {
        'Access-Control-Allow-Methods': 'GET,POST',
        'Access-Control-Allow-Origin': '*',
        'Access-Control-Allow-Credentials': 'true',
        'Access-Control-Allow-Headers': '*',
        'Access-Control-Expose-Headers': '*',
    });
