### ISSUE TITLE
Why do we need to replace `:`, `$`, `,`, `+`, `[`, and `]` back

### ISSUE THREAD

**Issue by uinz** [axios/axios#5728]
### Describe the issue

https://github.com/axios/axios/blob/v1.x/lib/helpers/buildURL.js#L14

Hi, I'm confused about the encode behavior, why is this necessary?

### Example Code

```js
/**
 * It replaces all instances of the characters `:`, `$`, `,`, `+`, `[`, and `]` with their
 * URI encoded counterparts
 *
 * @param {string} val The value to be encoded.
 *
 * @returns {string} The encoded value.
 */
function encode(val) {
  return encodeURIComponent(val).
    replace(/%3A/gi, ':').
    replace(/%24/g, '$').
    replace(/%2C/gi, ',').
    replace(/%20/g, '+').
    replace(/%5B/gi, '[').
    replace(/%5D/gi, ']');
}
```

**Comment by uinz** [comment]
> For example, the colon : is used to separate the protocol (like http or https) from the rest of the URL, so if you had a colon in the path part of your URL, it could cause problems. Similarly, the dollar sign $ and the comma , can have special meanings in different contexts and should be encoded to avoid misinterpretation. Plus sign + is often treated as a space character in URLs, and brackets [ and ] are used in URLs to denote IPv6 addresses.

@drod1107 
Thank you very much for your reply, but I still don't understand why these characters need to be replaced back.
If everyone follows the standard encode and decode rules, there shouldn't be any problems.

Can you give a specific example where this replacement is necessary?

**Comment by drod1107** [comment]
Ideally, in good development I should think it won't come up much, if at all. But... 

Let's say your API services a database for a company and the purpose of the DB is tracking employee training. Some employees take a course called "Service+" in the DB, or maybe "C#".

You could, of course, alias these. You could do a lot of things, and most of them are likely a better practice than the replacement method, IMO. 

But this replacement method is one way to do the job while ensuring that the DB reflects the data passed in EXACTLY to the character, without confusing the API with characters that would otherwise short circuit the URI path, and vice versa - the DB can offer an option to select from that includes a special character and the URI isn't shortcircuited by that character, and the user still sees the character on their end. 

Does that make more sense? Or did I misunderstand your question?
