### ISSUE TITLE
New version of axios does not allow for encoding user:password in request URL

### ISSUE THREAD

**Issue by nizar787** [axios/axios#5753]
### Describe the bug

Describe the bug
I am trying to encode

username: user
password: 12345!@

into a request url.

const res = await axios.post(
        http://user:12345!%40@localhost:5000,
        `{"jsonrpc":"1.1","id":"50","method":"test-method", "params":[1,2,3] }`
    );
Returns 401 when we provide the URI encoded version of the password on version 1.4

This request works fine on axios 0.27.2

To Reproduce
You will need a server that requires a username and password that you have the credentials to.

const username = <your username>
const password = <your password>
const hostAndPort = <your host with port number>

const completeUrl = `http://${username}:${encodeURIComponent(
    password,
)}@${hostAndPort/`;

const res = await axios.post(
       completeUrl,
        `{"jsonrpc":"1.1","id":"50","method":"test-method", "params":[1,2,3] }`
    );

### Axios Version

1.4.0

### Browser

chrome

### Browser Version

 114.0.5735.134

### Node.js Version

18.12

### OS

win 11

**Comment by eihli** [comment]
This is expected and it's part of the work involved in bumping across major versions. I[t's expected that you'll have breaks like this when you do a major version change](https://semver.org/). 

In this particular case, it's because version `v0.27.2` was using [Node's deprecated](https://nodejs.org/api/url.html#urlparseurlstring-parsequerystring-slashesdenotehost) `url.parse` and `v1.4.0` is using URL ([see the MDN docs](https://developer.mozilla.org/en-US/docs/Web/API/URL)).

They have different parse logic.

```
> const url = require("url");
> let user = "user"; let password = "12345!@";
> let location = `http://${user}:${encodeURIComponent(password)}@localhost:8080`;
> let oldWay = url.parse(location);
> let newWay = new URL(location);
> console.log(oldWay.auth)
user:12345!@
> console.log(newWay.password)
12345!%40
```
