### ISSUE TITLE
The body format is unexpected when set Content-Type as "application/json;charset=UTF-8" after v1.0.0

### ISSUE THREAD

**Issue by kiner-tang** [axios/axios#5808]
### Describe the bug

The body format is unexpected when set Content-Type as "application/json;charset=UTF-8" after v1.0.0. It is work in 0.27.2.

v0.27.2
![image](https://github.com/axios/axios/assets/10286961/c01d6825-fbea-4f3b-bbfb-72ef1d881e26)

![image](https://github.com/axios/axios/assets/10286961/24ffa2da-15a1-4e45-b5f9-111306b70426)

after v1.0.0

![image](https://github.com/axios/axios/assets/10286961/ddf98f0c-e7a2-4974-919c-b5ec3038f92f)
![image](https://github.com/axios/axios/assets/10286961/56afd11e-7da0-4706-a000-20cd1da08f9c)

### Axios Version

>=1.0.0

### Adapter Version

XHR

### Browser

Chrome

### Browser Version

115.0.5790.114

### Node.js Version

v16.15.1

**Comment by ZangHao0130** [comment]
The same, It seems that the issue is caused by the default `transformRequest` behavior.

I guess that you have passed a formatted value using the method "JSON.stringify". eg:

<img width="455" alt="image" src="https://github.com/axios/axios/assets/111431378/f206f487-1b4f-4c69-9ca2-6ebcb2bba9de">

In my project, I encountered this issue when upgrading the version from **v0.21.1** to **v0.21.2**. After investigation, I discovered that the problem was caused by the following changes， and It transformed the data into format like: JSON.stringify(JSON.stringify(xxxxx))

<img width="1011" alt="image" src="https://github.com/axios/axios/assets/111431378/e655a608-4ec7-44a4-8adc-57d2976688e6">

In version **v0.27.2**，The inferred condition is that：
```
    var contentType = headers && headers['Content-Type'];
    if (isObjectPayload || contentType === 'application/json')
```
<img width="715" alt="image" src="https://github.com/axios/axios/assets/111431378/63c5c3e5-70d7-41bd-90e1-56c5bb6cef41">

And in version **v1.0.0**, it's:
```
    const contentType = headers.getContentType() || '';
    const hasJSONContentType = contentType.indexOf('application/json') > -1;
    if (isObjectPayload || hasJSONContentType )
```
<img width="575" alt="image" src="https://github.com/axios/axios/assets/111431378/9bd4425e-7b27-4e01-8f1a-67364e104a07">

**Comment by kiner-tang** [comment]
My data is the encrypted string. And service accept application/json only, before 1.x, I can add `charset=utf-8` in contentType to resolve this problem. But it broken after 1.x. Can I rollback the logic about hasJSONContent to `contentType === 'application/json'`? Or there has better solution to solve the problem. I'd love to contribute a pr to that

**Comment by ZangHao0130** [comment]
> My data is the encrypted string. And service accept application/json only. Before 1.x, I can add `charset=utf-8` in contentType to resolve this problem. But it broken after 1.x. Can I rollback the logic about hasJSONContent to `contentType === 'application/json'`? Or there has better solution to solve the problem. I'd love to contribute a pr to that

I'm not sure if this is an appropriate solution, but I think you could consider adding the following code：
`transformRequest:(data) => data`
