### ISSUE TITLE
using axios.create - error received in catch is a string (instead of error object) 

### ISSUE THREAD

**Issue by aviadavi** [axios/axios#5817]
### Describe the bug

I'm using axios instance

```
const instance = axios.create({
  baseURL: `${BASE_URL}`,
  headers: { 'Content-Type': 'application/json' },
  withCredentials: true
});
```

When I use instance.post(...) , the parameter in the catch callback is a string : "Request failed with status code 400"

I needed the error object to get the response payload being returned by the server.

For some reason, **if I don't create an instance, and I directly using axios.post('baseURL/api'...) it works fine.**

Trying to use interceptors doesn't solve it.
```
instance.interceptors.response.use(
  response => response,
  error => Promise.reject(error)
);
```

I'm using the latest version available of axios (1.4.0) (it happens also in earlier versions like 0.21.)

### To Reproduce

just use 
```
const instance = axios.create({
  baseURL: `${BASE_URL}`,
  headers: { 'Content-Type': 'application/json' },
  withCredentials: true
});

instance.interceptors.response.use(
  response => response,
  error => Promise.reject(error)
);
```

and try to get the error response payload 

### Axios Version

1.4.0

### Node.js Version

18.12.1

### OS

Mac OS 18.3

### Additional Library Versions

```bash
React 16
```

**Comment by KhurramJalil** [comment]
Hi @aviadavi!

I'm unable to reproduce this issue using axios 1.4.0.

I didn't use any interceptors and have kept things super simple to replicate the issue and whether I use axios.post() directly or use the instance created via axios.create(), I get the error as an object in the catch block.

Can you please try the following code and follow these steps after the react app is started?
- Open up the browser's console and set/check the Info and Errors inside "Custom levels" .
- Hit the "Get Quote" button and observe the error object logged as information and the actual error also.
- Hit the "Get Quote" button again and observe the error object logged as information and the actual error also.

See the image below I took from my browser.
![image](https://github.com/axios/axios/assets/114917595/e74fbbd1-77a7-4c16-9930-3f5d1cf4c038)

The code below uses direct "axios.post()" and "axios instance.post()" methods turn wise every time the "Get Quote" button is clicked and you should see the error as an object rather than a sting in the catch block.

```
import React from 'react';
import './App.css';
import { useState } from 'react';
import axios from 'axios';

function App() {
    const [quote, setQuote] = useState('');
    const [turn, setTurn] = useState(false);
    const BASE_URL = 'https://someinvalidurl.com'
    const instance = axios.create({
        baseURL: `${BASE_URL}`,
        headers: { 'Content-Type': 'application/json' }
    });

    const getQuote = () => {
        setTurn(!turn);

        if (turn) {
            axios.post(`${BASE_URL}`)
                .then(res => {
                    console.log(res.data.content);
                    setQuote(res.data.content);
                }).catch(err => {
                    console.log(err);
                });
        } else {
            instance.post('/non-existant-method')
                .then(res => {
                    console.log(res.data.content);
                    setQuote(res.data.content);
                }).catch(err => {
                    console.log(err);
                });
        }
    }
  return (
    <div className="App">
          <button onClick={getQuote}>Get Quote</button>
          {quote && <p>{quote}</p>}
    </div>
  );
}

export default App;
```

**Comment by aviadavi** [comment]
@KhurramJalil Thanks for taking a deep look into this.

I have been troubleshooting it more, and it seems to be related to "withCredentials" option. if it's true, then status = null and there is no response payload. (in case of an error)

https://codesandbox.io/s/react-16-8-forked-m43rty

**Comment by KhurramJalil** [comment]
> @KhurramJalil Thanks for taking a deep look into this.
> 
> I have been troubleshooting it more, and it seems to be related to "withCredentials" option. if it's true, then status = null and there is no response payload. (in case of an error)
> 
> https://codesandbox.io/s/react-16-8-forked-m43rty

@aviadavi It seems that your originally posted issue is different than the comment you made above. Previously you posted that calling axios.post() returns error as an object (object of type AxiosError to be exact) while calling the same .pos() method on an axios instance) returns error as a string.

I have even used withCredentials: true and still the error is returned as an object of type AxiosError. You can again try my simplified version of the code below instead of the codesandbox link you shared above and see the error in browser console which would be an object no matter you call post method directly as axios.post() or via axois instance.post().

Following is my updated react app code with no other component, utility or hooks used and this time withCredentials: true.

```
import React, { useState } from 'react';
import './App.css';
import axios from 'axios';

function App() {
    const [quote, setQuote] = useState('');
    const [turn, setTurn] = useState(false);
    const BASE_URL = 'https://someinvalidurl.com'
    const instance = axios.create({
        baseURL: `${BASE_URL}`,
        headers: { 'Content-Type': 'application/json' },
        withCredentials: true
    });

    const getQuote = () => {
        setTurn(!turn);

        if (turn) {
            axios.post(`${BASE_URL}`)
                .then(res => {
                    console.log(res.data.content);
                    setQuote(res.data.content);
                }).catch(err => {
                    console.log(err);
                });
        } else {
            instance.post('/non-existant-method')
                .then(res => {
                    console.log(res.data.content);
                    setQuote(res.data.content);
                }).catch(err => {
                    console.log(err);
                });
        }
    }
  return (
    <div className="App">
          <button onClick={getQuote}>Get Quote</button>
          {quote && <p>{quote}</p>}
    </div>
  );
}

export default App;
```

@jasonsaayman @mzabriskie @DigitalBrainJS We can mark this issue as "not reproducible" if you are also unable to reproduce it with the "repro steps" originally mentioned by @aviadavi when the issue was first created and I believe it would be better to create a separate issue with exact "problem details and repro steps" if the originally posted issue is different than the issue I have quote at the start of this comment.

**Comment by aviadavi** [comment]
Closed as not reproduced
