### ISSUE TITLE
Calling postForm doesn't write the boundary key in the Content-Type header before passing the request to the interceptors

### ISSUE THREAD

**Issue by Tri125** [axios/axios#5899]
### Describe the bug

I'm using axios 1.4.0 in nodejs to post a form and a request interceptor is configured.
To build the form data I use the package "form-data" 4.0.0.
Here's a simplified view of the code:

```
import FormData from "form-data";
import type { AxiosInstance } from "axios";

    const fd = new FormData();
    fd.setBoundary("77f77c04-2c7b-4179-aca3-3e0b66bdb77d");
    const buff = Buffer.from("myTest");
    fd.append("test.json", buff, {
      filename: encodeURIComponent("test.json"),
      contentType: "application/json",
      knownLength: buff.byteLength,
    });
 const response = await this.axios.postForm(`http://localhost:1234`, fd);
```

When the request is sent, the server receive the following header: ``Content-Type, multipart/form-data; boundary=77f77c04-2c7b-4179-aca3-3e0b66bdb77d``

However, when inside my ``requestInterceptor`` the ``Content-Type`` header just ``multipart/form-data`` and it's missing the boundary.

### Expected behavior

When posting a form, axios automatically set the Content-Type header to ``multipart/form-data``.

I expect axios to set the Content-Type header with the boundary before handling the request to the request interceptors.

### Axios Version

1.4.0

### Node.js Version

16.13.0

### Additional Library Versions

```bash
"form-data": 4.0.0
```

**Comment by DigitalBrainJS** [comment]
Interceptors are part of Axios core, but the final installation of headers based on the payload, specific to the platform, is done by the adapter immediately before sending the request, which is quite logical. Axios core should not know anything about Node. js-specific implementations and somehow use them outside the adapter, since this violates the components' area of responsibility and will also lead to dead code ending up on the browser platform. It’s hard to imagine why you needed to manually install this header and be able to get it inside the interceptor. Maybe you should change directly the FormData payload inside the interceptor as a workaround...
In addition, you can use the native implementation of FormData in node18, where Axios supports a custom boundary header, but again, it’s hard for me to imagine any practical need for this.

**Comment by Tri125** [comment]
Thank you for the pointers! It looks like using ``post`` and setting the ``Content-Type`` header just like in your example is going to be just perfect.

To fully explain my intention, I require the Content-Type header as well as the full body of the request to generate a HMAC signature to authenticate with an api. Based on the documentation, I incorrectly expected every mutation on the headers to have already taken place once we return from the last interceptor in the chain.

So it's not much about setting the boundary by hand, but being able to access the exact same ``Content-Type`` that will be sent to the server in order to generate a valid authorization header from an interceptor.

You explained why the final ``Content-Type`` is set via the adapter and I have a solution to my specific problem so I will be closing the ticket. Thank you for the provided example.
