### ISSUE TITLE
Node.js 20 compatibility

### ISSUE THREAD

**Issue by Pharb** [axios/axios#5929]
### Describe the bug

Axios tests fail on Node.js 20 (will be next LTS version starting 2023-10-24).

There probably are breaking changes affecting HTTP clients, e.g.:
- https://github.com/nodejs/node/issues/47130
- https://github.com/node-fetch/node-fetch/issues/1735

### To Reproduce

Run tests with Node.js 20: https://github.com/Pharb/axios/actions/runs/6348646385/job/17245665305 

### Expected behavior

Axios works and is tested for Node.js 20

### Axios Version

v1.5.1

### Node.js Version

v20.7.0, v20.8.0

### OS

Ubuntu 22.04.3, macOS 13.6

### Additional context/Screenshots

- https://nodejs.org/en/blog/announcements/v20-release-announce
- https://nodejs.dev/en/about/releases/

**Comment by woodmark-dev** [comment]
Hello there, 
I want to work on this issue. Thank you.

**Comment by MerzDaniel** [comment]
This is a critical bug for us. Has there already been some progress?

**Comment by Pharb** [comment]
@DigitalBrainJS Could you please provide a statement on the plan how to resolve outstanding issues for Node.js 20?

[Currently 4 unit tests fail with Node 20.8.0](https://github.com/Pharb/axios/actions/runs/6563564408/job/17828088098) and Axios is affected by https://github.com/nodejs/node/issues/47130.

**Comment by adijesori** [comment]
@Pharb Did you find a workaround for this? We are suffering from the same

**Comment by Pharb** [comment]
I see that axios v1.6.0 is now tested for Node.js 20 - so this issue can be closed:

- https://github.com/axios/axios/pull/6011
- https://github.com/axios/axios/pull/6021

There are still problems with axios v1.6.2 and Node.js 20 resulting in ECONNRESET on localhost HTTP requests - my current workaround is this:

```ts
 axios.create({
    httpAgent: new Agent({ keepAlive: false })
  });
``` 

The Node.js issue is still open: https://github.com/nodejs/node/issues/47130

**Comment by adijesori** [comment]
> I see that axios v1.6.0 is now tested for Node.js 20 - so this issue can be closed:
> 
> * [fix(dns): fixed lookup function decorator to work properly in node 20.x; #6011](https://github.com/axios/axios/pull/6011)
> * [chore(tests): fixed tests to pass in node v19 and v20 with `keep-alive` enabled; #6021](https://github.com/axios/axios/pull/6021)
> 
> There are still problems with axios v1.6.2 and Node.js 20 resulting in ECONNRESET on localhost HTTP requests - my current workaround is this:
> 
> ```ts
>  axios.create({
>     httpAgent: new Agent({ keepAlive: false })
>   });
> ```
> 
> The Node.js issue is still open: [nodejs/node#47130](https://github.com/nodejs/node/issues/47130)

Thanks @Pharb! Will try that

Does this node 20 issue happens to you only on localhost HTTP requests? For us it is happening also with remote calls

**Comment by Pharb** [comment]
> Does this node 20 issue happens to you only on localhost HTTP requests? For us it is happening also with remote calls

I did not have problems with HTTPS remote calls. For me it was only a problem with HTTP requests to localhost.

**Comment by akwodkiewicz** [comment]
For us it's also happening with remote calls, but I guess the URL does not matter here.

The most important thing is that while the workaround works[^1], it cannot be easily applied to projects, because axios is very often [^2] a dependency of some 3rd party SDKs. Sometimes the packages allow you to pass some axios config to initialize them, but it is not common. And I'm not sure if that's even possible to override the axios config globally for all deps.

So, unfortunately, I think we still need to wait for the resolution of the issue on Node's side (https://github.com/nodejs/node/issues/47130)

[^1]: I did not test it myself, but I believe you 😄 
[^2]: I'd even say it's a de-facto standard HTTP library

**Comment by jfaissolle** [comment]
It seems I am encountering this problem with Axios 1.6+ and Node 20.10 when using `Promise.all()` to simultaneously run several requests on the same server.

**Comment by SebasAnasco1517** [comment]
I have this issue with Axios 1.6.7 and node 20

**Comment by born2net** [comment]
same here, node 20 and does not send texts

**Comment by born2net** [comment]
> Hi, do you know if this is going to be corrected in node? I have this issue with Axios 1.6.7 and node 20.

same issue here :/

**Comment by softy2k** [comment]
Same issue with **Node 20.12.1** and **Axios 1.6.8**
Is Ok whit same config but with **Node 18.20.1**

**Comment by joelin-vyond** [comment]
H there,
Since Node c22 is just released, it would be great to know whether the issue has been fixed in Node 22, or we still have to use node v16 or the other http client `undici`?

Thanks,
Joe Lin

**Comment by elovin** [comment]
We do not have this issue at all and we have been using node 20 just after it entered LTS.
Although we use RXJS to wrap promises and handle retries.

**Comment by vatte21** [comment]
> We do not have this issue at all and we have been using node 20 just after it entered LTS. Although we use RXJS to wrap promises and handle retries.

could you please provide some examples of using RXJS ?

**Comment by JohnLRBrock** [comment]
Still seeing this issue with node 20 and axios 1.6.1

We're currently working around it by creating axios clients with `keepAlive: true`

**Comment by adijesori** [comment]
We are looking to upgrade our nodejs to 22 or even 24. Was this issue fixed in those later versions > 20?
CC @JohnLRBrock @softy2k @jfaissolle @SebasAnasco1517 @akwodkiewicz

**Comment by jasonsaayman** [comment]
i beleive the latest version should be working as we do run tests against 22 & 24 if not please mention me and i can have a look into this asap

**Comment by akwodkiewicz** [comment]
@adijesori no, it was not fixed in Node at all AFAIU

But we successfully upgraded from Node 18 to 22 by runnign the following code at the app startup (credits due to @Zvrbsky):

```ts
import { Agent as HttpAgent } from 'http';
import { Agent as HttpsAgent } from 'https';

// Needed due to breaking change in Node 19
require('http').globalAgent = new HttpAgent({ keepAlive: false });
require('https').globalAgent = new HttpsAgent({ keepAlive: false });
```

(the code above is obviously in TS)

You could probably also [pre-load this with `--require` in Node](https://nodejs.org/api/cli.html#-r---require-module) to make sure it's run before the rest of the code, if you want to be 100% sure

**Comment by DigitalBrainJS** [comment]
Our tests would not be able to catch the keep-alive bug, since the tests assume a clean launch without side effects, so the test server is restarted for each test, which means that keep-alive will not be used. As [I mentioned earlier](https://github.com/axios/axios/issues/6113#issuecomment-2656966165), the bug is related to race conditions in the Node scheduler for those requests whose timeout was almost exhausted before allocating this socket from the pool on the client side. For this, it would be necessary to write a specialized test. I believe the Node team has already fixed this bug.

For affected versions, you can use a workaround:
```js
const instance = axios.create({
  httpAgent: new http.Agent({ keepAlive: false}),
  httpsAgent: new https.Agent({ keepAlive: false})
});
```
