### ISSUE TITLE
"./node_modules/axios/lib/utils.js" contains a reference to the file "process/browser".

### ISSUE THREAD

**Issue by filoucrackeur** [axios/axios#6571]
### Describe the bug

hi,

i use axios with symfony project and "encore" with webpack now there is a conflict with process/browser call. 
The bug appears on version 1.7.3 with the modifcation of the file ./node_modules/axios/lib/utils.js

```bash
yarn encore dev
yarn run v1.22.22
$ /Users/toto/project/node_modules/.bin/encore dev
Running webpack ...

 ERROR  Failed to compile with 1 errors                                                                                                                                   20:28:11

Module build failed: Module not found:
"./node_modules/axios/lib/utils.js" contains a reference to the file "process/browser".
This file can not be found, please check it for typos or update it if the file got moved.

webpack compiled with 2 errors
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
```

in my webpack.config.cjs

```js
    .addPlugin(new webpack.ProvidePlugin({
        process: 'process/browser',
    }))
```

### Axios Version

1.7.3

### Additional Library Versions

```bash
webpack
webpack-encore
```

**Comment by mikeCapozziICF** [comment]
I can confirm I have the same issue here.  If I run version 1.7.2, I do not have the issue.  When I update to 1.7.3 (because of the high vulnerability fix), I then cannot build the app.  The following error in my case:

Module not found: Error: Can't resolve 'process/browser' in '..../node_modules/axios/lib'
Did you mean 'browser.js'?
BREAKING CHANGE: The request 'process/browser' failed to resolve only because it was resolved as fully specified
(probably because the origin is strict EcmaScript Module, e. g. a module with javascript mimetype, a '*.mjs' file, or a '*.js' file where the package.json contains '"type": "module"').
The extension in the request is mandatory for it to be fully specified.
Add the extension to the request.

My `config-overrides.js` has aways had :

```
    new webpack.ProvidePlugin({
      process: 'process/browser'
    })
```

@filoucrackeur - Curious if you have since found any workarounds.

**Comment by filoucrackeur** [comment]
@mikeCapozziICF my workaround ----> downgrade version of axios to         "axios": "^1.6.8",

**Comment by DigitalBrainJS** [comment]
Webpack is probably trying to import shim for mocking `process` global, which is incorrect since there is no actual usage of this variable in the code on the browser platform- only a check for the existence of the variable to determine the platform type. This is most likely a bug or misconfiguration of webpack.
https://github.com/axios/axios/blob/ee208cfcae8770ac579f26e7278867567886e026/lib/utils.js#L698

**Comment by mikeCapozziICF** [comment]
> @mikeCapozziICF my workaround ----> downgrade version of axios to "axios": "^1.6.8",

Doh!  Only problem with that is 1.7.4 fixes a high severity vulnerability which gives us no option.

Thanks @DigitalBrainJS , I'll look into that.

**Comment by erwanriou** [comment]
last version of website + last version of axios = crash of build
5.94 & 1.7.7

Not sure who is at fault but yes i cannot fix the vulnerability until this is fixed.

**Comment by mmbutton** [comment]
@mikeCapozziICF I was able to work around this by changing `new webpack.ProvidePlugin({
      process: 'process/browser'
    })`
    To
    `new webpack.ProvidePlugin({
      process: 'process/browser.js'
    })`

**Comment by xavierfacq** [comment]
Problem is fixed for me by applying the following code (@see https://github.com/microsoft/PowerBI-visuals-tools/issues/365#issuecomment-1099716186)

In my config-overrides.js, add lines:

`config.module.rules.push({
      test: /\.m?js/,
      resolve: {
          fullySpecified: false
      }
  })`

![image](https://github.com/user-attachments/assets/656ef795-656e-478f-a538-4da0afc78ef2)

**Comment by jjunohj** [comment]
@xavierfacq It does works for me! THX 🙏

**Comment by houchaowei** [comment]
我又遇到了这个问题，axios 版本号 1.7.7
![image](https://github.com/user-attachments/assets/277797aa-7378-44d9-9bab-5c67acc0ec09)
有人可以帮助我吗

**Comment by houchaowei** [comment]
> 我又遇到了这个问题，axios 版本号 1.7.7 ![image](https://private-user-images.githubusercontent.com/17643027/371482354-277797aa-7378-44d9-9bab-5c67acc0ec09.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3Mjc0MzE2OTcsIm5iZiI6MTcyNzQzMTM5NywicGF0aCI6Ii8xNzY0MzAyNy8zNzE0ODIzNTQtMjc3Nzk3YWEtNzM3OC00NGQ5LTliYWItNWM2N2FjYzBlYzA5LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA5MjclMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwOTI3VDEwMDMxN1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTMyMDg4ODRjZWU0Y2ZmYWQ4OTI3MzlmODY3ZGMzMDY3MGM2ZTA1OWIxYzc0YzM5OGFlNTNkZDI1MjMyZTg1MTEmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.AY64FDvU9Ms8-HcoPRNBR43fNQt6iZAyy2uhnTE-MOA) 有人可以帮助我吗

node 版本：v16.15.1
yarn 版本：1.22.15
os：mac M1
axios：1.7.7
