### ISSUE TITLE
What's up with all the updates?

### ISSUE THREAD

**Issue by eldoy** [axios/axios#6586]
### Describe the issue

Axios used to be a stable package, now there's updates every week. What's up with that? Makes me want to stop using it.

**Comment by eldoy** [comment]
Wrong, the updates proves that you are not stable, or you wouldn't need updates, right? 

I'll just switch to fetch, these updates are really annoying.

**Comment by DigitalBrainJS** [comment]
> Wrong, the updates proves that you are not stable, or you wouldn't need updates, right?

Following this logic, Firefox is not stable, as it gets updated almost every day, which is annoying because as we know, true perfection should not have versions after 1.0.0. 
Any development should strive to deliver product improvements to the end user with a minimum delay, this is the essence of Agile, so without a boot screen like "Working on Axios updates. Don't turn off your PC." it's hard to imagine what could be "really annoying" about updates.

**Comment by DigitalBrainJS** [comment]
> Every time I see Axios being updated there is a chance my app will break, and I need to react to that, it's stressful and annoying

And why would you update Axios on a working project? The only reason could be CVE. In other cases, nobody forces you to update.

**Comment by eldoy** [comment]
Because I don't want the bugs you just fixed in my software? Especially not when it's a networking tool. 

Frequent updates = unstable (bad). No updates = stable (good). Not in your world?
