### ISSUE TITLE
Support for multiple request params with same name?

### ISSUE THREAD

**Issue by Mahi** [axios/axios#777]
The current way of sending a `GET` request with query params like `?foo=5&bar=3` works like this:

    axios.get('http://example.com/', { foo: 5, bar: 3 });

But since JS objects don't support multiple fields with the same key, there's no way to construct a request with multiple values for the same field (some APIs *require* this), such as this example:

    http://example.com/?foo=5&bar=3&foo=7

I'd suggest adding a way to create the above URL by providing a list of arguments instead:

    axios.get('http://example.com/', { bar: 3, foo: [5, 7] }

**Comment by supra28** [comment]
This is not a limitation of this library, you are just doing it wrong.
those are query params and not a js object as you mentioned, construct them using URLSearchParams API as given in the docs, or alternatively you can use qs library (also mentioned in the docs.

eg.
querystring.stringify({ foo: 'bar', baz: ['qux', 'quux'], corge: '' })
// returns 'foo=bar&baz=qux&baz=quux&corge='

**Comment by Mahi** [comment]
> those are query params and not a js object as you mentioned

They are query params passed to `get()` *as a JS object*. `get()` then probably constructs the query param string out of the JS object. I am currently using `stringify()`, but since there is clearly a built-in support for passing the query params as an object, why not improve it and add support for passing multiple params of the same key? Then we wouldn't need `stringify()` anymore.

**Comment by ventralnet** [comment]
@Mahi I agree, this is a slightly confusing implementation detail but it may just be because I am coming from the Angular 1.x $http service which does this GET param conversion for you.  Doing it for every API call may become error prone.  Looking at the docs I would probably suggest configuring a global paramSerializer like this

`axios.defaults.paramsSerializer = function(params) { /* ... */ };` 

In the paramsSerializer you can implement one of the strategies @adam-lynch  or @supra28 suggest using QS or the URLSearchParams API

**Comment by ventralnet** [comment]
paramSerializer doesn't seem to exist on defaults anymore.  Does anyone know of a way to configure a default paramsSerializer?

**Comment by AlexByte** [comment]
What about this?

**Comment by chinesedfan** [comment]
> why not improve it and add support for passing multiple params of the same key?

The problem is that the default `paramsSerializer` is not powerful enough. We can make axios as powerful as `qs`, but I think it will violate the design principle that keeping axios focused on the core functionalities. That's why axios provides an option, `paramsSerializer`, to allow users to import other packages to fulfill their requirements.
